### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by ghost** [MrS0m30n3/youtube-dl-gui#100]
Hi again and thanks for answer i would test what you wrote. I have another problem with subtitles. I dowload from Swedish play site like svtpl.se and oppetarkiv.se And when i download subtitles they use wsrt instead of srt on subtitles. In vlc there are no problem just delete the w from wsrt but in the standalone player it gets strange characters. dlg can both download subtitles and embedd them do you think its possible for the program to convert the subtitle file from wsrt to str automatically?

**Comment by nodiscc** [comment]
https://github.com/rg3/youtube-dl/#subtitle-options

In `Options > Commands`

      --sub-format FORMAT
              Subtitle format, accepts formats preference, for example: "srt" or "ass/srt/best"

so `--sub-format srt`

**Comment by nodiscc** [comment]
@MrS0m30n3 I think this issue can be closed.
