### ISSUE TITLE
Max download

### ISSUE THREAD

**Issue by ghost** [MrS0m30n3/youtube-dl-gui#101]
I don´t know how and were i change the max download option. Its there a new release coming soon maybe on dlg with this option wich make it easier?

**Comment by nodiscc** [comment]
You have to edit the value of `workers_number` L243 in optionsmanager.py

See here https://github.com/MrS0m30n3/youtube-dl-gui/blob/aa74cc20d05ea932870baa9c13c3c06f03596c61/youtube_dl_gui/optionsmanager.py#L243

**Comment by serpico10** [comment]
I cant find the file you want me to change

**Comment by nodiscc** [comment]
https://github.com/MrS0m30n3/youtube-dl-gui/issues/20#issuecomment-71318295:



> Now you can change the number of max parallel downloads by editing the 'workers_number' option on your settings.json file (~/.config/youtubedlg/settings.json). Note that you need to restart youtubedlg for the changes to take place. Also, this option will be added on the new GUI layout (as a GUI option) so you wont have to edit the settings.json file everytime.

>I will leave this issue open until i push the new GUI layout.

**Comment by serpico10** [comment]
Hi
I have some ideas about the update on dlg gui are you interested about that ?

**Comment by serpico10** [comment]
Hi
I have some ideas about the new gui if you are interested.

**Comment by nodiscc** [comment]
@MrS0m30n3 I think this issue can be closed.
