### ISSUE TITLE
max download

### ISSUE THREAD

**Issue by serpico10** [MrS0m30n3/youtube-dl-gui#102]
I cant find the file to change. I still wonder if there are a new version out soon and if so maybe some Changes i preferred are in the never version. Like more than 3 download at a time and delete finished files  for example. The actual version of dlg is  a year old now. I like dlg its a very good program and can be even better with some small Changes.

**Comment by nodiscc** [comment]
please keep this in https://github.com/MrS0m30n3/youtube-dl-gui/issues/101
