### ISSUE TITLE
Embed subtitle

### ISSUE THREAD

**Issue by ghost** [MrS0m30n3/youtube-dl-gui#103]
How can I embed subtitle in mp4 file if I want Swedish language I cant choose Swedish in options?
I also winder if its possible to download  a hole tv serie at a time.

**Comment by nodiscc** [comment]
> How can I embed subtitle in mp4 file

youtube-dl-gui is just a wrapper around https://github.com/rg3/youtube-dl/. From their README:

    --embed-subs                     Embed subtitles in the video (only for mp4, webm and mkv videos) 

>  I cant choose Swedish in options?

Does the video have swedish subs available at all?

> download a hole tv serie at a time

If the serie has a playlist available, you can download the playlist directly. Otherwise you have to enter all the video URLs manually.

**Comment by podab** [comment]
Hi again
Yes the video have Swedish subs but in the program i cant choose Swedish i can choose download all subs but then i cant get the option embed subs in mp4 file.

How do i know if the serie has a playlist i add a link so you can check 
http://www.oppetarkiv.se/etikett/titel/Graven/

**Comment by nodiscc** [comment]
> in the program i cant choose Swedish

The subtitle languages are hardcoded in https://github.com/MrS0m30n3/youtube-dl-gui/blob/aa74cc20d05ea932870baa9c13c3c06f03596c61/youtube_dl_gui/optionsframe.py#L1174, Swedish needs to be added. According to https://www.loc.gov/standards/iso639-2/php/code_list.php it should be ` ("sv", _("Swedish")),`.

> How do i know if the serie has a playlist i add a link so you can check 

The only playlist extractors that [youtube-dl](https://github.com/rg3/youtube-dl/) supports are:

```
$ youtube-dl --list-extractors | egrep -i "playlist|album"
audiomack:album
Bandcamp:album
crunchyroll:playlist
dailymotion:playlist
daum.net:playlist
DeezerPlaylist
gameone:playlist
ImgurAlbum
kuwo:album
LetvPlaylist
MySpace:album
netease:album
netease:playlist
NiconicoPlaylist
nowness:playlist
NRKPlaylist
PornHubPlaylist
qqmusic:album
qqmusic:playlist
soundcloud:playlist
THVideoPlaylist
tudou:album
tudou:playlist
vimeo:album
WebOfStoriesPlaylist
yandexmusic:album
yandexmusic:playlist
youtube:playlist
youtube:playlists
zingmp3:album
```

So for oppetarkiv.se you need to download them manually one at a time, or write a script to extract the episodes URLs, or even better write [a youtube-dl extractor](https://github.com/rg3/youtube-dl/#adding-support-for-a-new-site) for this site and propose them to add it in.

**Comment by podab** [comment]
Hi 
I don't think I can do the  changes in the code I are not a programmer. I read in the other comments that other users ask for some changes maybe you can fix it in the new gui that you write are coming.
Can I ask for some functions maybe.

More than 3 downloading files at a time
Support for Swedish language in subtitles download
Delete finished files from downloadlist
And when are you going to release the new gui?

**Comment by nodiscc** [comment]
I am not the developer. @MrS0m30n3 has been idle for some time. You can easily add this single line, or wait for the maintainer to do the required changes.

**Comment by podab** [comment]
Ok i try to add Swedish language like you wrote. How do i edit the jsonfile can i do it with notepad or must i use specific edit programme for that?

**Comment by podab** [comment]
Ok thanks i will do a try. But how can i edit the file must i use a specific edit program or can i use notepad?

**Comment by nodiscc** [comment]
Notepad is fine. Don't forget any spaces, commas or parentheses.

**Comment by podab** [comment]
This file are zipped on my disc should i opened it and edit and then zip again?
Sorry for the many questions because i dont done this before.

**Comment by MrS0m30n3** [comment]
Closing, since the Swedish subtitles option is now available in the new gui https://github.com/MrS0m30n3/youtube-dl-gui/commit/136e7219fe7d238cd9dc1854e1d323e485eee0fb.

Also, to answer the other questions asked in case someone else sees this:

>More than 3 downloading files at a time

Read https://github.com/MrS0m30n3/youtube-dl-gui/issues/20

>Delete finished files from downloadlist

Read https://github.com/MrS0m30n3/youtube-dl-gui/issues/24

>And when are you going to release the new gui?

Probably before 2017
