### ISSUE TITLE
%(autonumber)s not incrementing...

### ISSUE THREAD

**Issue by hj8ag** [MrS0m30n3/youtube-dl-gui#105]
I'm running through a list of about 1000 videos, that ideally I'm trying to label with a number that is equivalent to a spreadsheet that they come from (starting from 00001). I've specified this command in Output > Custom Template 

 `%(autonumber)s-%(title)s.%(ext)s`

However all of my files are coming out with the following:

00001-Untitled.mp4 etc.

Is there any obvious cause for this?

I'm running OSX 10.11.4, with youtube-dl-gut installed through homebrew

**Comment by MrS0m30n3** [comment]
Hi, @hj8ag 

What do you mean by "all my files are coming out with the following" ?
All your files have Untitled or the autonumber does not increment ?
I just tried it out and it worked fine for me.

**Comment by MrS0m30n3** [comment]
Closing since this issue is old. Feel free to re-open if you have to.
