### ISSUE TITLE
Only one link at a time

### ISSUE THREAD

**Issue by lilleindi** [MrS0m30n3/youtube-dl-gui#109]
Hi
Im trying to download some Pluralsight videos. 
But getting some errors because of overuse...

Is it possible to only download one link at a time?

Regards

**Comment by nodiscc** [comment]
https://github.com/MrS0m30n3/youtube-dl-gui/issues/53

> Currently you can change the number of simultaneous downloads by editing the workers_number option under your settings file. To find the path of your settings file start youtube-dl-gui and hit the options button. At the bottom of the General tab you should see the Settings File label which shows the absolute path to your settings file.

**Comment by lilleindi** [comment]
I tried editing the workers_number, but overtime i restart it make it back to 3?
And if i start youtube-dlg and then change the number to 1, nothing happens when i hit download?

**Comment by lilleindi** [comment]
I tried a little bit more digging...
Reinstalled youtube-dlg, and it works with workers_number 3
Then i changed it to 1 and it stops working..
Now if i change it back to 3 it still dont work..

**Comment by Korons** [comment]
Can you post your config file?

**Comment by MrS0m30n3** [comment]
@lilleindi Closing this feel free to reopen
