### ISSUE TITLE
Not an issue but a request: Vimeo or other sources?

### ISSUE THREAD

**Issue by fabiomb** [MrS0m30n3/youtube-dl-gui#110]
I know the app is called youtube-dl-gui but i can download vimeo videos with the command line app, it could be a nice addition to download them with the gui. I know, is not a issue!! ;) :+1:

**Comment by nodiscc** [comment]
You already can. Youtube-dl-gui just uses youtube-dl as a backend so the [same sites are supported](https://rg3.github.io/youtube-dl/supportedsites.html). Downloading from Vimeo works.

**Comment by fabiomb** [comment]
you are right, the problem i found is if you change the resolution, if you leave "default" it works, but not if you choose  720p mp4 or something

**Comment by nodiscc** [comment]
Well spotted I reported this at https://github.com/MrS0m30n3/youtube-dl-gui/issues/111
