### ISSUE TITLE
Formats list should not be hardcoded/support more formats

### ISSUE THREAD

**Issue by nodiscc** [MrS0m30n3/youtube-dl-gui#111]
https://github.com/MrS0m30n3/youtube-dl-gui/issues/110

> you are right, the problem i found is if you change the resolution, if you leave "default" it works, but not if you choose 720p mp4 or something

https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/youtube_dl_gui/optionsframe.py#L850

```
FORMATS = twodict([
        ("17", "3gp [176x144]"),
        ("36", "3gp [320x240]"),
        ("5", "flv [400x240]"),
        ("34", "flv [640x360]"),
...
```

Whereas

```
$ youtube-dl --list-formats 'https://vimeo.com/163535912'
[vimeo] 163535912: Downloading webpage
[vimeo] 163535912: Extracting information
[vimeo] 163535912: Downloading webpage
[vimeo] 163535912: Downloading JSON metadata
[vimeo] 163535912: Checking Original video URL
[vimeo] 163535912: Downloading m3u8 information
[info] Available formats for 163535912:
format code  extension  resolution note
hls-meta     mp4        multiple   Quality selection URL 
hls-621      mp4        640x360     621k , avc1.4D4016, mp4a.40.2
http-360p    mp4        640x360    , 30fps
hls-1748     mp4        960x540    1748k , avc1.64001F, mp4a.40.2
http-540p    mp4        960x540    , 30fps
hls-2804     mp4        1280x720   2804k , avc1.640020, mp4a.40.2
http-720p    mp4        1280x720   , 30fps
hls-4830     mp4        1920x1080  4830k , avc1.640028, mp4a.40.2
http-1080p   mp4        1920x1080  , 30fps
Original     mov        1920x1080  354.11MiB (best)
```

**Comment by MrS0m30n3** [comment]
Yeah i am aware of that. I also want to implement an option to automatically extract the video-audio formats dynamically, but there are other things that needs to be done first.

**Comment by JJRcop** [comment]
A drop down of common picture formats like 720p, 1080p could be implemented as a 'quality' selector in the main UI. Then the selected quality can be fed into the youtube-dl format selector like this: "bestvideo[height<={quality}]". This would improve usability, and a simple quality selector that is ignorant of the specific video codecs is the reason I don't reccomend this program to my dad.

 If I teach him how to add the format selector under advanced options, then why use this GUI in the first place?

**Comment by nodiscc** [comment]
Unmaintained project, use https://github.com/axcore/tartube
