### ISSUE TITLE
Something breaks ffmpeg

### ISSUE THREAD

**Issue by Zhico** [MrS0m30n3/youtube-dl-gui#112]
Hi. Great GUI you made.

Problem in short.
This link works fine.
`https://www.dr.dk/tv/se/spise-med-price-saeson-7/spise-med-price-pa-tur-1-6`
This does not.
`https://www.dr.dk/tv/se/spise-med-price-saeson-7/spise-med-price-pa-tur-2-6`
The link works fine in another youtube-dl gui. I think it's has something do with the way youtube-dl downloads the non working links and this breaks ffmpeg. 
You might need to use a VPN to access the links, as they are from danish national tv.

**Comment by Jan02** [comment]
@Zhico the app is for youtube

**Comment by nodiscc** [comment]
@Zhico please paste the contents of your error log here

**Comment by MrS0m30n3** [comment]
Closing, @Zhico if you still face the same problem you can re-open the issue.
