### ISSUE TITLE
Is it possible to get/download auto best video and audio quality? 

### ISSUE THREAD

**Issue by skeith** [MrS0m30n3/youtube-dl-gui#115]
I try to download a video that is available on 360p to 720p and it only download 720p it I set the video and audio quality that way. Is there auto setting?

**Comment by nodiscc** [comment]
Leaving the video format on `default` always downloads the best available quality.

**Comment by nodiscc** [comment]
@skeith please close if it fixes your issue.

**Comment by skeith** [comment]
Thank you for the help. Sorry for late response.
