### ISSUE TITLE
[fork] Project is unmaintained

### ISSUE THREAD

**Issue by nodiscc** [MrS0m30n3/youtube-dl-gui#119]
Hi all, judging by the absence of updates since 6 months, no replies to open issues that are now piling up in the bug tracker, solved issues not being closed, and Pull Requests not being revieved/merged, I guess that @MrS0m30n3 has finally decided to give up on youtube-dl-gui.

Therefore I propose a fork of the current repository, in the hopes that changes will be merged here when the original developer comes back. I am a beginner at Python so any help is welcome. I have created a Github organization repository at https://github.com/youtube-dlg/youtube-dl-gui, feel free to send Pull Requests and open issues for problems you might encounter.

I will resume work on the program in the coming weeks.

Ping @unreal666 @Penaz91 @smehemmed @dialog @okovarec @eliluminado @qinfeng @52Jolynn @farseenabdulsalam since you have pending Pull Requests. I will do my best to get them merged in the fork, in the mean time you can reopen them there to save me the work of doing it manually.

Also ping @dstftw @Arttse @dnlsrl @pr0d1r @ikkebr @Fironet @FSMaxB @daviewales since you have contributed to this project in the past.

**Comment by farseenabdulsalam** [comment]
Hi  @nodiscc, It's my pleasure to join the development.

**Comment by farseenabdulsalam** [comment]
@nodiscc, I just had a look at your fork.
I thought github would copy all of the issues to the new fork.

**Comment by nodiscc** [comment]
@farseenabdulsalam No it doesn't but feel free to reopen those you think are valuable.

**Comment by FSMaxB** [comment]
Feel free to ping me if you need an update to the german translation.

**Comment by nodiscc** [comment]
@FSMaxB If you want to update the german translation please follow the translation instructions at https://github.com/youtube-dlg/youtube-dl-gui and send a Pull Request, I would merge it.

**Comment by FSMaxB** [comment]
What I meant is that you can ping me, if the translation needs an update because the GUI was changed.

**Comment by Penaz91** [comment]
My pull request seems to be already part of the fork, do I have to do anything?

**Comment by nodiscc** [comment]
@Penaz91 Yes I have already merged it. You don't have to do anything.

**Comment by MrS0m30n3** [comment]
@nodiscc 
I will never give up on youtube-dl-gui. I just had no time i had to study for my university, CCNA etc..
Please everyone who is interested add your name below and i am going to add you to the project as a collaborator.

**Comment by nodiscc** [comment]
Hi @MrS0m30n3 glad to hear you're planning to continue maintenance of youtube-dlg! I have added you to the `owners` group of the https://github.com/youtube-dlg organization. Feel free to merge the current master branch here (basically it's just this repo's master branch + PRs merged - [diff](https://github.com/MrS0m30n3/youtube-dl-gui/compare/master...youtube-dlg:master)), and delete the organization, or move your repo to the organization, etc, whatever you like. I was getting worried that this cool project would end up abandoned.

There is an interesting patch/rewrite with PyQT pending at https://github.com/youtube-dlg/youtube-dl-gui/pull/5. I thought I would have some time to work on it, but like you I had limited time :/

**Comment by nodiscc** [comment]
INteresting issues/requests have been brought up at https://github.com/youtube-dlg/youtube-dl-gui/issues by the way.

**Comment by MrS0m30n3** [comment]
I am going to check-merge the diff tomorrow. I will also transfer the issues here.

**Comment by MrS0m30n3** [comment]
Closing this, anyone else who is interested add your name below and i will add you as a collaborator
