### ISSUE TITLE
[OS X] No module named wx

### ISSUE THREAD

**Issue by Lexmark0381** [MrS0m30n3/youtube-dl-gui#121]
To install wx, run 

`brew install wxpython`

If you don't have homebrew installed, please visit [brew.sh](brew.sh) first and install brew.

**Comment by nodiscc** [comment]
@Lexmark0381 So what should we put in the `Mac:` section of https://github.com/MrS0m30n3/youtube-dl-gui#installation ?

**Comment by Lexmark0381** [comment]
Requirements are: python2 and wxpython. Both of them can be obtained with Homebrew.
First install brew from the link stated before, than run:
`brew install python wxpython`
After the installation of these 2, i was able to launch youtube-dl-gui and succesfully download what i needed.
P.s. There are still errors, but in the end it works!
