### ISSUE TITLE
Add access to --embed-thumbnail for audio files

### ISSUE THREAD

**Issue by MrS0m30n3** [MrS0m30n3/youtube-dl-gui#124]
From @philipzae on Jul 11 2016

> Similar to the 'write thumbnail to disk' option in the Filesystem tab, an option to embed a thumbnail in the audio file would be most useful and it is supported in m4a files as long as atomicparsley is installed.

Original issue: https://github.com/youtube-dlg/youtube-dl-gui/issues/14

**Comment by CodePunk-** [comment]
I'm with him. Would be nice to have this option.
