### ISSUE TITLE
Set --no-playlist option by default

### ISSUE THREAD

**Issue by MrS0m30n3** [MrS0m30n3/youtube-dl-gui#128]
From @philipzae on Jul 8 2016

> The url of a video when played from within a playlist is like < https://www.youtube.com/watch?v=rYUKf2gWS-4&list=PLAl4aZK3mRv2QTsDOp1CZvDpMAYz9xBpy&index=1 >, but youtube-dl-gui considers this a playlist download and downloads all the entries of the playlist. It should only download a playlist if it is a url like < https://www.youtube.com/playlist?list=PLAl4aZK3mRv2QTsDOp1CZvDpMAYz9xBpy >.

Original issue: https://github.com/youtube-dlg/youtube-dl-gui/issues/10

**Comment by MrS0m30n3** [comment]
Closing, since *youtube-dl-gui* uses the default behaviour of *youtube-dl*.

If you don't want to download the entire playlist, you can:
* Select only the video URL (without the **&list=*** part)
* Add `--no-playlist` under Options>Extra tab
* Change the default behaviour of youtube-dl

**Comment by chrisgraham** [comment]
I tried to bring this up with youtube-dl, but they won't change the default behavior (https://github.com/ytdl-org/youtube-dl/issues/22016).

I think any normal user would expect things to work simply without extra configuration for URLs copied out of their watch later. So I'd ask you to reconsider this.

**Comment by liamengland1** [comment]
Just remove the part after `&list=`...

**Comment by chrisgraham** [comment]
> Just remove the part after `&list=`...

I get it, but I want to encourage packages to be more user friendly to increase Linux adoption, and this issue is a prime example of something being unnecessary complicated and also easy to be fixed.
