### ISSUE TITLE
No uninstall option

### ISSUE THREAD

**Issue by shivdhar** [MrS0m30n3/youtube-dl-gui#135]
It didn't meet my needs, so I tried to uninstall it. Turns out there's no option to uninstall it.
Had to do this (from [this thread](http://askubuntu.com/questions/38692/how-does-one-remove-applications-installed-through-python-setup-py-install)) to uninstall the program:
```
python setup.py install --record files.txt
cat files.txt | xargs rm -rf 
```
which feels hacky at best.

Please add a way to uninstall it, or failing that, distribute it through PiPy or something, which *does* have uninstall built in.

**Comment by MrS0m30n3** [comment]
The issue template was there for a reason, closing...
