### ISSUE TITLE
No download & settings being overwritten everytime

### ISSUE THREAD

**Issue by uahim** [MrS0m30n3/youtube-dl-gui#136]
hello,

I just managed to install youtube-dl-gui on WinXP. now I get it started, but this it won't download anything (screenshot attached below) and outputs this error in the cmd window. also, changes made to settings.json are being reset to default on startup.

> C:\gnu\youtube-dl-gui> py youtube_dl_gui
> Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "C:\gnu\Python27\lib\threading.py", line 530, in __bootstrap_inner
>     self.run()
>   File "C:\gnu\Python27\lib\site-packages\youtube_dl_gui\downloadmanager.py", line 288, in run
>     ret_code = self._downloader.download(self._data['url'], options)
>   File "C:\gnu\Python27\lib\site-packages\youtube_dl_gui\downloaders.py", line 162, in download
>     self._create_process(cmd)
>   File "C:\gnu\Python27\lib\site-packages\youtube_dl_gui\downloaders.py", line 322, in _create_process
>     info.dwFlags |= subprocess.STARTF_USESHOWWINDOW
> AttributeError: 'module' object has no attribute 'STARTF_USESHOWWINDOW'

![ytdl](https://cloud.githubusercontent.com/assets/6866794/19057503/9c0d966e-89d0-11e6-967f-ef2433f0eb9d.png)

ideas?

**Comment by uahim** [comment]
@MrS0m30n3 care to explain what exactly is "invalid"?

**Comment by MrS0m30n3** [comment]
The template was there for a reason, it says:
>### WARNING
All the invalid issues will be rejected!!

I can't guess if you use the latest version, what service pack you use, what OS you are on etc etc...
If you want to open an issue do it properly (no offense but i don't have to spend my time when someone can't report his-her problem).
