### ISSUE TITLE
AttributeError - 'STARTF_USESHOWWINDOW'

### ISSUE THREAD

**Issue by uahim** [MrS0m30n3/youtube-dl-gui#137]
- [x] **I assure** that my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **I assure** that I'm running youtube-dl-gui **0.3.8**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker

---

### What is the purpose of your *issue*?
- [x] Bug during the download process (encountered problems after hitting the *Download* button)

---

#### Provide the full verbose output as follows:

1. Add `-v` flag to Options > Commands tab
2. Re-try to download the URL
3. Go to `Options > Log` tab and click the `View Log` button
4. Copy the **whole** content of the log file and insert it between the triple ``` part

```
the log is empty
```

---

Please remove the following section between the (---) if your problem does not belong to **the first two categories (bug report)**

#### What operating system do you use ?
Win XP SP3

#### List of actions to perform to reproduce the problem:
  1. py C:\gnu\Python27\lib\site-packages\youtube_dl_gui
  2. URL http://www.youtube.com/watch?v=H22t-tiWiLw
  3. clicking DOWNLOAD
  4. nothing happens
  
#### What is the expected behaviour ?
the video should be downloaded

#### What happens instead ?
nothing, as seen in the screenshot below
![clipboard01](https://cloud.githubusercontent.com/assets/6866794/19082533/df5f27dc-8a5e-11e6-8e39-fd5accfb4afd.png)

---

### Description of your *issue*, suggested solution and other information. Please make sure the description is worded well enough to be understood.

it won't download anything and outputs this error in the cmd window. also, changes made to settings.json are being reset to default on startup.

> Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "C:\gnu\Python27\lib\threading.py", line 530, in __bootstrap_inner
>     self.run()
>   File "C:\gnu\Python27\lib\site-packages\youtube_dl_gui\downloadmanager.py", line 288, in run
>     ret_code = self._downloader.download(self._data['url'], options)
>   File "C:\gnu\Python27\lib\site-packages\youtube_dl_gui\downloaders.py", line 162, in download
>     self._create_process(cmd)
>   File "C:\gnu\Python27\lib\site-packages\youtube_dl_gui\downloaders.py", line 322, in _create_process
>     info.dwFlags |= subprocess.STARTF_USESHOWWINDOW
> AttributeError: 'module' object has no attribute 'STARTF_USESHOWWINDOW'

**Comment by MrS0m30n3** [comment]
What python version do you use ?

Also, i guess you installed *youtube_dl_gui* from the source using: `python setup.py install`? 
Why not use the Windows installer ?

The STARTF_USESHOWWINDOW attribute should be available.

One of the following is happening:
* You use an outdated Python version, probably < **2.7.3**
* For some reason Python is not installed correctly
* You have overwritten the **subprocess.py** file under C:\gnu\Python27\Lib

You can also run those two commands on cmd and paste the output here:

`python -c "import subprocess; subprocess.STARTF_USESHOWWINDOW"`
`python -c "import subprocess; print(subprocess.__file__)"`

**Comment by MrS0m30n3** [comment]
Probably duplicate of: https://github.com/MrS0m30n3/youtube-dl-gui/pull/77

**Comment by uahim** [comment]
> What python version do you use ?

that was it, for some reason I had 2.7.0 installed. thank you.

not sure if https://github.com/MrS0m30n3/youtube-dl-gui/pull/77 covers this, but I managed to workaround the settings.json to be overwritten to default after editing it. maybe someone else will find this helpful: after editing, start youtube_dl_gui but don't go to the options dialog - just download any video and close youtube_dl_gui again. this seems to work here.

> Why not use the Windows installer ?

I didn't know there is one, on https://github.com/MrS0m30n3/youtube-dl-gui#installation it says "Windows: TODO Package MSI/portable ZIP"

**Comment by nodiscc** [comment]
@uahim Yes, I added this todo in the README in the temporary fork, and it got pulled with the rest of the changes when @MrS0m30n3 merged the fork. There _is_ a windows installer at https://github.com/MrS0m30n3/youtube-dl-gui/releases, but there are no instructions/Makefile/... to actually build the installer from the latest version. I will open another issue. Thanks for noticing.

**Comment by MrS0m30n3** [comment]
@uahim you probably had an issue with the settings because of the crash or you were passing wrong values to the settings.json (if you tried to edit it).

Currently the latest Windows build (portable) is this one: [link](https://drive.google.com/file/d/0B4LUjPpAKNa1MXdOT1BQOEFEMGs), which dates back to Feb 15, 2016
