### ISSUE TITLE
Package latest revisions for Windows/Portable app

### ISSUE THREAD

**Issue by nodiscc** [MrS0m30n3/youtube-dl-gui#138]
Followup to https://github.com/MrS0m30n3/youtube-dl-gui/issues/137:

>    Why not use the Windows installer ?
> 
> > I didn't know there is one, on https://github.com/MrS0m30n3/youtube-dl-gui#installation it says "Windows: TODO Package MSI/portable ZIP"
> > 
> > > @uahim Yes, I added this todo in the README in the temporary fork, and it got pulled with the rest of the changes when @MrS0m30n3 merged the fork. There is a windows installer at https://github.com/MrS0m30n3/youtube-dl-gui/releases, but there are no instructions/Makefile/... to actually build the installer from the latest version. I will open another issue. Thanks for noticing.

I have zero experience with packaging MSIs. @MrS0m30n3 what did you use to package 0.3.8 for WIndows?

**Comment by MrS0m30n3** [comment]
It's a secret :gun: 
* **py2exe** to build the executables
  * [Inno Setup](http://www.jrsoftware.org/isinfo.php) to create the Windows installer
  * Zip the files (built by py2exe) to create the portable version

I guess i could write a *how_to* and add my build script for Inno
Leave this issue open as a reminder

**Comment by CodePunk-** [comment]
Please do or would you mind uploading your portable version. 
Pretty useful and easy to use tool, thanks for keeping it alive.

**Comment by linglung** [comment]
I have also same confusing about this. Please upload the portable version.

**Comment by student13371** [comment]
It would be so great if all the changes and commits were compiled into a new Windows portable release version 0.3.**9**

**Comment by MrS0m30n3** [comment]
I just uploaded a portable build for the **new_layout** branch (commit b791ac805f925c88dbcd0b5a06ec0d2b9c1d6de1)
You can find the build [here](https://drive.google.com/open?id=0B4LUjPpAKNa1SkVJYVhnak1JMTA)

**Comment by CodePunk-** [comment]
The new GUI looks awesome, many thanks!

**Comment by MrS0m30n3** [comment]
@CodePunk- 

Open a new issue (don't fill any of the details asked just remove everything) and do the following:
1. Open youtube-dl-gui and go to Options > Extra tab
2. Enable **Debug youtube-dl**
3. Go to Options > Advanced tab and **Clear** your log file
3. Try to download the URL
4. Paste the content of your log file between triple back quotes like this: \`\`\`log content here\`\`\`

**Comment by nodiscc** [comment]
I'd be interested in checking out the build script (even in an incomplete form, mid-way between a howto and a fully automated build script). I could help with improving full automation of the build process, but since I have zero experience with Inno Setup, seeing a rough draft of how it works would probably help.

**Comment by nodiscc** [comment]
I don't use this software anymore and it's been unmaintained since 2018, therefore I'm closing this issue. I can recommend https://github.com/axcore/tartube as a good alternative.
