### ISSUE TITLE
Options window changes

### ISSUE THREAD

**Issue by MrS0m30n3** [MrS0m30n3/youtube-dl-gui#139]
@philipzae @nodiscc 

Currently we have the changes listed [here](https://docs.google.com/document/d/1UJ55sYepfk5Dl0nCJNz9fXRBgpG32v-4RwIqSdkXXVg/edit#heading=h.x339dzbalqij) by **philipzae**

Feel free to supply an image with your suggestions.

**Comment by philipzae** [comment]
Mockups for the organization i mentioned in the google doc.

![image48](https://cloud.githubusercontent.com/assets/4412114/19288579/bdadc594-9017-11e6-91ab-70bd437de216.png)

![image53](https://cloud.githubusercontent.com/assets/4412114/19289897/fff8add2-901d-11e6-8433-3ac1a6a3459d.png)

**Comment by MrS0m30n3** [comment]
Everything looks fine but, i have some questions:
* What about the **mix video format** from the *Video* tab?
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;There are lot of closed issues from users who want this functionality

* What about the **playlist** & **filesize** options?
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I believe that they are usefull, should we remove them or maybe add a new tab or fit them in an existing one?

**Comment by philipzae** [comment]
> What about the mix video format from the Video tab?

Yes the two mix video format drop downs lists should be available under the video format grid with an add button, which would add it to the list.

> What about the playlist & filesize options?

Playlist is intended to be part of the main window, where when a playlist url is detected, a new dialog opens and populates a grid for the user to select which playlist entries they want to download. If filesize options are needed to be retained, then they can go on the download tab

> What is the use case of the Extract audio from video option?

Extract audio is the `-x` argument and keep original video is the `-k`. I personally like downloading a video and also having the audio extracted from it and be able to keep both.

I guess one of the things that is still missing from the mockup is the 'commands box' entry, which should be put on the advanced tab. Would be good to also put the contents of youtube-dl's default config file (~/.config/youtube-dl/config) as well, as that affects all downloads. I have `--no-mtime` set in it and we should default to have that in the 'commands box' as well.

If you prefer to go with vertical tabs like the Qt options dialog, things could be broken down into smaller sections, though it could be with the horizontal tabs as well.

Forgot to include a note in the mockup about the '...' button next to the custom file name format textbox. Basically it opens a menu of options and clicking one of them with append the file name template code for the entry into the custom file name textbox in this format ' - %(field)'. You can see this functionality at work in the QMMP audio app's options dialog.

**Comment by MrS0m30n3** [comment]
>>What is the use case of the Extract audio from video option?

>Extract audio is the -x argument and keep original video is the -k. I personally like downloading a video and also having the audio extracted from it and be able to keep both.

Selecting **Extract audio from video** option isn't the same as selecting *mp3*, *wav*, etc.. from the drop down list on the main window?

**Comment by philipzae** [comment]
> Selecting Extract audio from video option isn't the same as selecting mp3, wav, etc.. from the drop down list on the main window?

Selecting mp3 or wav from the drop down would download the audio file (e.g. m4a) and then covert it to the other format.

**Comment by nodiscc** [comment]
> Selecting mp3 or wav from the drop down would download the audio file (e.g. m4a) and then covert it to the other format.

Unless the service directly provides mp3 or wav, in which case it will simply be downloaded and no conversion will happen (which is quite rare).

**Comment by MrS0m30n3** [comment]
So, if you select mp3, wav, etc you download the video and then convert it to the other format and if you set the **Extract audio from video** option you extract the original audio from the video file without converting it, right?

If that's the case then again why do we need the **Extract audio from video** option we could add it on the *Audio Formats* as "default", "original" or something else as suggested here https://github.com/MrS0m30n3/youtube-dl-gui/issues/125 instead of having an extra option.

Again to see if i understand correctly:  
* Selecting *mp3*, *wav*, etc = `youtube-dl -x --audio-format mp3 <url>`
* Selecting the *Extract audio from video* = `youtube-dl -x <url>`

**Comment by philipzae** [comment]
Nope this is how it is
- Selecting mp3 = `youtube-dl -f bestaudio --audio-format mp3 <url>` (No need to download a video stream if the user only wants an mp3.)
- Extract audio from video = `youtube-dl -x <url>` (User wants the audio stream from a video without any conversion)

**Comment by MrS0m30n3** [comment]
I just pushed the changes on the new_layout branch it's not 100% done.
Check it out and post your feedback here.

Known issues:
* Currently there is no support for the *mix_video_formats*
* No *Extract audio from video file* option yet
* Custom output formats, no button to add templates
* No tray icon options, since there is no tray icon support currently
* No simultaneous downloads option (i won't add it since the user can easily change this from the settings.json, i also plan to change the sim. downloads to 1 by default and add a how to in FAQs on how to change it)
* No useragent dropdown since i can't provide a big enough number of hardcoded useragents
* Some things might not work (like formats selection), but i am going to fix those in the next days
* I will re-adjust the layout when i'm done with the basic functionality (you can post images to help me out)

**Comment by MrS0m30n3** [comment]
Pushed more code. Now most of the stuff should work.

Note that there is a new dependency, run: `pip install twodict`

**Comment by philipzae** [comment]
Looks good. Here is some feedback.

**Main Dialog**
- Add separator between audio and video formats

**Options Dialog General**
- Would be good set an exact size for the dialog, or atleast its width.

**General tab**
- 'Shutdown' label to 'Shutdown on download completion'
- Is the shutdown password field required, as when i shutdown from any desktop environment, it doesnt ask for a password. It would be good to invoke the DE's shutdown mechanism, so a user can click cancel at the prompt. If the field is necessary, the please add a 'User Password' label before it underneath the shutdown checkbox and have the field aligned to the label and not right aligned to the dialog
- Append ' (Not recommended for non-english titled videos)' to the 'Remove non-ASCII characters' checkbox label

**Comment by MrS0m30n3** [comment]
>Add separator between audio and video formats

I also wanted to add one, but there is no built-in widget that supports separators. I might have to create a custom widget for this, if it is even possible.

>Would be good set an exact size for the dialog, or atleast its width

I am going to set a minimum size for the frame.

>'Shutdown' label to 'Shutdown on download completion'

:+1: 

>Is the shutdown password field required...

The only other way that i know is using the [d-bus](https://en.wikipedia.org/wiki/D-Bus), which is more complicated. I am going to do some research. If you know any other way to programmatically shutdown the system without having to run SUDO you can post it here or provide a link.

>Append ' (Not recommended for non-english titled videos)' to the 'Remove non-ASCII characters' checkbox label

If the video title is in english there is no reason to check this option since all english characters are ASCII. What i want to say basically is that most users use this option for non-english characters which is the opposite of what you suggest.

**Comment by philipzae** [comment]
> The only other way that i know is using the d-bus, which is more complicated. I am going to do some research. If you know any other way to programmatically shutdown the system without having to run SUDO you can post it here or provide a link.

Not sure how to do it, but qbittorrent and uget have the options and they are open source apps, so it should be possible to dig through their code to see how they are doing it. they also have options for suspend and hibernate.

> What i want to say basically is that most users use this option for non-english characters which is the opposite of what you suggest.

So you are saying that the majority of users who enable this option, are doing so for video titles that are not in english? If so, then what is the point of it, as i tested an non-english youtube video title and it showed up blank with the option enabled.

**Comment by MrS0m30n3** [comment]
Pushed more code:
* Added a custom combobox widget for video formats. Now i can add padding to the formats in order to distinguish them.
* Added the custom format template button under Options>General tab.
* Changed the shutdown checkbox label.

About the shutdown, i checked the source code for both qbittorrent and uget and they both use d-bus to shutdown the system ([uget](https://sourceforge.net/p/urlget/uget/ci/master/tree/uglib/UgUtils.c#l529), [qbittorrent](https://github.com/qbittorrent/qBittorrent/blob/3ea81be2ccf863f21733b08f23dc2280b2bf98ed/src/base/utils/misc.cpp#L98)). I added it in the TODO file, but its not high on my priorities.

**Comment by MrS0m30n3** [comment]
Tasks remaining for optionsframe completion:

* Add *mix video formats* option (not sure how to fit in the ui)
* Add *extract audio from video file* option
* Add labels back to gettext
* Adjust layout
  * Set frames minimum size
  * Adjust the spaces between widgets

I hope i don't forget anything.

**Comment by MrS0m30n3** [comment]
I just added the *extract audio from video file* option. Now selecting:

1. **mp3** = `youtube-dl -x --audio-format mp3 <url>`
2. **extract audio from video** = `youtube-dl [-f format] -x <url>`
3. Selecting **extract audio from video** with an **audio format** has no effect

This behaviour also covers issue https://github.com/MrS0m30n3/youtube-dl-gui/issues/125. (See 2.)

Also, @philipzae in a previous post you said:
> * Selecting mp3 = youtube-dl -f bestaudio --audio-format mp3 <url> (No need to download a video stream if the user only wants an mp3.)

(I believe you forgot the `-x` flag, since the `--audio-format` flag has no effect without it)

If you check the [youtube-dl source code](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/__init__.py#L212) you can see that youtube-dl automatically sets the quality to 'bestaudio/best' when there is only the `-x` flag, so there is no need to add `-f bestaudio`.

**Comment by philipzae** [comment]
@MrS0m30n3 yes you are correct about `-x`, as i thought "Convert video files to audio-only files" in help wasnt for convert audio files to a different format. :D

**Comment by MrS0m30n3** [comment]
I finished with the **options window**, this is going to be the final layout.
Give it a try and let me know if there are any issues (spaces between widgets, etc..)

**Comment by nodiscc** [comment]
After pulling the latest revision (I don't remember changing anything to my python setup), the program does not start, with the following error:

    $ python -m youtube_dl_gui 
    No module named twodict

Python versions:

```
python2.7: 2.7.12-3+b1
python3: 3.5.1-4
```

**Comment by MrS0m30n3** [comment]
@nodiscc In case you haven't seen it already i said in a previous post that there is a new dep.
Run `pip install twodict`

**Comment by nodiscc** [comment]
> pip install twodict

Sorry, my bad, it works fine (note that twodict is not packaged for debian and derivatives). Let's add it `pip install twodict` to the README?

> let me know if there are any issues

Important missing things IMHO are:
 * dynamic formats `{best/worst/bestaudio/bestvideo/worstaudio/worstvideo}` in the formats list (https://github.com/MrS0m30n3/youtube-dl-gui/issues/116)
 * generic video formats without resolution restrictions (webm,mp4,3gp,flv)
 * a preselection of sensible default formats (https://github.com/MrS0m30n3/youtube-dl-gui/issues/131)

**Comment by MrS0m30n3** [comment]
>Sorry, my bad, it works fine now (note that twodict is not packaged for debian and derivatives). Let's add it pip install twodict to the README?

I have already added it on [README](https://github.com/MrS0m30n3/youtube-dl-gui/tree/new_layout#requirements) as a requirement. I will re-format the README after i merge the new layout.

>* dynamic formats {best/worst/bestaudio/bestvideo/worstaudio/worstvideo} in the formats list (#116)

That's a separate issue.
Also, i'm not quite sure that i want to add those since i dont believe many people use the **worst** ones and best=default, bestaudio=default + *extract audio from video file*.

>* generic video formats without resolution restrictions (webm,mp4,3gp,flv)

I'm going to add them.

>* a preselection of sensible default formats (131)

I will change the default formats after closing #131.
    
So, if you have no more issues-suggestions with the **options window** layout i'm going to close this issue after adding the generic video formats (webm, mp4, etc..)

**Comment by MrS0m30n3** [comment]
I just added the generic video formats. The only thing that still remains is the *mix video formats* option.
I will probably add it on the main window under the *formats* combobox as *mix..* or something like that.

**Comment by nodiscc** [comment]
Great work, thank you.

**Comment by philipzae** [comment]
@MrS0m30n3 
Sorry for the delay. Here are some suggestions.

- Shouldnt 'Audio quality' under the Formats tab have a 'default' entry?
- 'Retries' label on the Advanced tab being right aligned seems strange. The entry seems out of place with the rest of the stuff in the tab, so maybe worth moving it over to the newly created Extra tab.
- Would be useful to link to https://github.com/rg3/youtube-dl/blob/master/README.md#options with the 'Command line arguments' label on the Extra tab

**Comment by MrS0m30n3** [comment]
>* Shouldnt 'Audio quality' under the Formats tab have a 'default' entry?

No, *mid* is the default value which is equal to youtube-dl *--audio-quality 5* (default for youtube-dl).

>* 'Retries' label on the Advanced tab being right...

I know, i tried moving it around but that's the best place i could come up with. Also, i don't see a way to move it to the Extra tab.

>* Would be useful to link to https://github.com/rg3/youtube-dl/blob/master/README.md#options with the 'Command line arguments' label on the Extra tab

I also thought about it, but i don't want to add a hyperlink since those are options for advanced users that already know about the youtube-dl commands.

>* The 'Title + Quality' and 'Title + ID + Quality' entries are missing from the file format drop down list.

Done.
* Title + Quality = %(title)s-%(height)sp.%(ext)s
* Title + ID + Quality = %(title)s-%(id)s-%(height)sp.%(ext)s

**Comment by philipzae** [comment]
> I also thought about it, but i don't want to add a hyperlink since those are options for advanced users that already know about the youtube-dl commands.

Even advanced users (meaning users who are aware of using commandline arguments, but not necessarily the ones for youtube-dl) would like an easy means to see the list of commands rather than having to open up the terminal. We could possibly add the same filename format '...' button to make some of the more common options easy to insert.

**Comment by MrS0m30n3** [comment]
With advanced users, i mean youtube-dl users that already know about the command line options.
The reason that i added the command line box in the first place was to allow **youtube-dl users** to use options currently not presented in the gui.

Anyway, i'm not going to make changes on the commands box.
