### ISSUE TITLE
MAX DOWNLOADS does not seem to limit amount of simultaneous files downloading

### ISSUE THREAD

**Issue by flamaest** [MrS0m30n3/youtube-dl-gui#140]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### WARNING
All the invalid issues will be rejected!!

---

### Before going further
* If your problem is a bug with the **youtube-dl** program or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

* Make sure you are using the *latest* **youtube-dl-gui** version: `Options > About` tab. If it's not please download & install the latest version for your OS and check if your issue still persists

* Make sure you are using the *latest* **youtube-dl** version: Click the `Update` button on the main screen and check if your issue still persists

* Make sure you searched the bugtracker for similar issues including closed ones

  - [ X] **I assure** that my problem is **NOT** with **youtube-dl**
  - [X ] I've **verified** and **I assure** that I'm running youtube-dl-gui **0.3.8**
  - [X ] **I assure** that i am using the latest version of **youtube-dl**
  - [X ] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker

---

### What is the purpose of your *issue*?
- [X ] Bug during the download process (encountered problems after hitting the *Download* button)
- [ ] Bug other (encountered other problems with *youtube-dl-gui*)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Please remove the following section between the (---) if your problem does not belong to the **bug during the download process** category

#### Provide the full verbose output as follows:

1. Add `-v` flag to Options > Commands tab
2. Re-try to download the URL
3. Go to `Options > Log` tab and click the `View Log` button
4. Copy the **whole** content of the log file and insert it between the triple ``` part

```
NO LOG ENTRY FOUND FOR THIS PROBLEM
```

---

Please remove the following section between the (---) if your problem does not belong to **the first two categories (bug report)**

#### What operating system do you use ?
  windows 7 pro

#### List of actions to perform to reproduce the problem:
  1. .. goto youtube-dl-gui 0.3.8-win 'options'
  2. .. select PLAYLIST --> set MAX DOWNLOADS to 1
  3. .. Add more than one file to download, yet both download at the same time.
  
#### What is the expected behavior ?

only one file should download using this max value = 1

#### What happens instead ?

All requested video files try to download at the same time.

---

### Description of your *issue*, suggested solution and other information. Please make sure the description is worded well enough to be understood.

verify that MAX DOWNLOADS to 1 limits downloading one file at a time.

**Comment by MrS0m30n3** [comment]
This option sets the maximum number of videos to download from a playlist.
Currently there is no option on the gui to change the simultaneous downloads.
You can read https://github.com/MrS0m30n3/youtube-dl-gui/issues/53
