### ISSUE TITLE
Logfile

### ISSUE THREAD

**Issue by norden1** [MrS0m30n3/youtube-dl-gui#141]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### WARNING
All the invalid issues will be rejected!!

---

### Before going further
* If your problem is a bug with the **youtube-dl** program or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

* Make sure you are using the *latest* **youtube-dl-gui** version: `Options > About` tab. If it's not please download & install the latest version for your OS and check if your issue still persists

* Make sure you are using the *latest* **youtube-dl** version: Click the `Update` button on the main screen and check if your issue still persists

* Make sure you searched the bugtracker for similar issues including closed ones

  - [x] **I assure** that my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **I assure** that I'm running youtube-dl-gui **0.3.8**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker

---

### What is the purpose of your *issue*?
- [ ] Bug during the download process (encountered problems after hitting the *Download* button)
- [ ] Bug other (encountered other problems with *youtube-dl-gui*)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information. Please make sure the description is worded well enough to be understood.

Why are my logfile always empty when I open it. Sometimes I get problem and need the logfile to send to the people ho can fix it on youtube dl. The checkbox enable logfiel are checked its that not enough?

**Comment by norden1** [comment]
Why are my logfile always empty when I open it. Sometimes I get problem and need the logfile to send to the people ho can fix it on youtube dl. The box enable logfiel are checked its that not enough?

**Comment by MrS0m30n3** [comment]
Hi,

By default, only the **Error** & **Warning** messages are being recorded.
If you want to log the youtube-dl **Debug** output you need to pass the `-v` option under Options>Commands.

**Comment by norden1** [comment]
Hi
Thanks for answer maybe this option can get implemented in the new gui?

**Comment by MrS0m30n3** [comment]
If you mean logging the **debug** output by default, no since this will make the logfile hard to read. If you mean adding it as an option (checkbox, etc..), yes it's already in the [TODO](https://github.com/MrS0m30n3/youtube-dl-gui/blob/new_layout/TODO#L49) list.

**Comment by norden1** [comment]
You know exactly what i mean i really like that. I look forward to the new gui are you going to release it soon maybe? i am very hopeful about that because i often use Youtube dlg its very good probably the best program a have seen. 
Thanks for good answer.

**Comment by MrS0m30n3** [comment]
I'm definitely not good with deadlines. I want to believe that the new ui will be available until the end of this year. [Those are the issues](https://github.com/MrS0m30n3/youtube-dl-gui/milestone/1) that we have to take care before merging back to *master* and making a new release.

**Comment by norden1** [comment]
Hi
I have some suggestions for the new gui i write them here.
Add Swedish language so its possible to choose Swedish language and embed into file when downloading.

An option to see which version of Youtube dl which are in use or maybe get an notification when a new version of Youtube dl are released.

Possible to download a hole tv serie with lot of episodes so you dont need to copy and paste each link.
Maybe someone else had write this i dont know.
Now i wait for the new gui and i will have patience.

**Comment by MrS0m30n3** [comment]
Your first two suggestions are already in my TODO list.
The last one seems like a youtube-dl issue. Maybe there is a way already, i guess this is relative to the youtube-dl extractor being used.

**Comment by norden1** [comment]
Hi
I dont know what you mean abot wich Youtube dl ectractor being used to download a tv serie at time.

**Comment by MrS0m30n3** [comment]
**youtube-dl** has a [list of extractors](https://github.com/rg3/youtube-dl/tree/master/youtube_dl/extractor) which are responsible for extracting informations about the requested url.

What i meant in my previous comment was that if the corresponding extractor supports series extraction, you should be able to download all the episodes from a tv serie at once, else you should add support to the corresponding extractor.

**Comment by norden1** [comment]
Were can i find information about this if i want to do that. I look on the link above you have in your comment and there are svt but i dont know how i should do to to try to download a list of episodes at once. Should i make a request to Youtube dl or what?

**Comment by MrS0m30n3** [comment]
You could try to implement it yourself. Check those for help:
* https://github.com/rg3/youtube-dl#developer-instructions
* irc channel **#youtube-dl** [webchat](http://webchat.freenode.net/?randomnick=1&channels=youtube-dl) on freenode (to talk to someone, maybe they could guide you)

Or make a new issue and ask the developers to add support (if it's possible).

**Comment by norden1** [comment]
Thanks for your time but i are not so good to make this i cant anything about programming. Maybe i make an issue and hope they can implement it.
Thanks for answer and a good program which i use very often.
