### ISSUE TITLE
[Windows 10] Unable to download anything, but can do so on other computers.

### ISSUE THREAD

**Issue by azyzzx** [MrS0m30n3/youtube-dl-gui#142]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### WARNING
All the invalid issues will be rejected!!

---

### Before going further
* If your problem is a bug with the **youtube-dl** program or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

* Make sure you are using the *latest* **youtube-dl-gui** version: `Options > About` tab. If it's not please download & install the latest version for your OS and check if your issue still persists

* Make sure you are using the *latest* **youtube-dl** version: Click the `Update` button on the main screen and check if your issue still persists

* Make sure you searched the bugtracker for similar issues including closed ones

  - [x] **I assure** that my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **I assure** that I'm running youtube-dl-gui **0.3.8**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker

---

### What is the purpose of your *issue*?
- [x] Bug during the download process (encountered problems after hitting the *Download* button)
- [ ] Bug other (encountered other problems with *youtube-dl-gui*)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Please remove the following section between the (---) if your problem does not belong to the **bug during the download process** category

#### Provide the full verbose output as follows:

1. Add `-v` flag to Options > Commands tab
2. Re-try to download the URL
3. Go to `Options > Log` tab and click the `View Log` button
4. Copy the **whole** content of the log file and insert it between the triple ``` part

```
Log viewer doesn't show anything, Even with the '-v' flag.
```

---

Please remove the following section between the (---) if your problem does not belong to **the first two categories (bug report)**

#### What operating system do you use ?

W10

#### List of actions to perform to reproduce the problem:

  1. Download and install youtube-dl-gui on a clean installation of Windows 10, Change nothing in the options.
  2. Copy-paste URL into the download box.
  2. Click 'Download'.
  3. Dialog box pops up that says 'Download completed'.
  4. Click OK.
  
#### What is the expected behaviour ?

Folder pops up showing your downloaded items. 

#### What happens instead ?

Nothing in the folder. It is empty. The files have not been downloaded at all. Also, on the left-hand bottom corner of the youtube-dl-gui program, it says 'Successfully downloaded 1 urls in 0 day(s) 0 hours 0 minutes 0 seconds'.

---

### Description of your *issue*, suggested solution and other information. Please make sure the description is worded well enough to be understood.
http://i.imgur.com/0b8wtxX.png
Picture above shows the problem. For some reason, it works another one of my computers (also Windows 10). I recently clean installed Windows 10 on the computer I'm having the problem with.
It's probably a small isolated case, but I'd like to know how to get it working.

Thanks so much!

**Comment by MrS0m30n3** [comment]
That seems like a weird issue and since there is no log output it's hard to debug.

The most obvious case is that the *youtube-dl* executable does not work properly for some reason (bad download probably).

On your issue report you checked
>I assure that i am using the latest version of youtube-dl

Did you followed the instructions?
>Click the *Update* button on the main screen and check if your issue still persists

If you did so, can you try to update *youtube-dl* (click the Update button) again and see if your issue is solved?

**Comment by azyzzx** [comment]
Hi,

Sorry to get back to you so late. Clicking update for youtube-dl-gui hasn't helped it. However, it's clearly nothing wrong on your side, and it's more than likely wrong on my end.

Thanks for the help.

**Comment by MrS0m30n3** [comment]
I'm pretty sure that for some reason the *youtube-dl* executable does not work properly.

Let's try something different:
* On your keyboard hit the *Windows* key + R (Run dialog should appear)
* Type `cmd` and hit Enter (Command line window should appear)
* Inside the cmd window type `cd %appdata%\youtube-dlg` and hit Enter
* Inside the cmd window type `youtube-dl.exe -v YOUR_URL_HERE` and hit Enter
* Finally paste the **FULL** output from the previous command here

### Note
I don't have a Windows machine, so i might have some mistakes in the above commands.

**Comment by azyzzx** [comment]
Hi again,


The error message that popped up when I executed youtube-dl.exe was "msvcr100.dll is missing". I fixed it by installing libraries for Microsoft Visual c++ 2010.

Cheers MrS0m30n3. Thanks for sticking with me, and for your supportive development of this project.
