### ISSUE TITLE
File renaming

### ISSUE THREAD

**Issue by norden1** [MrS0m30n3/youtube-dl-gui#144]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### WARNING
All the invalid issues will be rejected!!

---

### Before going further
* If your problem is a bug with the **youtube-dl** program or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

* Make sure you are using the *latest* **youtube-dl-gui** version: `Options > About` tab. If it's not please download & install the latest version for your OS and check if your issue still persists

* Make sure you are using the *latest* **youtube-dl** version: Click the `Update` button on the main screen and check if your issue still persists

* Make sure you searched the bugtracker for similar issues including closed ones

  - [x] **I assure** that my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **I assure** that I'm running youtube-dl-gui **0.3.8**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [ ] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker

---

### What is the purpose of your *issue*?
- [ ] Bug during the download process (encountered problems after hitting the *Download* button)
- [ ] Bug other (encountered other problems with *youtube-dl-gui*)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information. Please make sure the description is worded well enough to be understood.

![youtube dlg 2](https://cloud.githubusercontent.com/assets/22798405/20650532/f318676a-b4d0-11e6-9d22-3b47b58bb10c.jpg)
It is possible to get filename from url look the Arrow 1
Instead of the filename on Arrow 2 
I attach a screenshot what i mean. I have tried different setting on the output option but i dont have figured out how it works. When downloading a lot of episodes there are not so good to get title instead of the number of episodes wich are more useful when downloading many episodes.

**Comment by norden1** [comment]
![youtube dlg 2](https://cloud.githubusercontent.com/assets/22798405/20650532/f318676a-b4d0-11e6-9d22-3b47b58bb10c.jpg)
It is possible to get filename from url look the Arrow 1
Instead of the filename on Arrow 2 
I attach a screenshot what i mean.

**Comment by MrS0m30n3** [comment]
You can change the output option under Options>Output tab.
1. Enable *Custom Template*
2. Remove what's inside the textbox
3. Add your own template

You can try one of the following or create your own:
* `%(title)s - %(episode_number)s-%(season_number)s.%(ext)s`
Output example: **videotitle - 1-2.mp4**

* `%(series)s\%(season_number)s\%(title)s ep-%(episode_number)s.%(ext)s`
Output example: **seriesname/1/videotitle ep-2.mp4**

For a template list check [here](https://github.com/rg3/youtube-dl/blob/master/README.md#output-template) and don't forget the **.%(ext)s** part.

**Comment by norden1** [comment]
Thanks for answer.
 I will try the options you wrote. Maybe there are going to be easier in the new version if possible.

**Comment by nodiscc** [comment]
>  Does the different options depends on how the file are stored on server too?

The naming options/patterns work everywhere, from any server. Please [read](https://github.com/rg3/youtube-dl/blob/master/README.md#output-template) the documentation to know more. For example a corner case would be

> Note that some of the sequences are not guaranteed to be present since they depend on the metadata obtained by a particular extractor. Such sequences will be replaced with NA.

> Maybe there are going to be easier in the new version if possible.

There are so much possible combinations/custom patterns that it is not possible to provide them all in a simple list. For rare requests like yours it is required to read the documentation and write your own pattern.

**Comment by norden1** [comment]
I have tried with some options and there be NA as you wrote. I am not a data programmer at all so its not so easy to understand all the options. I know that Youtube dl are such a expertprogram to use. But i use it in Youtube dlg wich is much easier because i dont need to understand all options. 
If i paste a link maybe you can see if there are possible to get other filename or maybe its not possible because the metadata you wrote. 
Thanks for help and answer.
http://www.oppetarkiv.se/video/3747345/rederiet-sasong-1-avsnitt-3-av-318.

**Comment by nodiscc** [comment]
Unfortunately 

> ERROR: This video is only available in Sweden.

I believe you want to have a filename like `rederiet-sasong-2-avsnitt-25-av-318.mp4`? I don't know if this is possible at all. The [SVT/Oppet Arkiv extractor](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/svt.py#L124) is only able to extract the following information: `'url', 'md5', 'id', 'ext', 'title', 'duration'` 

 I would experiment with every option available in https://github.com/rg3/youtube-dl/blob/master/README.md#output-template (Try with `%(id)s.%(ext)s ??). It's not necessary to have programming knowledge for this, you just have to try, and see. You can also ask on youtube-dl's issue tracker.

Not a youtube-dl-gui issue, so I'm closing it. Let us know if you have more info.
