### ISSUE TITLE
New website layout

### ISSUE THREAD

**Issue by MrS0m30n3** [MrS0m30n3/youtube-dl-gui#146]
I wrote the [new site](http://mrs0m30n3.github.io/youtube-dl-gui/) from scratch and since i don't have good knowledge of CSS (i hate CSS) i would love if someone with knowledge in CSS - HTML could help me:

* Center the [f(*@#& header](https://github.com/MrS0m30n3/youtube-dl-gui/blob/gh-pages/index.html#L28) vertically
* Test the site in different resolutions if she-he has a big enough screen
* Improve the layout - css code in whatever way she-he thinks is best

### Note
In case you don't know the website code is stored under the [gh-pages](https://github.com/MrS0m30n3/youtube-dl-gui/tree/gh-pages) branch.

**Comment by th0rgall** [comment]
Not an expert either, but I got that f(*@#& header centered :), see #148.
The site already looks pretty good to me, but I might check back later when I have time.

**Comment by nodiscc** [comment]
@MrS0m30n3 I just wanted to let you know that the website looks fine to me. I don't see a problem with the current header alignment either. Nice work

**Comment by th0rgall** [comment]
@nodiscc It's a detail, but on a portrait viewport (smartphones...) the header was aligned unevenly to the top. You'll see when you resize a browser window / use responsive design mode. I guess that's what @MrS0m30n3 meant.

**Comment by kj77** [comment]
@th0rgall @th0rgall Do you guys like that blue background? It looks like a BSOD to me :P

**Comment by nodiscc** [comment]
>  It looks like a BSOD to me :P 

It was a bit surprising at first, but yeah I like it :)

**Comment by th0rgall** [comment]
@kj77 True, it's very contrasty and could be something else, but it doesn't really bother me.

Is there any use to my pull request ( #148 ) ? It should be vertically centered on every viewport there.

**Comment by MrS0m30n3** [comment]
Thanks for centering the f(*@#& header @th0rgall, good job, at the end of the day it was easier than i thought.

>Do you guys like that blue background? It looks like a BSOD to me :P

@kj77 You say it like BSOD is a bad thing :package: 

Anywayzzzz feel free to provide more pull requests and ideas in order to improve the site, closing.

**Comment by nodiscc** [comment]
@MrS0m30n3 You can now update the website URL displayed at the top of https://github.com/MrS0m30n3/youtube-dl-gui (description / website fields)
