### ISSUE TITLE
Playlist download stopping and limit on playlist start of 999

### ISSUE THREAD

**Issue by CigarBoB** [MrS0m30n3/youtube-dl-gui#149]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### WARNING
All the invalid issues will be rejected!!

---

### Before going further
* If your problem is a bug with the **youtube-dl** program or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

* Make sure you are using the *latest* **youtube-dl-gui** version: `Options > About` tab. If it's not please download & install the latest version for your OS and check if your issue still persists

* Make sure you are using the *latest* **youtube-dl** version: Click the `Update` button on the main screen and check if your issue still persists

* Make sure you searched the bugtracker for similar issues including closed ones

  - [x] **I assure** that my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **I assure** that I'm running youtube-dl-gui **0.3.8**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker

---

### What is the purpose of your *issue*?
- [x] Bug during the download process (encountered problems after hitting the *Download* button)
- [ ] Bug other (encountered other problems with *youtube-dl-gui*)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Please remove the following section between the (---) if your problem does not belong to the **bug during the download process** category

#### Provide the full verbose output as follows:

1. Add `-v` flag to Options > Commands tab
2. Re-try to download the URL
3. Go to `Options > Log` tab and click the `View Log` button
4. Copy the **whole** content of the log file and insert it between the triple ``` part

```
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
ERROR: requested format not available
ERROR: requested format not available
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: unable to extract uploader nickname
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
ERROR: requested format not available
ERROR: requested format not available
ERROR: requested format not available
ERROR: requested format not available
ERROR: requested format not available
ERROR: requested format not available
ERROR: requested format not available
ERROR: requested format not available
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
ERROR: requested format not available
ERROR: requested format not available
ERROR: requested format not available
ERROR: requested format not available
ERROR: requested format not available
ERROR: requested format not available
ERROR: requested format not available
ERROR: requested format not available
ERROR: requested format not available
ERROR: requested format not available
ERROR: requested format not available
ERROR: requested format not available
ERROR: requested format not available
WARNING: unable to extract uploader nicERROR: requested format not available
ERROR: requested format not available
ERROR: requested format not available
ERROR: requested format not available
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
ERROR: Unable to extract sources; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Falling back on generic information extractor.
WARNING: Falling back on generic information extractor.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: unable to extract uploader nickname
ERROR: Error in output template: unsupported format character 'V' (0x56) at index 30 (encoding: 'cp1252')
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
ERROR: unable to rename file: [WinError 183] Cannot create a file when that file already exists: 'F:\\[YouTube Video Downloads]\\egolei lei\\ \u30002017_1_8.f135.mp4.part-Frag235.part' -> 'F:\\[YouTube Video Downloads]\\egolei lei\\ \u30002017_1_8.f135.mp4.part-Frag235'
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
Usage: youtube-dl.exe [OPTIONS] URL [URL...]
[debug] System config: []
[debug] User config: []
[debug] System config: []
```

---

Please remove the following section between the (---) if your problem does not belong to **the first two categories (bug report)**

#### What operating system do you use ?
Windows 10
#### List of actions to perform to reproduce the problem:
  1. Download a large play list from Youtube.com. The list i'm trying to grab has 2600+ videos. (https://www.youtube.com/playlist?list=UU1X5fwXl8zUSR-E9igZ5jfQ)

#### What is the expected behaviour ?
I would expect for YouTube-DLG to run through the playlist and grab each file going down the line.

#### What happens instead ?
The program downloads 70-170 videos and stalls out. If i stop and start it it will Pre Process them till it hit the same number as before. 

Here is an image of what it looks like. http://i.imgur.com/t8WtLbU.png

I have found a workaround though. I began increasing the start number for the playlist each time it would stall out, -2 videos to cover overlap. It would then start up again and go for a while till it stalled out.

I wouldn't even be submitting this ticket if I didn't run into the issue of a 999 limit for the start number of a playlist. 

I opened up the .json file and manually edited the starting number. When I started Youtube-DLG it was reduced back to 999 each time.

---

I'm not sure what you can do about the playlist download stopping. But it seems that raising the limit for a playlist start number would be fairly easy.

**Comment by MrS0m30n3** [comment]
The playlist limit on the new UI is now 9999, but a new release is not yet available.

Regarding the issue with the playlist, is that the whole log content?
It seems that the **youtube-dl** debug output is truncated and also, that *usage* message in the log file seems pretty weird.

**Comment by CigarBoB** [comment]
That is the whole log. When the program gets stuck in pre processing it never errors out. It just stalls. I have started to use --datebefore/--dateafter so that I can continue my hording. The same issue still happens with the downloads just stalling after 60-170 completed files. 

For me, as long as I can change the start number to over 999 I can deal with this issue.

**Comment by MrS0m30n3** [comment]
Can you do the following?

1. Go to *Options > Log* tab and clear the log file
2. Go to *Options > Commands* and add this: `--skip-download`
  (You should now have the **-v** and **--skip-download** flags under the commands field)
3. Try to re-download the playlist URL and let it finish
4. Go to *Options > Log* tab, click view log and paste the log content here

**Comment by MrS0m30n3** [comment]
Taking a quick guess here, but you can also try this build: [latest portable](https://drive.google.com/file/d/0B4LUjPpAKNa1MXdOT1BQOEFEMGs) (Feb 15 2016). Just remember to clear the **-v** and **--skip-download** flags under the *commands* field before trying to download your playlist. If this build works then it's an known issue which is already fixed.

**Comment by CigarBoB** [comment]
I'm currently working on trying to recreate the error. I have two instances of youtube-dlg running on two different playlists. The same issue has been present on every playlist that was large enough.

I will report back as soon as the error repeats.

**Comment by MrS0m30n3** [comment]
95% sure that it's the same issue with https://github.com/MrS0m30n3/youtube-dl-gui/issues/49, which makes sense due to the large playlist size.

>...the subprocess module was deadlocking due to the large amount of ffmpeg output in the stderr pipe which had as a result to freeze the download process...

Also, it's not a coincidence that your issue is **149** and the old one is **49**, that's a sign!!! :P

**Comment by CigarBoB** [comment]
Lol 149 & 49. Nice.

I started a new playlist of 415 videos to test the settings. Adding the --skip-download seems to be just running through all the videos on pre processing without actually downloading anything.

Also, after adding the --skip-download I was forced to use login credentials for youtube. This was an issue at first because there isn't any way to input a verification code into YTDLG from a txt msg. I just ended up using one of my dummy gmail accounts to continue.

**Comment by MrS0m30n3** [comment]
Just download the portable version mentioned above and everything should work fine.

**Comment by CigarBoB** [comment]
already downloaded it. I will give it a try.

**Comment by CigarBoB** [comment]
I just wanted to do say thank you for helping me out. It is awesome of you to have created this fork and to actually be supporting it.

**Comment by MrS0m30n3** [comment]
The *latest portable* worked fine, right? If so, please close this issue.

Unfortunately, the latest installer build points to an outdated version which has a lot of bugs.
Hope i will be able to release *0.3.9* by the end of this month.

**Comment by CigarBoB** [comment]
I was waiting till tonight to report back.

I have downloaded a ton of content on long playlists and didn't have a single issue.

Thank you again for all your help.
