### ISSUE TITLE
Suggestion: Have a "thin-client" style GUI that requires youtube-dl cmdline

### ISSUE THREAD

**Issue by thenoncoder** [MrS0m30n3/youtube-dl-gui#152]
That way, when youtube-dl has a bug or error, we can just replace it with the newer/fixed version and you don't have to modify your code unless you really need to.

This could be a different version and you could still keep the normal youtube-dl-gui in development.

**Comment by MrS0m30n3** [comment]
Youtube-dlg already uses a "thin-client" architecture by using the *youtube-dl* binary directly instead of using the youtube-dl Python library.
