### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by norden1** [MrS0m30n3/youtube-dl-gui#155]
### What is the purpose of your *issue*?

Question.

--------------------

I wonder when the new release of Youtube dlgui are coming?

**Comment by norden1** [comment]
I wonder when the new release of Youtube dlgui are coming?

**Comment by MrS0m30n3** [comment]
I don't have a release schedule, the next version will be available when it's ready.
If you are on Windows you can download the new GUI from [here](https://drive.google.com/open?id=0B4LUjPpAKNa1SkVJYVhnak1JMTA) and test it out.

**Comment by norden1** [comment]
Hi
I have dowbload and tested the new gui. It looks great but I have some questions.

 Where can I find the option to change max simultanous downloads?
On format option there are some box checked and some not checked and the sound are on mid. Does the program automatically choose the original option from site or do I need to check the box keep original size.

**Comment by MrS0m30n3** [comment]
There is no option to change the simultanous downloads, but you can read issue https://github.com/MrS0m30n3/youtube-dl-gui/issues/20.
As for the second question i don't exactly get what you mean, there is no option "keep original size".

**Comment by nodiscc** [comment]
>  Does the program automatically choose the original option from site or do I need to check the box keep original size.

The program defaults to the `best` available format.

**Comment by norden1** [comment]
Sorry I mean "keep original files" and I mean if the program automatic choose for example mp4 and mp3 if its stored like that on server I download from. I also don't need to think about to choose between example np4, mkv or flv. When post processes are going I wonder what the program do. Does it set the extension or what. 

Its there not a max download maybe there can be unlimited max download without option to change. 
The new gui looks better.  and the version I use it is stable?
I also have another question. 
Its there necessary to update the ffmpeg sometimes or its is update when update youtube dl.
Thanks for good program.

**Comment by MrS0m30n3** [comment]
Those are a lot of questions.

* The program downloads the requested format if it's available on the host site. If not, then it reports an error.

* On the post process phase a lot of things happen, like *audio extraction*, *file merge*, *metadata*, etc...

* Having unlimited parallel downloads it's not a good idea due to performance issues.

* The version you use it's **NOT** stable, it's a pre-release i made available as requested on issue https://github.com/MrS0m30n3/youtube-dl-gui/issues/138.

* The update process does **NOT** update ffmpeg. You can update it manually by copying the new ffmpeg files to the youtube-dlg directory, but i don't see the point.

**Comment by norden1** [comment]
Thanks for answer and your time. And I look forward to the new release when its coming.

**Comment by norden1** [comment]
Hi
I test the new gui on link you post . When i try to download from these two links i get warning message but the file are downloaded succesfully. But in the old program it works perfect without warning message. 
I Think you should know that and i know that release on new gui are not stable yet.
https://www.oppetarkiv.se/video/9477798/bullen
https://www.oppetarkiv.se/video/2754615/sexton-avsnitt-2-av-16

**Comment by MrS0m30n3** [comment]
Can you post the *warning* messages you get?

**Comment by norden1** [comment]
I download files again and copy this info from logfile hope it can help you.

03/08/17 07:08:46] WARNING: el subtitles not available for 1369741-002OA
[03/08/17 07:11:49] WARNING: 1355870-074OA: malformated aac bitstream. Install ffmpeg or avconv to fix this automatically.
[03/08/17 07:13:01] WARNING: el subtitles not available for 1369741-002OA
[03/08/17 07:13:01] WARNING: 1369741-002OA: malformated aac bitstream. Install ffmpeg or avconv to fix this automatically.

**Comment by MrS0m30n3** [comment]
I removed the duplicates from your log.

The first log entry means that *youtube-dl* could not locate Greek subtitles for the video, which is not normal if they don't exist. The second log entry is probably related to issue #151.

**Comment by norden1** [comment]
I don't choose any subtitles to download. Do you mean that you have fixed the problem now?

**Comment by MrS0m30n3** [comment]
Regarding the subtitles issue maybe you have some of the subtitles option enabled, you should double check your options.

As for #151, no it's not fixed yet. I wil let you know when it's fixed to check if you still get the same *warning* messages.

**Comment by norden1** [comment]
It works fine without warning messages in the old gui. And I doesn't choose any subtitle to download I am sure.
Does it works for you to download without warning messages?

**Comment by MrS0m30n3** [comment]
@norden1 

Can you try [this](https://drive.google.com/file/d/0B4LUjPpAKNa1M2FKMmZOTnJxM1U/view) version and let me know if you still get those warning messages? Also, don't forget to clear your log file before downloading a URL (Options>Advanced tab).

**Comment by norden1** [comment]
@MrS0m30n3 
Now i have download and test again. The two links above whic i use Before works fine without warning messages. I also download a lot other programs from svt and öppet arkiv and it works fine. But why the size which are shown in program when ts finished are so Little. Look in screenshot i post thoose tre files are more than a 1 gb each. but in old proh´gram it shows the correct size when finished. I post the links too
![dlg](https://cloud.githubusercontent.com/assets/22798405/24163025/a1108d4c-0e69-11e7-8648-55199ae61e7f.jpg)

http://www.svtplay.se/video/12885148/skavlan/skavlan-sasong-17-avsnitt-10
http://www.svtplay.se/video/12033210/skavlan/skavlan-sasong-17-avsnitt-2
http://www.svtplay.se/video/12669936/skavlan/skavlan-sasong-17-avsnitt-8

**Comment by norden1** [comment]
I dont have noticed that Before but when i test in old program so it seems that sometimes the correct size are shown and sometimes not. Maybe its  random .

**Comment by nodiscc** [comment]
@norden1 Can you reproduce this with the command line [youtube-dl](https://github.com/rg3/youtube-dl) tool?

Also **please** report separate issues in **separate** bug reports. This issue is about upcoming release dates. I will move your questions to another issue.

**Comment by nodiscc** [comment]
Moved to https://github.com/MrS0m30n3/youtube-dl-gui/issues/163 https://github.com/MrS0m30n3/youtube-dl-gui/issues/162
