### ISSUE TITLE
Option to set file timestamp to download date rather than server/published date

### ISSUE THREAD

**Issue by answerquest** [MrS0m30n3/youtube-dl-gui#158]
### Before going further

  - [x] **I assure** that my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **I assure** that I'm running youtube-dl-gui **0.3.8**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker

---

### What is the purpose of your *issue*?
- [ ] Bug during the download process (encountered problems after hitting the *Download* button)
- [ ] Bug other (encountered other problems with *youtube-dl-gui*)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information. Please make sure the description is worded well enough to be understood.

In both windows and linux version, after downloading, the timestamp of the file (last modified time is the most commonly used parameter) is set as the publishing date or the video's original timestamp on server. That causes a problem of hiding away recent downloads down the pile if their publish date was not recent. In windows I can at least set the folder's sorting to file creation time, which then brings the files up. But in my lubuntu pcmanfm file manager i have no choice. As a user this causes me trouble especially if I have multiple videos to download - I have to keep on changing the download path to  a new folder just make sure I don't lose latest videos.

I can also understand there would be valid use cases where the user would want the file timestamp to be same as the publish date. But can we not have both options since this is a GUI? I suggest adding this option (set timestamp to download time instead of server time) under the "Filesystem" tab in the options window. Alternatively, please advise what to put in command line arguments to make this happen.

**Comment by nodiscc** [comment]
> please advise what to put in command line arguments to make this happen.

The option you're looking for is

```
--no-mtime
              Do not use the Last-modified header to set the file modification time
```

**Comment by MrS0m30n3** [comment]
As nodiscc said you can add the `--no-mtime` flag under the Options>Commands tab.
Also, if you use the new GUI this option is available under Options>Extra tab ("No mtime").

**Comment by answerquest** [comment]
awesome, thanks! I'm using this on lubuntu / ubuntu .. any hint on how to get the new GUI? Or I can wait till the feature comes in the main repo etc.

**Comment by MrS0m30n3** [comment]
You can test the new GUI by running the following commands in a terminal window:
```
git clone https://github.com/MrS0m30n3/youtube-dl-gui/ -b new_layout
cd youtube-dl-gui
python -m youtube_dl_gui
```

Note that the **new_layout** branch is not stable, if you find any bugs please let us know.
