### ISSUE TITLE
HowTO on windows

### ISSUE THREAD

**Issue by CheweyZ** [MrS0m30n3/youtube-dl-gui#159]
Update readme to say how to do setup on windows or make the exe to run

### Before going further
* If your problem is a bug with the **youtube-dl** program or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

* Make sure you are using the *latest* **youtube-dl-gui** version: `Options > About` tab. If it's not please download & install the latest version for your OS and check if your issue still persists

* Make sure you are using the *latest* **youtube-dl** version: Click the `Update` button on the main screen and check if your issue still persists

* Make sure you searched the bugtracker for similar issues including closed ones

  - [ ] **I assure** that my problem is **NOT** with **youtube-dl**
  - [ ] I've **verified** and **I assure** that I'm running youtube-dl-gui **0.3.8**
  - [ ] **I assure** that i am using the latest version of **youtube-dl**
  - [ ] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker

---

### What is the purpose of your *issue*?
- [ ] Bug during the download process (encountered problems after hitting the *Download* button)
- [ ] Bug other (encountered other problems with *youtube-dl-gui*)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Please remove the following section between the (---) if your problem does not belong to the **bug during the download process** category

#### Provide the full verbose output as follows:

1. Add `-v` flag to Options > Commands tab
2. Re-try to download the URL
3. Go to `Options > Log` tab and click the `View Log` button
4. Copy the **whole** content of the log file and insert it between the triple ``` part

```
[delete me and insert your log content here]
```

---

Please remove the following section between the (---) if your problem does not belong to **the first two categories (bug report)**

#### List of actions to perform to reproduce the problem:
  1. ..
  2. ..
  3. ..
  
#### What happens instead ?

---

**Comment by nodiscc** [comment]
Providing updated windows executables is tracked in https://github.com/MrS0m30n3/youtube-dl-gui/issues/138
