### ISSUE TITLE
Reported downloaded filesize is incorrect

### ISSUE THREAD

**Issue by nodiscc** [MrS0m30n3/youtube-dl-gui#162]
Moved from #155 

@norden1 wrote: 

>Now i have download and test again. The two links above which i use before works fine without warning messages. I also download a lot of other programs from svt and öppet arkiv and it works fine. But why the size which are shown in program when its finished are so Little. Look in screenshot i post thoose tre files are more than a 1 gb each. but in old the program it shows the correct size when finished. I post the links too

![dlg](https://cloud.githubusercontent.com/assets/22798405/24163025/a1108d4c-0e69-11e7-8648-55199ae61e7f.jpg)

>http://www.svtplay.se/video/12885148/skavlan/skavlan-sasong-17-avsnitt-10
>http://www.svtplay.se/video/12033210/skavlan/skavlan-sasong-17-avsnitt-2
>http://www.svtplay.se/video/12669936/skavlan/skavlan-sasong-17-avsnitt-8

> I dont have noticed that Before but when i test in old program so it seems that sometimes the correct size are shown and sometimes not. Maybe its random .

**Comment by nodiscc** [comment]
@norden1 Can you reproduce this with the command line [youtube-dl](https://github.com/rg3/youtube-dl) tool?

**Comment by norden1** [comment]
@nodiscc 
I have never used Youtube-dl from command line i don't now how to use therefore i use DLG. Which I think its much easier.

**Comment by MrS0m30n3** [comment]
That's probably a bug with **youtube-dl-gui** due to commit [d6f6c7a](https://github.com/MrS0m30n3/youtube-dl-gui/commit/d6f6c7aeade9382eda2709b4f04a92bf9861c587#diff-023a91c976edfbee166c828f7188fb2dR185). I will take a closer look and let you know. Also, it would be helpful if you could paste here the *DEBUG* output of **youtube-dl**.

You can follow the steps below to do so:
1. Go to Options > Extra tab and enable the **Debug youtube-dl** option
2. Go to Options > Advanced tab and **Clear** your log file
3. Try to download a new URL 
4. When it reaches 1% stop downloading
5. Paste your log contents here between triple ```

**Comment by norden1** [comment]
Here is the log

"[03/22/17 14:57:06] [debug] System config: []
[03/22/17 14:57:06] [debug] User config: []
[03/22/17 14:57:06] [debug] Custom config: []
[03/22/17 14:57:06] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\122\\Desktop\\youtube-dl-gui-0.3.8-win-portable-b791ac8\\%(title)s.%(ext)s', '-v', '--ignore-config', '--hls-prefer-native', 'http://www.svtplay.se/video/12885148/skavlan/skavlan-sasong-17-avsnitt-10']
[03/22/17 14:57:06] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[03/22/17 14:57:06] [debug] youtube-dl version 2017.03.22
[03/22/17 14:57:06] [debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[03/22/17 14:57:06] [debug] exe versions: none
[03/22/17 14:57:06] [debug] Proxy map: {}
"

**Comment by norden1** [comment]
Hope i contribute with some help.

**Comment by MrS0m30n3** [comment]
I just uploaded a new portable build.
You can get it from [here](https://drive.google.com/open?id=0B4LUjPpAKNa1clVOY3pfRnlGMUU) it's based on commit https://github.com/MrS0m30n3/youtube-dl-gui/commit/77cfd53058c44372898fca17affef7e8011e34d8.

Let me know if this solves your issue.

**Comment by norden1** [comment]
The new version works fine the filesize are shown correctly now.  
Thanks for that.  
I have some small suggestions i post them here.

when download many episodes there are a lot lot of copy and paste. A  function to save the Project when closing program. And next time you start the program it can resume so you dont need to copy and paste all links again which you dont have downloaded yet.

A shortcut on mainside on program to subtitle option. I mean first go to option tab and select subtitle language. And then a shortcut on mainside there you can check or uncheck a box and choose subtitle or not based on settings in option tab. and so you even can see if subtitle are choosen or not.
And the new gui looks great its Clean and nice layout.

**Comment by MrS0m30n3** [comment]
Your suggestions are already in my TODO list.
Thanks for reporting this bug, if you spot anything else let me know.
