### ISSUE TITLE
youtube-dl-gui only downloads half the videos on a certain channel hand hangs

### ISSUE THREAD

**Issue by eldergamer** [MrS0m30n3/youtube-dl-gui#168]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### WARNING
All the invalid issues will be rejected!!

---

### Before going further
* If your problem is a bug with the **youtube-dl** program or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

* Make sure you are using the *latest* **youtube-dl-gui** version: `Options > About` tab. If it's not please download & install the latest version for your OS and check if your issue still persists

* Make sure you are using the *latest* **youtube-dl** version: Click the `Update` button on the main screen and check if your issue still persists

* Make sure you searched the bugtracker for similar issues including closed ones

  - [ ] **I assure** that my problem is **NOT** with **youtube-dl**
  - [ ] I've **verified** and **I assure** that I'm running youtube-dl-gui **0.3.8**
  - [ ] **I assure** that i am using the latest version of **youtube-dl**
  - [ ] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker

---

### What is the purpose of your *issue*?
- [x] Bug during the download process (encountered problems after hitting the *Download* button)
- [ ] Bug other (encountered other problems with *youtube-dl-gui*)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Please remove the following section between the (---) if your problem does not belong to the **bug during the download process** category

#### Provide the full verbose output as follows:

1. Add `-v` flag to Options > Commands tab
2. Re-try to download the URL
3. Go to `Options > Log` tab and click the `View Log` button
4. Copy the **whole** content of the log file and insert it between the triple ``` part

```
[delete me and insert your log content here]
```

---

Please remove the following section between the (---) if your problem does not belong to **the first two categories (bug report)**

#### List of actions to perform to reproduce the problem:
  1. ..
  2. ..
  3. ..
  
#### What happens instead ?

---

**Comment by eldergamer** [comment]
Thanks for taking a moment to look at this. Also I could not fill out the bug report properly. I don't know why. I use firefox and when it didn't work I switched to chrome but still it would not let me insert the log above so I will insert it below and try explaining my issues as good as I can.

I am using Youtube-dl-gui 0.3.8, I am running windows 10.

Here is the situation. I am trying to download all the videos from the following channel on youtube:

https://www.youtube.com/user/FIKITEnSUP/videos

the download process will begin. It says there are 131 video to download. dl-gui gets 76 of them and stalls. I checked the log and it says the following:

WARNING: Requested formats are incompatible for merge and will be merged into mkv.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.

This is not a mistake, it is listed twice. I am also including a attatchment with a screenshot

Hope you can help me.

Thanks,
eldergamer@gmail.com

![errors with youtube-dl-gui](https://cloud.githubusercontent.com/assets/27978413/25361135/6cde8eae-2901-11e7-9871-51722fce600f.png)

**Comment by MR-2** [comment]
@eldergamer webm. isn't suitable for mp4.

**Comment by eldergamer** [comment]
Thanks for your response. I'm not sure what do next. I changed the video setting from default to mp4 1920x1080. I updated the FFmpeg by overwriting the older ones in the YoutubeDLG. I testing it now. It's getting stuck in preprocessing on 108/132. The same channel as before:

https://www.youtube.com/user/FIKITEnSUP/videos

**Comment by MR-2** [comment]
@eldergamer 
The inconstancy in number of fragments that you're able to fetch in the two separate goes at it makes me think it might be something completley unrelated to the application. 

Are you using a unstable wireless internet connection?
 Do you have strict firewall settings that might interfere with the application?

**Comment by eldergamer** [comment]
My internet is solid, I'm not wireless, and I am not using a proxy. In fact
I installed youtube-dl-gui on my machine at work and had the same result. I
put it on a machine that is outside the firewall at work so I know it
wasn't firewall related. I'm stumped...

Thanks
eldergamer

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
