### ISSUE TITLE
Enhancement: youtube-dl command line update process

### ISSUE THREAD

**Issue by Hanvdm** [MrS0m30n3/youtube-dl-gui#172]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### WARNING
All the invalid issues will be rejected!!

---

### Before going further
* If your problem is a bug with the **youtube-dl** program or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

* Make sure you are using the *latest* **youtube-dl-gui** version: `Options > About` tab. If it's not please download & install the latest version for your OS and check if your issue still persists

* Make sure you are using the *latest* **youtube-dl** version: Click the `Update` button on the main screen and check if your issue still persists

* Make sure you searched the bugtracker for similar issues including closed ones

  - [x] **I assure** that my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **I assure** that I'm running youtube-dl-gui **0.3.8**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker

---

### What is the purpose of your *issue*?
- [ ] Bug during the download process (encountered problems after hitting the *Download* button)
- [ ] Bug other (encountered other problems with *youtube-dl-gui*)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information. Please make sure the description is worded well enough to be understood.
Since you close my previous submission perhaps I am unfamiliar how to fill this report.
As I am not a programmer and this program is by far one of the best and I use it quit often

I would like to ask if it is possible to please put something extra in the update procedure to first check if the -dl command line application is already up to date. Because sometimes I as a user make the mistake by pressing the update button by mistake after I already updated the program a very short time back.
When you press the update button it download the -dl command line application all over again. I know this issue is not really the programmer problem but rather I ask if something like this could be included in the gui program. I know the youtube-dl program have his own update flag so it should be easy to include in the youtube-dlg gui program.
Otherwise if this will be impossible to implement please when the gui program start for the first time and the the user press the update button to keep the update button greyed out for that particular session until the gui program close and startup again
Thank you very much
Sorry if the previous post were understandable.

**Comment by MrS0m30n3** [comment]
In the new UI the update button is not longer available in the main window so i think you wont have the same problem. Also, checking the *youtube-dl* version during the update process is already in my TODO list but at the end of the day the user is responsible on how he-she uses the UI.

If you want to try out the new UI:
* **Windows** (portable): [google drive](https://drive.google.com/file/d/0B4LUjPpAKNa1clVOY3pfRnlGMUU/view?usp=drive_web)
* **Linux**: Clone the *new_layout* branch using git and run `python -m youtube_dl_gui`

**Comment by Hanvdm** [comment]
Thank you very much for your reply and I will look at the new layout that you put in your link description.
Thank you
