### ISSUE TITLE
when calling "get command" menu item, spaces in output filename template break template argument

### ISSUE THREAD

**Issue by tolik89u** [MrS0m30n3/youtube-dl-gui#173]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### WARNING
All the invalid issues will be rejected!!

---

### Before going further
* If your problem is a bug with the **youtube-dl** program or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

* Make sure you are using the *latest* **youtube-dl-gui** version: `Options > About` tab. If it's not please download & install the latest version for your OS and check if your issue still persists

* Make sure you are using the *latest* **youtube-dl** version: Click the `Update` button on the main screen and check if your issue still persists

* Make sure you searched the bugtracker for similar issues including closed ones

  - [x] **I assure** that my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **I assure** that I'm running youtube-dl-gui **0.3.8**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker

---

### What is the purpose of your *issue*?
- [ ] Bug during the download process (encountered problems after hitting the *Download* button)
- [x] Bug other (encountered other problems with *youtube-dl-gui*)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Please remove the following section between the (---) if your problem does not belong to **the first two categories (bug report)**

#### What operating system do you use ?
Windows 10 x64 russian locale
#### List of actions to perform to reproduce the problem:
  1. in settings, set output filename template so that it contains spaces, e. g.
`%(upload_date)s\%(id)s_%(playlist_id)s - %(format)s.%(ext)s`
  2. add some downloads to the downloads list
  3. press right mouse button on one and click "get command" menu item
  
#### What is the expected behaviour ?
output filename template command line argument is correctly escaped so that spaces in template do not split it into multiple separate (invalid) arguments, so that youtube-dl could correctly run that command, e. g.
`youtube-dl.exe -o "%(upload_date)s\%(id)s_%(playlist_id)s - %(format)s.%(ext)s"`
#### What happens instead ?
spaces are not escaped and since in windows command line commands space is an arguments separator, therefore not properly escaped spaces split template argument on multiple args and break the command, so that youtube-dl already cannot rut in correctly, e. g. `youtube-dl.exe -o %(upload_date)s\%(id)s_%(playlist_id)s - %(format)s.%(ext)s`

---

### Description of your *issue*, suggested solution and other information. Please make sure the description is worded well enough to be understood.
I suggest at least to wrap the output filename template in double quotes as I showed that above, as the easiest (but maybe not the best) solution.

**Comment by MrS0m30n3** [comment]
Hi, @tolik89u 

I just uploaded a patched portable version, you can get it from [here](https://drive.google.com/file/d/0B4LUjPpAKNa1bU5qb0tNRGJCTU0). I used double quotes (not the best solution) to get around spaces since '\\' and '^' did not work on Windows.

If the issue still persists let me know else you should close this issue, thanks for the report.
