### ISSUE TITLE
Can not download file

### ISSUE THREAD

**Issue by alex-s-m** [MrS0m30n3/youtube-dl-gui#183]
Can not download file
https://github.com/MrS0m30n3/youtube-dl-gui/releases/download/0.4/youtube-dl-gui-0.4-win-portable.zip

**Comment by MrS0m30n3** [comment]
There is no release yet available for version 0.4 you can download 0.3.8
https://github.com/MrS0m30n3/youtube-dl-gui/releases/download/0.3.8/youtube-dl-gui-0.3.8-win-portable.zip
