### ISSUE TITLE
Separated folders

### ISSUE THREAD

**Issue by Sonicpromo** [MrS0m30n3/youtube-dl-gui#185]
- [ ] **I think** my problem is **NOT** with **youtube-dl**
  - [ x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [ x] **I assure** that i am using the latest version of **youtube-dl**
  - [ x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [ x] I've read the FAQs file

---

Hello
IFAIK it is not possible to separate videos to a different folders depending on the channel's name? Can I ask you to implement this feature in your GUI version of youtube-dl?
Thanks

Example: save folder/channel_name1, save folder/channel_name2, etc

**Comment by MrS0m30n3** [comment]
You can use the `%(chapter)s_%(chapter_number)s` in the "filename format" field.

**Comment by Sonicpromo** [comment]
What do you mean? In output/custom template or commands? Its not working for me, still saves the video into 1 folder without separation

**Comment by MrS0m30n3** [comment]
The `%(chapter)s_%(chapter_number)s` is wrong, excuse me.
You should use something like that `%(uploader)s/%(title)s.%(ext)s`

In order to use a custom template just go to "General" tab and select "Custom" under the "Filename format" field. Then you can paste you own output template in the box below.

**Comment by Sonicpromo** [comment]
Much obliged, you are my hero! :-)

**Comment by Sonicpromo** [comment]
Hello
One more question please: can I download 1080p video+best audio and then convert them to 720p with 2pass vbr and lets say 128 aac for better image quality/bitrate and less space (automatically) using ffmpeg? And how to limit the bitrate/framerate in that case?
