### ISSUE TITLE
only remux audio

### ISSUE THREAD

**Issue by nwgat** [MrS0m30n3/youtube-dl-gui#187]
when "Convert to Audio"
please add a "Only Remux" option

so that if the file has opus, then simply remux it to .opus
ffmpeg file.webm -acodec copy file.opus (if opus)
ffmpeg file.webm -acodec copy file.ogg (if vorbis)
ffmpeg file.mp4 -acodec copy file.m4a (if aac)

that way you wont lose even more quality from re-encoding it
and alot of players already has support for the codecs

**Comment by MrS0m30n3** [comment]
Sorry i cant help you...
