### ISSUE TITLE
Download links broken

### ISSUE THREAD

**Issue by CRRZYMAN** [MrS0m30n3/youtube-dl-gui#188]
- [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

### What is the purpose of your *issue*?

- [x] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

My issue is very simple: Most of the download links in the 'downloads' section are broken, including the Source .zip, Source tar.gz, PyPi, Windows Installer, and Windows Portable downloads. All of them link to a '404 Not Found' page or a 'Page Not Found' on Github. While I will try to compile the application from source, the download links should really be fixed as they are a far more convenient way to download the application, especially for Windows.

**Comment by MrS0m30n3** [comment]
https://github.com/MrS0m30n3/youtube-dl-gui/issues/183
