### ISSUE TITLE
Tray/notification icon with drag-n-drop?

### ISSUE THREAD

**Issue by nodiscc** [MrS0m30n3/youtube-dl-gui#19]
A tray icon that supports drag n dropping URLs (eg. from your browser bar, link on web page...) on it for quick download would be nice. I found [gtkStatusIcon](http://www.pygtk.org/pygtk2reference/class-gtkstatusicon.html) for pyGTK.

[nomnom](http://nomnom.sourceforge.net/) had this but sadly it's abandoned and only compatible with clive/cclive download tools.

**Comment by mbnoimi** [comment]
+1

**Comment by nodiscc** [comment]
> The wx.TaskBarIcon doesn't have a drag & drop event

I looked into it and this was my conclusion as well. Without drag and drop capabilities a tray icon does not have much benefits. Closing.

**Comment by MrS0m30n3** [comment]
I would like to take a closer look on this and see what we can do about it, so leave it open.

**Comment by h-h-h-h** [comment]
It doesn't have to be dropping on a tray icon. There can be a little always-on-top window for that -- translucent, if possible --, like [LameXP](https://github.com/lordmulder/LameXP) does it. Though the main window, or the list view in it, should accept dropped data, too:
- ![LameXP's little drap-n-drop window](https://cloud.addictivetips.com/wp-content/uploads/2012/05/Drag-N-Drop.jpg)
- ![LameXP's main window accepting dropped data](http://www.free-codecs.com/pictures/screenshots/Lamexp.jpg)

**Comment by h-h-h-h** [comment]
If drag-and-drop support is implemented, please allow internet shortcut files, too! On Windows, `.url` files are used, mostly. They can be read via COM. [MPC-BE](https://mpcbe.sourceforge.io/)'s codebase shows [how](https://sourceforge.net/p/mpcbe/code/HEAD/tree/trunk/src/apps/mplayerc/PlayerPlaylistBar.cpp#l994).

Here are search queries on Github and Google to find Python code for loading `.url` files:
- https://github.com/search?l=&q=CLSID_InternetShortcut+language%3APython&type=Code
- https://www.google.com/search?q=py|python+%22CLSID_InternetShortcut%22+-site%3Agithub.com&oq=py|python+%22CLSID_InternetShortcut%22+-site%3Agithub.com

This youtube-dl issue give you more information on internet shortcut fileformat for other platforms than Windows: https://github.com/rg3/youtube-dl/issues/16402.

**Comment by nodiscc** [comment]
Unmaintained project, use https://github.com/axcore/tartube
