### ISSUE TITLE
question about playlist function

### ISSUE THREAD

**Issue by norden1** [MrS0m30n3/youtube-dl-gui#193]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

I wonder when and how I can use this option playlist. I try to dowenload a lot of episodes and try to rename like 1 and  and more. How this playlist option work?
![dlg](https://user-images.githubusercontent.com/22798405/28357508-eeccf538-6c6b-11e7-80d6-81ccc23cc065.jpg)

**Comment by norden1** [comment]
I wonder when and how I can use this option playlist. I try to dowenload a lot of episodes and try to rename like 1 and  and more. How this playlist option work?
![dlg](https://user-images.githubusercontent.com/22798405/28357508-eeccf538-6c6b-11e7-80d6-81ccc23cc065.jpg)

**Comment by MrS0m30n3** [comment]
I can't understand what exactly is your question, anyways...

---
>I wonder when and how I can use this option playlist

When you want to select specific playlist items or download a part of the playlist

>I try to dowenload a lot of episodes and try to rename like 1 and and more

Nice

>How this playlist option work?

You can select the *start* & *stop* index and you can also set the *max* number of items to download if you don't want to download the whole playlist

**Comment by norden1** [comment]
Thanks for answer now I now what its meaning. If I want to download a playlist from SVT they must also have the function playlist in their site its that correct?

**Comment by MrS0m30n3** [comment]
Yes, in order to download a playlist the website must provide one.
It's like going to buy a car, ofc you have to go to a place they sell cars else it's not possible to buy one.
