### ISSUE TITLE
Missing button icons

### ISSUE THREAD

**Issue by tqphan** [MrS0m30n3/youtube-dl-gui#197]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [ ] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [ ] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [ ] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **youtube-dl-gui**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

the log is empty

#### What operating system do you use ?
windows 10 x64 pro

#### List of actions to perform to reproduce the problem:

  1. launch youtube-dl-gui
  2. ..
  3. ..
  
#### What is the expected behaviour ?
program launch error free

#### What happens instead ?
Unable to open stop32_px.png. Many buttons on the gui are missing. In fact, all buttons are missing except the options button and the reload button 

---

**Comment by MrS0m30n3** [comment]
1. Where did you installed **youtube-dlg** from?
2. Are you sure that "launching youtube-dl-gui" was the only thing you did after the installation?

**Comment by tqphan** [comment]
1. downloaded youtube-dl-gui-0.4-win-portable.zip from https://github.com/MrS0m30n3/youtube-dl-gui/releases 
2. I unzip it in a virtual box running win10 x64 pro, executed youtube-dl-gui.exe from 'portable' folder. get error about stop32_px.png

I checked the png files in \portable\data\pixmaps, all the png files are blank except youtube-dl-gui.png. I'll try to replace the png files from  0.3 version and see what happens later when I have time and report back

**Comment by MrS0m30n3** [comment]
All the PNG files look fine for me. You don't have to replace the PNG files from version 0.3 just redownload the portable version, maybe they got corrupted when you transfered them to the VM or while extracting them.
