### ISSUE TITLE
Enhancement: Option "maximum parallel downloads"

### ISSUE THREAD

**Issue by chill0r** [MrS0m30n3/youtube-dl-gui#20]
It would be nice if there would be an option to change the maximum downloads.

Currently it's fixed at 3 downloads at each time.

**Comment by MrS0m30n3** [comment]
@nodiscc @chill0r https://github.com/MrS0m30n3/youtube-dl-gui/commit/0f63f956bf76b56164590b5253bbecee7611b0f1

Now you can change the number of max parallel downloads by editing the 'workers_number' option on your settings.json file (~/.config/youtubedlg/settings.json). Note that you need to restart youtubedlg for the changes to take place. Also, this option will be added on the new GUI layout (as a GUI option) so you wont have to edit the settings.json file everytime.

I will leave this issue open until i push the new GUI layout.

**Comment by farseenabdulsalam** [comment]
Hi @MrS0m30n3 it's my pleasure to help you.
But I'm completely new to git and GitHub.
I'm still trying to figure out how things work here :)
