### ISSUE TITLE
Can I consider language to increase support for Chinese?

### ISSUE THREAD

**Issue by lki2019** [MrS0m30n3/youtube-dl-gui#205]
Can I consider language to increase support for Chinese?

Thank you

**Comment by MrS0m30n3** [comment]
There were multiple pull-request adding Chinese support (check [pull-requests](https://github.com/MrS0m30n3/youtube-dl-gui/pulls?utf8=%E2%9C%93&q=Chinese)) but there are all abandoned.

If you are interested you can try adding support for Chinese on your own by following our [guide](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/localization_howto.md).
