### ISSUE TITLE
n00b Windows installation guide

### ISSUE THREAD

**Issue by AdKiller** [MrS0m30n3/youtube-dl-gui#207]
Please add a step by step for Windows installation.
thanks

**Comment by MrS0m30n3** [comment]
What more can we add?

You just extract the setup file from the ZIP, run it and follow the instructions.

**Comment by AdKiller** [comment]
sorry for the false positive. it did not work for me the first time I tried youtube-dl-gui-0.4-win-portable, I thought it was because I was missing Requirements:    Python 2.7.3+,     wxPython 3,     TwoDict

However, I did notice the portable version drops files in AppData-- which is not ok for a portable app. Maybe it didn't work the first time because it couldn't add those files to AppData...

**Comment by MrS0m30n3** [comment]
We have already an open issue regarding the configuration path in the portable version. Check https://github.com/MrS0m30n3/youtube-dl-gui/issues/65
