### ISSUE TITLE
Unable to stop or delete link

### ISSUE THREAD

**Issue by duytrung** [MrS0m30n3/youtube-dl-gui#210]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [ ] **I think** my problem is **NOT** with **youtube-dl**
  - [ ] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [ ] **I assure** that i am using the latest version of **youtube-dl**
  - [ ] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [ ] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [X] Bug report
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---
```
### Bug report
I tried to pause and remove the link, it show 100% but not complete. 
GUI not responding on pressing pause button.

I tried to delete link using delete (recycle bin) icon. but GUI said that: Item is active can not remove.

I tried to play the file. But GUI said it is not completed although it show 100%.

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

---

### Feature request (request for a new functionality)

Please make sure that the requested feature is **NOT** already in the [TODO](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/TODO) list

- [ ] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list
I think GUI to increase number of parallel download, not only 3 at the same time but if needed, to 4, 8 or so.

I think that placing the youtube-dl.exe in the portable folder would be better than in the user's folder. I locate this file and found that it was downloaded and store in the user folder. 
#### What operating system do you use ?

Vista Home
---
```

**Comment by MrS0m30n3** [comment]
Sure my friend all you dreams will come true one day.
