### ISSUE TITLE
I installed with pip on OSX, now how do I run it?

### ISSUE THREAD

**Issue by ntnelson1s** [MrS0m30n3/youtube-dl-gui#211]
It seems like a stupidly simple problem, I've installed the youtube-dlg program using pip on MacOS Sierra 10.12.3, got my dependencies in order through some struggling (wxpython3 instead of version 4), etc., and then now that I've gotten to a point where everything seems to be installed where it should be fit to run, I can't seem to figure out how. Here's where I got to.

`$ sudo -H pip install youtube-dlg`
`Requirement already satisfied: youtube-dlg in /private/var/root/Library/Python/2.7/lib/python/site-packages`

My question is, how do I simply run youtube-dlg? The app name and path are listed, and I'm naively stuck on where to go next. This may be a pathing issue I'm not aware of. I was hoping to run it once and find a way to keep it either pinned to the Dock or in Apps seeing as it is a GUI. Getting this to work on windows was easy enough, but unfortunately in the OS world I am master of none, user of many.

**Comment by MrS0m30n3** [comment]
Or you could just type `youtube-dl-gui` in your terminal and hit Enter.

You can also create an desktop launcher (or whatever it's called in the Mac world) and use that to launch the application from you desktop-dock-etc.

**Comment by thegayankalinga** [comment]
check out this 

https://github.com/Kevin-De-Koninck/Get-It
