### ISSUE TITLE
.deb file dependency issue. twodict is installed but when it checks for dependencies it doesn't detect it. 

### ISSUE THREAD

**Issue by RustyRaptor** [MrS0m30n3/youtube-dl-gui#213]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bug-tracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

Please remove any sections between (---) if they are not related to your issue

---

### Bug report
The latest .deb on the Ubuntu ppa for xenial is not working. I assure you that twodict is installed and working. I tried both using the source and pip install. I am not sure if this is something I should report here though. 

```
sudo dpkg -i youtube-dlg_0.4-1-webupd8-xenial4_all.deb 
(Reading database ... 308847 files and directories currently installed.)
Preparing to unpack youtube-dlg_0.4-1-webupd8-xenial4_all.deb ...
Unpacking youtube-dlg (0.4-1~webupd8~xenial4) over (0.4-1~webupd8~xenial4) ...
dpkg: dependency problems prevent configuration of youtube-dlg:
 youtube-dlg depends on python-twodict (>= 1.2); however:
  Package python-twodict is not installed.

dpkg: error processing package youtube-dlg (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Errors were encountered while processing:
 youtube-dlg

```

#### List of actions to perform to reproduce the problem:

  1. Download the .deb file from the ppa link
  2. run sudo dpkg -i <filename>
  3. Install the dependency it asks for (twodict) once with pip and again from source and try again 
  
#### What is the expected behavior?
should install normally when twodict is installed. 

#### What happens instead?
It doesn't install and says twodict isn't installed
---

#### What operating system do you use?
Ubuntu 16.04 Xenial 

---

Not sure if this is Ubuntu's fault or a mistake in the .deb file.

**Comment by nodiscc** [comment]
Hi @RustyRaptor the Ubuntu PPA is maintained by @hotice (owner of the webupd8.org website) and is not affiliated with this repo; I tried to ping him [here](https://github.com/MrS0m30n3/youtube-dl-gui/pull/189#issuecomment-314808071) to see if we could work on a common package but no reply so far. I suggest that you contact the package maintainer whose address should be in the information of the .deb package you downloaded.

We are also working on a Debian package but it's incomplete, and we still have to package python-twodict. See #189 and #21

**Comment by MrS0m30n3** [comment]
Just download and install the **python-twodict** package from [here](http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/pool/main/p/python-twodict/). Then you should be able to install the youtube-dlg deb package using *dpkg*.
