### ISSUE TITLE
Feature request: Show the download progress & accelerate with wget

### ISSUE THREAD

**Issue by duytrung** [MrS0m30n3/youtube-dl-gui#219]
### What is the purpose of your *issue*?

- [ ] Bug report
- **[x]** Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Feature request (request for a new functionality)

1. Please add a download progress for each item in the tree for each playlist. I found that there are some broken download as *.part files. I re-entering it to make the program resume.
2. Save these list for future use, for example, to update the new video available in the channel. So we dont have to download duplicates. 
3. Save channel to each folder name based on channel name.
3. Accelerate downloads with wget or similar like curl ...

#### What operating system do you use ?
Win10

---

**Comment by MrS0m30n3** [comment]
1) Not sure what exactly you are saying but we plan to improve the playlist download procedure.
2) You can add the `--download-archive FILE` option under the **Options** > **Extra** tab. This will create a file with all the video ID's you have downloaded, preventing youtube-dlg from downloading duplicates.
3) Go to **Options** > **General** tab and set the **Filename format** to **Custom**.
4) Not sure what exactly you mean.

Please before posting check the guidelines.
