### ISSUE TITLE
Youtube-dlg stops downloading queue when encountering blocked content

### ISSUE THREAD

**Issue by TMi4** [MrS0m30n3/youtube-dl-gui#22]
First of all, thanks for this awesome tool.

Sadly I encountered an issue when downloading playlists or channels:

ERROR: [...]: YouTube said: Unfortunately, this video is not available in your country because it could contain music, for which we could not agree on conditions of use with GEMA.

After this yt-dlg just halts and does not finish what's left in the queue.

This should be solvable by using youtube-dl's "-i" or "--ignore-errors".
I tired setting this up in the "Commands" section within the options, but it doesn't seem to work as I am still getting the Error and youtube-dlg refuses to download anything after it encountered said GEMA related error.

This is not about circumventing geo-blocking; I just want yt-dlg to continue downloading and skipping blocked videos to finish whats left in the queue.

**Comment by MrS0m30n3** [comment]
I am closing this issue, feel free to reopen it if you need to.
