### ISSUE TITLE
1080p DASH videos from Youtube have no audio

### ISSUE THREAD

**Issue by octophetus** [MrS0m30n3/youtube-dl-gui#223]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [ ] **I think** my problem is **NOT** with **youtube-dl**
  - [X] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [X] **I assure** that i am using the latest version of **youtube-dl**
  - [X] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [X] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **youtube-dl-gui**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

```
delete me and insert your log content here
```

#### What operating system do you use ?
Windows 10

#### List of actions to perform to reproduce the problem:

  1. Choose any youtube link to a video with 1080p quality
  2. Choose option "MP4 [1080p] (DASH video)"
  3. Open the file and see that the audio file is incorrect.
  
#### What is the expected behaviour ?
Select option to download 1080p Youtube DASH format video and have it choose correct corresponding audio
#### What happens instead ?
Downloads 1080p Youtube DASH format video with non-functioning audio

---

### Feature request (request for a new functionality)

If you use the youtube-dl format option youtube-dl -f "137+140" under options>extras then it will download 1080p video with working audio. Would like for this to be a setting option instead of needing to add and remove it all the time from options>extras (since it is not a setting I use when downloading from other sites than Youtube).

- [X] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list

#### What operating system do you use ?
Windows 10...

---

**Comment by nodiscc** [comment]
@octophetus does using the `default` format setting not produce working 1080p video + audio files for you? It works for me (no need to edit options)

Example: https://www.youtube.com/watch?v=Zkkr-HhnwS8

```
$ mediainfo "M.I.A. - P.O.W.A-Zkkr-HhnwS8-youtube.mkv"
[...]
Complete name                            : M.I.A. - P.O.W.A-Zkkr-HhnwS8-youtube.mkv
Format                                   : Matroska
[...]
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
[...]
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
[...]
Audio
Format                                   : Opus
Codec ID                                 : A_OPUS
Duration                                 : 3 min 49 s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 kHz
```

**Comment by octophetus** [comment]
Wow. Idk what I was doing wrong but it is in fact working. I swear lol it didn't work in default so I thought I had to make it DASH and blah blah blah. But default is working just fine. Sorry! I don't know where I went wrong!

**Comment by MrS0m30n3** [comment]
Also, note that in the next release you will be able to create your own formats and have them available in the formats drop-down. See [TODO List #6](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/TODO#L6) and please check the TODO list before posting a Feature request.

**Comment by raniesantos** [comment]
@MrS0m30n3

**Comment by raniesantos** [comment]
> in the next release you will be able to create your own formats and have them available in the formats drop-down

@MrS0m30n3 Is it out yet?

**Comment by MrS0m30n3** [comment]
@raniesantos 

1. This option will be available in version 0.4.1
2. No reason to add other formats since you will be able to create your own formats

**Comment by raniesantos** [comment]
@MrS0m30n3 Fair enough, I just assumed it would make sense as a default since it's always in YouTube's quality options.

**Comment by monkeylove** [comment]
Hi. Is there a way to use AAC or MP3 instead of Opus?

Edit:

I found the solution. Add the following to the "extra" tab of the options window:

$ youtube-dl -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"
