### ISSUE TITLE
Documentation: Windows: Recommend Installation of Microsoft Visual C++ 2010 Redistributable Package 

### ISSUE THREAD

**Issue by scarejar** [MrS0m30n3/youtube-dl-gui#224]
https://www.microsoft.com/en-US/download/details.aspx?id=5555

Fresh install of Windows here, installed youtube-dl-gui and the application kept crashing and spent a little while trying to figure out why, in which, followed instructions from  youtube-dl to install this and it stopped crashing, everything started working

**Comment by genpfault** [comment]
I didn't even get a crash, it just pretended to succeed and didn't download any files.  Nothing in the log either about `youtube-dl` failing to run.

**Comment by MrS0m30n3** [comment]
Exactly the same issue https://github.com/MrS0m30n3/youtube-dl-gui/issues/142. I guess we could add it in the FAQs.
