### ISSUE TITLE
[suggestion] drop https://code.google.com/p/youtube-dlg/

### ISSUE THREAD

**Issue by nodiscc** [MrS0m30n3/youtube-dl-gui#23]
Hi @MrS0m30n3 glad to see there's progress on the refactoring. This is just to let you know that you can use github [Releases](https://github.com/blog/1547-release-your-software), and attach the windows binary to the github releases. This would be more comfortable than keeping the cooglecode project around, and hosting the releases on google drive..

I'd also be more comfortable downloading from github when I'm on a windows machine.

Let me know if I can be of any help.

**Comment by MrS0m30n3** [comment]
@nodiscc 

Now you can find the Windows binaries under https://github.com/MrS0m30n3/youtube-dl-gui/releases
as you suggested.

From now on the google code project is not longer maintained but i wont drop the project because the google code will shutdown anyway.
