### ISSUE TITLE
[Feature request]: use website for localisations

### ISSUE THREAD

**Issue by luigino** [MrS0m30n3/youtube-dl-gui#232]
I suggest that you rely on something like transifex/weblate/zanata to coordinate translations.

That way, translators will receive an email every time there are new strings and won't have to muck around with git to send them.

Just my 2 cents.

**Comment by MrS0m30n3** [comment]
That's a good idea and it will probably speed up things a little bit (translations taking me so much time to review). Have you used any of the above (transifex, weblate, zanata)?

**Comment by luigino** [comment]
Mostly transifex, but only from the translator side. Several packages I've helped localise rely on it, but I really don't know whether it's good or not from the developer's end.
I can only tell you weblate seems to have a snappier interface and is used by SUSE to localise its distro.

**Comment by nodiscc** [comment]
I have used Transifex as a translator, it is nice, and also used by large projects ([XFCE](https://www.transifex.com/xfce/public/) comes to mind). It makes finding untranslated or unreviewed strings, easier. It has some nice features like emailing translators when new .po files are added. It helps avoiding errors like accidentally breaking the .po syntax. Users can signup with Github (no extra account required). It can display some useful charts like https://www.transifex.com/projects/p/thunar/resource/master/chart/image_png

![](https://www.transifex.com/projects/p/thunar/resource/master/chart/image_png)

The only downside I've found is that, indeed the UI can sometimes become a bit slow.

**Comment by pavreh** [comment]
I use launchpad.net as a translator. This tool is developed by Canonical and projects like Ubuntu or Mint use it.

You can set a restriction for translations e.g. open - everyone can translate your project or structured - everyone can suggest a translation but only a member of a defined translation team can accept it.

Moreover you can set a regular automatic snapshot of the translations and commit it to your project.

**Comment by MrS0m30n3** [comment]
I went with Transifex [youtube-dl-gui](https://www.transifex.com/youtube-dl-gui/public/). It seems pretty good, it has a command line tool like git (called *tx*) for managing translations (push & pull) on the developers side and it's also a Greek based company.
