### ISSUE TITLE
Flac Audio Option

### ISSUE THREAD

**Issue by User486375** [MrS0m30n3/youtube-dl-gui#234]
Why isn't there a Flac option in the audio formats? I can see that youtube-dl already supports it? Thanks.

**Comment by MrS0m30n3** [comment]
You can now enable the *flac* audio format under **Audio formats** in the `Options > Formats` tab.

**Comment by User486375** [comment]
Thanks for the fast response and change! I'm now just wondering if it's either not working correctly or if it takes time to become live on updates/windows installer? I updated the windows portable version but can't see the Flac option in **Audio formats**, I also tried out the windows installer and updated that with also no success.

**Comment by MrS0m30n3** [comment]
That's because there is not a new release yet.
You can either wait for the next release or download and install from source [master zip](https://github.com/MrS0m30n3/youtube-dl-gui/archive/master.zip).

**Comment by User486375** [comment]
Ah I was thinking this is probably the case, thanks once again for the amazingly fast changes!

**Comment by nathantaal** [comment]
> That's because there is not a new release yet.
> You can either wait for the next release or download and install from source [master zip](https://github.com/MrS0m30n3/youtube-dl-gui/archive/master.zip).

Do you have instructions to build the portable version or is it the same procedure?

**Comment by Meenit** [comment]
Sorry to revive an old thread, but I have the recent build of `youtube-dlg` (0.4), and I still don't see an option for FLAC under the `Options > Formats` tab.

**Comment by nathantaal** [comment]
> Sorry to revive an old thread, but I have the recent build of `youtube-dlg` (0.4), and I still don't see an option for FLAC under the `Options > Formats` tab.

I can confirm it isn't there, sadly, but it was merged after 0.4 was released. We'll still need to wait to 4.x or 5.0.

**Comment by edbird** [comment]
What would the point of this be? Youtube does not store audio in FLAC format, therefore it is pointless to convert whatever format is obtained from the download to FLAC.

FLAC only makes sense when encoding lossless, uncompressed formats such as WAV.
