### ISSUE TITLE
Downloading some videos at the wrong resolution

### ISSUE THREAD

**Issue by ClefAria** [MrS0m30n3/youtube-dl-gui#237]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [X] **I think** my problem is **NOT** with **youtube-dl**
  - [X] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [X] **I assure** that i am using the latest version of **youtube-dl**
  - [X] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [X] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [X] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### What operating system do you use ?

Windows 7 x64 SP1

#### List of actions to perform to reproduce the problem:

  1. Attempt to download this (and other videos on the same channel, that are naturally 720p@30) videos normally, such as https://youtu.be/sLiKbcO9Zz4, under "default"
  2. ..
  3. ..
  
#### What is the expected behaviour ?

It will download the video at its highest/native resolution, 720p

#### What happens instead ?

It downloads a 480p version instead. However, if I change the dropdown from "default" to "mp4 [720p]", the desired 720p version downloads as intended.

In my "formats" tab, I have everything selected, except for formats larger than 1080p (a waste to download for me, having a 1080p monitor), so I don't think that is the culprit.

**Comment by nodiscc** [comment]
I can't reproduce this. Tried to download https://youtu.be/sLiKbcO9Zz4 with the format set to `default` and the result is

```
$ mediainfo Barachi\ Assassin\ Part\ 1\ -\ Dungeon\ Crawl\ Stone\ Soup-sLiKbcO9Zz4-youtube.mp4
[...]
Width                                    : 1 280 pixels
Height                                   : 720 pixels
[...]
```

Are you sure you don't have any options set in `Options > Extra`? Or in `%APPDATA%/youtube-dl/config.txt`? Are you sure you selected the `default` format was selected when adding the video to the download list?

Also you didn't include the debug log as requested in the issue template.

**Comment by ClefAria** [comment]
I didn't change anything, but it's working now. I don't get it, but I guess issue resolved, lol...

**Comment by MrS0m30n3** [comment]
We can't help you if you don't provide the log output as stated in the issue template.
