### ISSUE TITLE
Feature request for an option to remove videos from the URL list when they're completed

### ISSUE THREAD

**Issue by bugzeeolboy** [MrS0m30n3/youtube-dl-gui#24]
I have satellite internet which errors out a lot, youtube-dlg works fine most of the time. Sometimes I have to restart the entire download and it just goes through all of them, pre-processes three videos at a time, and says the finished videos are finished. That's what I want instead of it redownloading them, but there are also some videos that won't download in WEBM that it would be hard to fish the list and take out all URLs except for those. It'd be neat if there were an option in the options window to remove URLs from the URLs list when they're done downloading, so when I press the download button again to finish the ones that error out (or to switch to a different format), it won't pre-process the list all over again (and I won't have to fish URLs to only redownload non-WebM videos). And perhaps, an option for a secondary format for when an undownloadable-in-this-format error occurs.

**Comment by MrS0m30n3** [comment]
Commits 01602d5, bb3983e and 621c391 fix this issue.

Under the new UI you can click the *Delete* button and select *Remove completed* which is going to remove only the *Completed* items and not the ones that have *Errors*. Also, you can now quickly re-insert a URL with different options using the *Re-enter* option under the context menu.

An option for the secondary format is not available but now the default video formats (mp4, webm, etc) are. You can also use the old trick mentioned above with the "-f 22/18/17" flag under Options>Extra tab. Just remember to leave the selected format to *default*.
