### ISSUE TITLE
Audio download. Conversion not working.

### ISSUE THREAD

**Issue by sharpaper** [MrS0m30n3/youtube-dl-gui#240]
- [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Bug report
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

#### What operating system do you use ?

Windows XP

#### List of actions to perform to reproduce the problem:

  1. Download a file and select "mp3" output.
  
#### What is the expected behaviour ?

Convert downloaded file to mp3.

#### What happens instead ?

Regardless of whatever output format I choose (mp3, aac, ...) the output is **always** `.webm`. The file is not converted to mp3.

**Comment by nodiscc** [comment]
#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **youtube-dl-gui**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

\`\`\`
delete me and insert your log content here
\`\`\`

**Comment by sharpaper** [comment]
Why was this closed? Was it solved?

**Comment by MrS0m30n3** [comment]
We cant help you without the log file.

**Comment by sharpaper** [comment]
1. I didn't open this issue looking for help-desk support. It simply happened that I had to run your program on windows xp, but something went wrong so I thought it was a good idea to report the issue. So this could be a legit bug
2. the fact that you closed the issue without even verifying the bug is laughable. You just closed it pretending that the issue doesn't exist. If this is a bug, it won't automagically fix just because you decided to ignore it
3. it happened that I had to use windows xp, but it could also be buggy on other platforms (but you're ignoring it)
4. I don't use windows xp regularly. It just happened that I ran your program on windows xp, saw the bug, and decided to report it later on the same day. I haven't posted the log because I haven't had a second chance to run windows xp in the last days. But the bug could also affect newer windows systems

I don't remember if I used the installer or portable version (probably portable).

**Comment by MrS0m30n3** [comment]
Let me repeat myself (i will type it in bold). **We can't help you if you don't provide the log file.** The issue template is there for a reason.

Your "bug" could be A-N-Y-T-H-I-N-G, from you failing to select the proper download format to some crazy stuff that i can't even think of right now.

When you find the time you can open a new issue and feel in the details properly. Until then, please stop wasting our time!
