### ISSUE TITLE
add "open folder"and its icon

### ISSUE THREAD

**Issue by jerry011235** [MrS0m30n3/youtube-dl-gui#241]
"open folder" means open output folder,open the folder where the videos just downloaded.

**Comment by MrS0m30n3** [comment]
You can open the destination folder using one of the two ways below:
* Right click on the download item and select "Open destination"
* Double click the **folder icon** next to the savepath drop-down (only few chosen people know about this option, congratulations you are one of them)

**Comment by jerry011235** [comment]
hahaha!Easter egg!
thank you!
and hope to add youtube-dl's Current version in "setting-about" window。
sometimes when youtubedl download failed(time out or other bugs), click the delete icon ,hint "can't remove"，then click the "X" icon,The window is not responding.

**Comment by MrS0m30n3** [comment]
>sometimes when youtubedl download failed(time out or other bugs), click the delete icon ,hint "can't remove"，then click the "X" icon,The window is not responding.

You should open a new issue for this and remember to fill in the details.
