### ISSUE TITLE
Always stuck on queued for far too long

### ISSUE THREAD

**Issue by Kiux97** [MrS0m30n3/youtube-dl-gui#242]
I am running the latest version of youtube-dl-gui. I have tried numerous different videos. I have restarted. I have given admin rights. Still, all videos get stuck on queued for atleast 30+ minutes before starting for some reaosn. Windows 10. Please tell me if there are any more details

**Comment by Kiux97** [comment]
Very sorry, title was supposed to be "Always stuck on queued for far too long"

**Comment by nodiscc** [comment]
>Please tell me if there are any more details

@Klux97 Hi, you didn't provide the info requested in the [issue template](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/.github/ISSUE_TEMPLATE.md). Please reopen an issue, don't delete the template text, and provide information where requested (check the appropriate boxes, include the full log). Without this information it is impossible to help you debug your problem :/ Thanks in advance
