### ISSUE TITLE
trying to give url at run time

### ISSUE THREAD

**Issue by monikarazdan** [MrS0m30n3/youtube-dl-gui#243]
[import shutil
import os 

u_input=int(input("enter url:"))

ydl_opts = {}
url=(u_input)
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download(url)
    info_dict=ydl.extract_info(url[0], download=False)
    video_title = info_dict.get('title', None)
    print(video_title)
print("DONE!")
script_dir = os.path.dirname(os.path.realpath(__file__))
print(script_dir+"\\" +video_title)](url)

**Comment by nodiscc** [comment]
@monikarazdan  Hi, you didn't provide the info requested in the [issue template](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/.github/ISSUE_TEMPLATE.md). Please reopen an issue, don't delete the template text, and provide information where requested (check the appropriate boxes, include the full log). Without this information it is impossible to help you debug your problem :/ Thanks in advance

**Comment by monikarazdan** [comment]
sorry I'm new to github too, and I didn't get it clearly, can u brief it

**Comment by nodiscc** [comment]
* Go to https://github.com/MrS0m30n3/youtube-dl-gui/issues/new
 * Don't delete the default text
 * Put a `x` in the relevant boxes, like this:

```
  - [x] **I think** my problem is **NOT** with **youtube-dl**
...
- [x] Question
```

 * Reply to the remaining questions (steps to reproduce, attach log if needed...)
