### ISSUE TITLE
Translations unnecessarily having country codes?

### ISSUE THREAD

**Issue by fitojb** [MrS0m30n3/youtube-dl-gui#247]
I can see that in the folder youtube-dl-gui/youtube_dl_gui/locale/ all the available translations have a country code. Why is that? The only one which could need it is perhaps pt_BR. es_ES is certainly unnecessary—just having “es” would suffice.

**Comment by nodiscc** [comment]
@fitojb This is the naming convention used by [GNU gettext](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/setup.py#L27). I think the docs should explain it all:

 * https://www.gnu.org/software/gettext/manual/html_node/Locale-Names.html
 * https://www.gnu.org/software/gettext/manual/html_node/Usual-Language-Codes.html#Usual-Language-Codes
 * https://www.gnu.org/software/gettext/manual/html_node/Country-Codes.html

Let me know if this answers your question

**Comment by fitojb** [comment]
I know what the codes are for; my comment was more about the translations being too specific; it is unusual to have everything country-coded in FOSS localizations. Most of the time, doing that leads to redundant volunteer work and reduced translation quality, as people can’t concentrate in having a single translation which almost always is enough for many countries in practice.

**Comment by fitojb** [comment]
I removed the question mark from my bug's title; that edit from your part was really patronizing.
