### ISSUE TITLE
Windows version not downloading youtube videos

### ISSUE THREAD

**Issue by jyrel59** [MrS0m30n3/youtube-dl-gui#248]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [ ] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### What operating system do you use ?
Windows server 2016 Standard

#### List of actions to perform to reproduce the problem:

  1. put youtube url in the top url box
  2. click on Add button
  3. click on Start Button
  
#### What is the expected behaviour ?
The expected behaviour is that it should download the video. 

#### What happens instead ?
No video is downloaded & a message box saying "Downloads completed" gets shown instantly 

---
Brief Description : 
Installed the setup file of latest version of youtube-dl, 
then placed a youtube url in the top url box
then clicked on "add" button [default is selected]
then clicked on "Start" button -> No video got downloaded & still a  message box saying "Downloads completed" gets shown instantly even though No video was downloaded.

**Comment by Be-ngt-oH** [comment]
Hi there,

could you check your log for "SSL CERTIFICATE_VERIFY_FAILED"? If this is the case, you can find a solution here: https://github.com/rg3/youtube-dl/issues/7309#issuecomment-172354527

Good luck

**Comment by MrS0m30n3** [comment]
From the FAQs file:
> * The program crashes frequently or pretends to succeed downloading the files (Windows): Follow [youtube-dl instructions](https://github.com/rg3/youtube-dl#the-exe-throws-an-error-due-to-missing-msvcr100dll) on updating your Visual C++ Redistributable.

**Comment by MrS0m30n3** [comment]
Closing, if your issue is not resolved you can re-open it.

**Comment by negativecitizen** [comment]
I' ve a definitive solution to this .You can redirect  the download directory for youtube-dl to avoid this error :1.  first locate your "settings.json" usually in  "C:\Users\<your user>\AppData\Roaming\youtube-dlg" 2. edit the last line ("youtubedl_path".............. ")
  and change the path  to something practical like C:\\youtube-dl  3. paste the latest  youtube-dl.exe   downloaded from this  url  https://github.com/ytdl-org/youtube-dl/releases/  
Probably you need to make the copy a a fresh .exe  time to time to get the latest version but  its straight and works. 
This is a way to  manually update the library avoiding  the certificate error and the lost of time .Enjoy
