### ISSUE TITLE
change config path to current directory in portable version.

### ISSUE THREAD

**Issue by jerry011235** [MrS0m30n3/youtube-dl-gui#249]
```
settings.json file location:
Windows: %appdata%\youtube-dlg\settings.json
Linux: ~/.config/youtube-dlg/settings.json
```
in portable version,hope the path is `./settings.json` or `%~dp0\settings.json`
and it will automatically download/update youtube-dl.exe to `%~dp0` in Windows.

Also,you can post youtube-dl-gui to the [portableapps forums](https://portableapps.com/forums),and it can be distributed as easy-to-use .paf.exe installer files.

**Comment by MrS0m30n3** [comment]
There is already an open issue for this, see #65.
