### ISSUE TITLE
Is Downloaded content info stored anywhere?

### ISSUE THREAD

**Issue by pooky2483** [MrS0m30n3/youtube-dl-gui#253]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [X] **I think** my problem is **NOT** with **youtube-dl**
  - [X] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [X] **I assure** that i am using the latest version of **youtube-dl**
  - [X] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [X] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---
OTHER

I have been downloading the videos of a YouTube channel 'https://www.youtube.com/user/SriLankerC/videos' and decided to download them all again but using a different video format. I first used mp4 and then decided to use webm, so I deleted the whole folder and try again, but it downloaded nothing.

I assume by this that youtube dl keeps some sort of history of what it has donloaded. So, what I'd like to know is, where is this infomation stored and if it does store dl info, is it safe to delete info of downloaded videos/channels.

---

**Comment by MrS0m30n3** [comment]
There is no option available in **youtube-dl-gui** to keep track of downloaded files (at least not yet).

You should ask in the youtube-dl's repo instead. Also, make sure that under the `Options>Extra` tab you have the **Ignore youtube-dl config** option set.

**Comment by nodiscc** [comment]
See also `--download-archive` in https://github.com/rg3/youtube-dl#video-selection
