### ISSUE TITLE
add a manpage

### ISSUE THREAD

**Issue by legrostdg** [MrS0m30n3/youtube-dl-gui#259]
It would help Debian packaging to add a simple manpage.

**Comment by MrS0m30n3** [comment]
In my opinion there is no point in adding a manpage, since there are no command-line args and adding just the *NAME*, *SYNOPSIS*, etc sections is just a waste of time.

**Comment by nodiscc** [comment]
I proposed a very simple manpage in https://github.com/MrS0m30n3/youtube-dl-gui/pull/261,  it's not much but it clarifies the basics, I also think Debian requires manpages for each binary, and it's nice to be able to list available programs by typing `man y<TAB><TAB>`.

@legrostdg you may also want to add a packaging rule to copy [README.md](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/README.md), [CHANGELOG](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/ChangeLog) and [TODO](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/TODO) (?) to `/usr/share/doc/`. I've seen may packages do that and it's nice to have all the docs available locally.

**Comment by MrS0m30n3** [comment]
Added a simple manpage +other-stuff, based on the @nodiscc's pull-request.
The setup.py installs the manpage in `{prefix}/share/man/man1` automatically, so you don't have to modify anything on the debian packaging side (probably).

**Comment by legrostdg** [comment]
@MrS0m30n3 do you think you could push another release? It would help getting this in Debian.

**Comment by MrS0m30n3** [comment]
Nope, i want to take care of all the issues in [Release 0.4.1 - Milestone](https://github.com/MrS0m30n3/youtube-dl-gui/milestone/2) first.

**Comment by legrostdg** [comment]
OK, I'll wait for this new release before integrating the changes in the Debian package.
