### ISSUE TITLE
Firefox integration

### ISSUE THREAD

**Issue by mbnoimi** [MrS0m30n3/youtube-dl-gui#26]
I suggest to add an integration with Firefox by asking [FlashGot addon](https://addons.mozilla.org/en-US/firefox/addon/flashgot/) admins to add an action for youtube-dlg

**Comment by mbnoimi** [comment]
I post a feature request flashgot forums:
https://forums.informaction.com/viewtopic.php?f=11&t=20466#p73987

**Comment by MrS0m30n3** [comment]
I don't really know how FlashGot works and i don't have the time to look it up, but i think it uses download managers like wget, youtube-dl to download the given links. So what's the point of adding my GUI into FlashGot when my GUI already uses youtube-dl as a download manager?

I mean you can probably use youtube-dl directly from FlashGot.

**Comment by mbnoimi** [comment]
You're absolutely correct but in case FlashGot passed a link to youtuble-dl it will deal with it under CLI so the user will be able to configure it as your GUI do (in same way of any GUI download manager ex. wget)

**Comment by MrS0m30n3** [comment]
Anyway, you posted on their forum so it should be fine. I mean what you ask is a feature request for their program not mine. I am closing this.
