### ISSUE TITLE
 Error in the new GUI version 2018.01.07 | ImportError: No module named combo

### ISSUE THREAD

**Issue by BlackHacker12** [MrS0m30n3/youtube-dl-gui#262]
hello 
I updated the YouTubeDL from Webupd8 PPA  and i tried to open the GUI Version but no response then i used the terminal to run it with this command : youtube-dl-gui  
 after writing the command i hit Enter i got this python error  :
======================================================================
          ***    ATTENTION   ***
This messaging protocol is deprecated. This module, and hence arg1
messaging protocol, will be removed in v3.4 of PyPubSub. Please make
the necessary changes to your code so that it no longer requires this
module. The pypubsub documentation provides steps that may be useful
to minimize the chance of introducing bugs in your application.
======================================================================

Traceback (most recent call last):
  File "/usr/bin/youtube-dl-gui", line 35, in <module>
    import youtube_dl_gui
  File "/usr/lib/python2.7/dist-packages/youtube_dl_gui/__init__.py", line 76, in <module>
    from .mainframe import MainFrame
  File "/usr/lib/python2.7/dist-packages/youtube_dl_gui/mainframe.py", line 19, in <module>
    from .optionsframe import (
  File "/usr/lib/python2.7/dist-packages/youtube_dl_gui/optionsframe.py", line 12, in <module>
    import wx.combo
ImportError: No module named combo

how can i fix it ? .

**Comment by nodiscc** [comment]
@BlackHacker12 What OS/distribution?

Youtube-dlg requires [wxPython 3](https://github.com/MrS0m30n3/youtube-dl-gui#requirements). You should have a file `combo.py` somewhere on your machine:

    $ locate combo.py
    /usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/combo.py

If this file is not present you probably should install the relevant python package. For debian-based distributions `sudo apt install python-wxgtk3.0`. If you are on Windows please ignore everything I just said (I guess you're using Linux since your log shows Linux paths).

**Comment by BlackHacker12** [comment]
@nodiscc  
Linux Mint 18.3
this the what i got i guess python-wx is installed
/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/combo.py
/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/combo.pyc
/usr/local/lib/python2.7/dist-packages/whoosh/matching/combo.py
/usr/local/lib/python2.7/dist-packages/whoosh/matching/combo.pyc
===============================================
python-wxgtk3.0 is already the newest version (3.0.2.0+dfsg-1build1).

**Comment by MrS0m30n3** [comment]
Next time use a larger font... hahahah
