### ISSUE TITLE
GUI Error -  ImportError: No module named combo

### ISSUE THREAD

**Issue by BlackHacker12** [MrS0m30n3/youtube-dl-gui#263]
Hello .
I updated the YouTubeDL from Webupd8 PPA and i tried to open the GUI Version but no response then i used the terminal to run it with this command : youtube-dl-gui
after writing the command i hit Enter i got this python error : 

Traceback (most recent call last):
File "/usr/bin/youtube-dl-gui", line 35, in
import youtube_dl_gui
File "/usr/lib/python2.7/dist-packages/youtube_dl_gui/init.py", line 76, in
from .mainframe import MainFrame
File "/usr/lib/python2.7/dist-packages/youtube_dl_gui/mainframe.py", line 19, in
from .optionsframe import (
File "/usr/lib/python2.7/dist-packages/youtube_dl_gui/optionsframe.py", line 12, in
import wx.combo
ImportError: No module named combo

how can i fix it ? .

Linux Mint 18.3
python-wxgtk3.0 is already the newest version (3.0.2.0+dfsg-1build1).
the combo file path : /usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/combo.py

@MrS0m30n3 i think this is large enough.

**Comment by MrS0m30n3** [comment]
1. Open a python interpreter
2. Type import wx
3. wx.version()
4. import wx.combo

If step 3 does not report version 3.0.2.0 uninstall ubuntu and use windows from now on.

### Note
You issue is still invalid (for many reasons) i just made an attempt here to help you.

**Comment by BlackHacker12** [comment]
@MrS0m30n3 it didn't help sorry for bothering all i did is reinstall the YouTubeDL GUI Package and the Requirements and now every things work,.

Thank you for time and attempt to help me.

**Comment by ajsnyde** [comment]
I resolved this by installing wx through sourceforge - it seems that the pre-4.0 versions aren't listed on the main page or the dependency installer within pycharm.
https://sourceforge.net/projects/wxpython/files/wxPython/

**Comment by NightMachinary** [comment]
@MrS0m30n3 I get '4.0.1 osx-cocoa (phoenix)'.

**Comment by MrS0m30n3** [comment]
@NightMachinary [Windows](https://en.wikipedia.org/wiki/Microsoft_Windows) is for you then!

**Comment by NightMachinary** [comment]
@MrS0m30n3 Fuck off. You’re yet another ape suffering from the knowledge curse, and your software documentation sucks ass. I would have put the a link to “How to migrate to an Africa Savanna” here, if I wasn’t sure you wouldn’t even survive there.

**Comment by MrS0m30n3** [comment]
>Fuck off. You’re yet another ape suffering from the knowledge curse

Thank you so much for your kind words!

>and your software documentation sucks ass

Yes, it does! Please, help as improve it!

>I would have put a link to “How to migrate to an African Savanna”

African Savanna is a nice place!!! :heart:

**Comment by MrS0m30n3** [comment]
Jokes aside, for any serious person that reads this.

Under the **Requirements** section in the README.md file (and in many more places), it clearly states that you need **wxPython 3<--**, not 1, not 2, not 4, but 3. It's as simple as that.

At the end of the day i can't help you if you don't even know what software you have installed on your computer.

Sorry!

**Comment by NightMachinary** [comment]
Fair enough 💖☘️

**Comment by tjkluska** [comment]
Besides, very useful piece of software.
Thanks MrS0m30n3 !

**Comment by zhuyinheng** [comment]
try `conda install wxpython=3.0` instead
