### ISSUE TITLE
Install error wx.combo

### ISSUE THREAD

**Issue by jkohlin** [MrS0m30n3/youtube-dl-gui#267]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [ ] **I think** my problem is **NOT** with **youtube-dl**
  - [ ] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

Please remove any sections between (---) if they are not related to your issue

---

#### What operating system do you use ?
macos
#### List of actions to perform to reproduce the problem:

  1. pip install youtube-dlg
  
#### What is the expected behaviour ?
Install wo problem
#### What happens instead ?
following error: 
        import wx.combo
    ImportError: No module named combo
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-SIHT_O/youtube-dlg/

---

---

Unable to install the application. I installed all the required software before, but get this message. I guess wx wasn't installed correctly, but don't know how/why?

**Comment by ferdiptsy** [comment]
Same error here, 
No module named combo.
Also I'm stupid and don't know if I'm supposed to link gettext or whatever that means :(

**Comment by AbercrombieChang** [comment]
Same problem too, I have to build from the source code eventually. Here is my actions and hope it will help.

- Install dependencies
```
$ brew install python2
$ brew install wxpython
$ brew install gettext
$ pip2 install twodict
```

- Link wx to site-packages of python installed by homebrew. I get "No module named wx" error without this step.
```
$ cd /usr/local/opt/python2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
$ ln -s /usr/local/opt/wxpython/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx wx
```

- Add path of msgfmt to PATH temporarily.
```
$ export PATH=/usr/local/opt/gettext/bin:$PATH
```

- Install youtube-dl-gui whose source code is in Downloads folder
```
$ cd ~/Downloads/youtube-dl-gui-0.4
$ python2 setup.py install
```

- Run youtube-dl-gui
```
$ youtube-dl-gui
```

**Comment by MrS0m30n3** [comment]
Seems the same issue with https://github.com/MrS0m30n3/youtube-dl-gui/issues/263.

**Comment by enbandari** [comment]
@AbercrombieChang You are great!

**Comment by ajsnyde** [comment]
I resolved this by installing wx through sourceforge - it seems that the pre-4.0 versions aren't listed on the main page or the dependency installer within pycharm.
https://sourceforge.net/projects/wxpython/files/wxPython/

**Comment by NightMachinary** [comment]
@ajsnyde How do you install that package? On mac, it needs MacPython and doesn't install on my Conda Python 2. :\

**Comment by WeirdSeven** [comment]
@AbercrombieChang Thanks for the solution! Actually, it looks like you can install youtube-dlg via simply pip after linking wx and adding PATH.  Do`pip2 install youtube-dlg`.
