### ISSUE TITLE
Drag and drop support

### ISSUE THREAD

**Issue by terjelm** [MrS0m30n3/youtube-dl-gui#268]
### Before going further

  - [X] **I think** my problem is **NOT** with **youtube-dl**
  - [X] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [X] **I assure** that i am using the latest version of **youtube-dl**
  - [X] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [X] I've read the FAQs file

### What is the purpose of your *issue*?

- [ ] Bug report
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Feature request (request for a new functionality)

Please make sure that the requested feature is **NOT** already in the [TODO](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/TODO) list

- [X] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list

#### What operating system do you use ?

Windows

---

# Drag-and-drop support
It would be useful if the program had support for drag and drop. That way we could just drag links to episodes from a browser and have them inserted. A bit faster and more user friendly than the old -school copy-paste of links.
Either the whole window could have a drag-and-drop handler or just the URL-input frame.

PS: Thanks for a very nice program, very much appreciated.

**Comment by nodiscc** [comment]
Check https://github.com/MrS0m30n3/youtube-dl-gui/issues/19
