### ISSUE TITLE
Connection to a German IP

### ISSUE THREAD

**Issue by anewuser** [MrS0m30n3/youtube-dl-gui#27]
Why did Youtube-dlG try to connect to 95.143.172.170 the first time I opened it? The "Auto update" option is disabled by default in the options.

**Comment by nodiscc** [comment]
@anewuser What OS? What network monitoring tool did you use? What is the transmitted data?

**Comment by anewuser** [comment]
@nodiscc Comodo Firewall on Windows 8.1.  I've downloaded the official build from Google Code (the link on the project Github page).

That's apparently the address used to check for updates, but I found it strange that it tried to connect automatically to it on the first-run, since the auto-update option is disabled by default.

**Comment by MrS0m30n3** [comment]
Hi, @anewuser thanks for using youtube-dlg.

The 95.143.172.170 (yt-dl.org) is the place from which youtube-dlg downloads the latest youtube-dl binary (See https://yt-dl.org/latest/).

You probably downloaded the 0.3.5.b version. This is the source tree for the 0.3.5.b version: https://github.com/MrS0m30n3/youtube-dl-gui/tree/bcf432be7894c934d853ae94bb83c76b4a071265/youtube_dl_gui

As you can see on YoutubeDLGUI.py module, (See line:125) youtube-dlg calls the check_if_youtube_dl_exist() method even if auto-update option is disabled which checks if the youtube-dl binary exists. If not it auto downloads youtube-dl binary. So, thats why you see this IP.

In the current version, downloadmanager.py module checks to make sure youtube-dl binary exists before it starts the download process. (See line:91 check_youtubedl() method).

**Comment by anewuser** [comment]
@MrS0m30n3 I see. Thank you for making a GUI for this great program. :)
