### ISSUE TITLE
"Last modified" date value

### ISSUE THREAD

**Issue by thatguy344** [MrS0m30n3/youtube-dl-gui#273]
Hello,

The "last modified" date value is always automatically being taken from the original file and then added to the meta data of the mp4's which youtube-dl-gui downloads, is this intentional and if so do you plan on making this import of the original file's meta data an optional feature in the future aswell? The thing is that this makes browsing for the files in windows explorer quite bothersome (since i have it set to "show last modified files first" by default) and right now i'm having to resort to manually changing the mp4's file meta data after downloading every time because of this... I really like your frontend btw!

- Regards

**Comment by nodiscc** [comment]
@thatguy344 Setting the file modification time is part of how [youtube-dl](https://github.com/rg3/youtube-dl) handles `--add-metadata`. To prevent touching the file modification time you can add `--no-mtime` to the command line options (see https://github.com/rg3/youtube-dl#filesystem-options).

**Comment by MrS0m30n3** [comment]
There is also the option "No mtime" under the Options>Extra tab.
