### ISSUE TITLE
Download not working and log is blank.

### ISSUE THREAD

**Issue by CDLuminate** [MrS0m30n3/youtube-dl-gui#275]
I cannot download any video from https://www.bilibili.com/ with youtube-dlg. When I click the "Start" button, the downloading process will end up immediately and nothing is downloaded. But the commands obtained by right-clicking the items in list is working when I copied them to terminal.

Apart from that, the log is blank, even if I enabled "debug youtube-dl", disabled "ignore errors".

What should I do?

**Comment by nodiscc** [comment]
You didn't include the log or any of the requested info. Please reopen an issue with the relevant information included (don't delete the template).
