### ISSUE TITLE
How do I force a specific format to be downloaded e.g. webm

### ISSUE THREAD

**Issue by pooky2483** [MrS0m30n3/youtube-dl-gui#278]
- [X] **I think** my problem is **NOT** with **youtube-dl**
  - [X] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [X] **I assure** that i am using the latest version of **youtube-dl**
  - [X] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [X] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [X] Other

#### What operating system do you use ?
Kubuntu 16.04/14.04
#### List of actions to perform to reproduce the problem:

  1. Set filename format to CUSTOM
  2. Video format to WEBM
  3. Audio format blank, I've even tried setting it to OPUS
  4. Setting next to ADD, I change to WEBM
  5. Edit save path to where I require them to be saved
  6. Copy list of youtube addresses of channels
  7. Click on ADD
  8. Click on the 'cloud' to start the downloads
  
  
#### What is the expected behaviour ?
I expect the downloads to all be webm format
#### What happens instead ?
Some formats are mp4 or other

Issue is that formats other than WEBM are downloaded
I have the same settings on a laptop running Kubuntu 16.04 and the latest versions of youtube-dl & youtube-dlg and that one downloads the requested format no trouble, the one I'm having problems with is on a virtualbox copy of Kubuntu 16.04 inside a master OS of Kubuntu 14.04

**Comment by nodiscc** [comment]
@pooky2483 can you try to reproduce the problem again, and send the logs? (as requested in the template)
