### ISSUE TITLE
[Youtube] Unable to extract video URL. Using youtube portable 0.4

### ISSUE THREAD

**Issue by ajtpak** [MrS0m30n3/youtube-dl-gui#281]
Hello, I have read the read me and followed everything, but I'm constantly having this error when I check the logs: "WARNING: Falling back on generic information extractor.
ERROR: Unable to extract video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: Requested formats are incompatible for merge and will be merged into mkv." 

I have everything set to the defaults. I'm on windows 10

**Comment by nodiscc** [comment]
Please reopen an issue while keeping the [issue template](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/.github/ISSUE_TEMPLATE.md) and filling in the requested infomation.
