### ISSUE TITLE
is not a valid Win32 application [Solution Found]

### ISSUE THREAD

**Issue by christophered** [MrS0m30n3/youtube-dl-gui#286]
- [ x] **I think** my problem is **NOT** with **youtube-dl**
  - [x ] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x ] **I assure** that i am using the latest version of **youtube-dl**
  - [x ] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [x ] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x ] Bug report

### Bug report

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "youtube_dl_gui\downloadmanager.pyc", line 599, in run
  File "youtube_dl_gui\downloaders.pyc", line 162, in download
  File "youtube_dl_gui\downloaders.pyc", line 337, in _create_process
  File "subprocess.pyc", line 390, in __init__
  File "subprocess.pyc", line 640, in _execute_child
WindowsError: [Error 193] %1 is not a valid Win32 application
```

#### What operating system do you use ?
Windows 8 64bit, I have used both the portable version and the setup version, both have failed, I even used the lated youtube-dl
#### List of actions to perform to reproduce the problem:

  1. ran youtube-dl-gui, pasted the youtube url, chosen mp4 format
  2. added the link
  3. clicked start
  
#### What is the expected behaviour ?
To download
#### What happens instead ?
stuck in Queued 0%

---

**Comment by christophered** [comment]
@MrS0m30n3 I found the solution! When you run Youtube-DLG it creates a folder C:\Users\ ``[YOUR USERNAME]`` \AppData\Roaming\youtube-dlg
The problem was that this created folder contained `youtube-dl.exe` with a filesize of `0 bytes`, so I corrected this issue by copying `youtube-dl.exe` to that folder.

**Comment by christophered** [comment]
@MrS0m30n3 it seems that Youtube-DLG doesn't look for `youtube-dl.exe` in it's current folder, instead it looks for `youtube-dl.exe` in the `\AppData\Roaming\youtube-dlg`

**Comment by TTMARSH** [comment]
good.
