### ISSUE TITLE
[QUESTION] How do I create a download log to avoid double downloads after deleting previous files from the download folder?

### ISSUE THREAD

**Issue by samsepiol59** [MrS0m30n3/youtube-dl-gui#287]
Hi there,

basically what I'm doing is using youtube-dlg on **Ubuntu 16.04** to download all videos from a certain channel and then upload said videos to a cloud service, as a way or archiving them. After uploading the videos, I delete them from my disk.

What I'd love to do is being able to create some kind of text archive (or whatever works), so that I don't re-download files I've already downloaded the next time I try to download videos from the same channel - basically, only download the videos released between the current download and the previous one! Is it possible?!

PS I've already got this in the command line arguments in the options
`-f bestvideo[ext=mp4][width<=1920][heigth<=1080]+bestaudio --merge-output-format mkv`

**Comment by nodiscc** [comment]
Hi @samsepiol59 please check https://github.com/MrS0m30n3/youtube-dl-gui/issues/194 where I suggested using the `--download-archive` option from the command-line sttings under the advanced settings tab. Basically you could define a central `archive.txt` file whih references all videos you downloaded. Videos/IDs already present in this file would not be re-downloaded in future attempts.

Let me know if this answers your question.

**Comment by samsepiol59** [comment]
Thanks!! so I should just add the `--download-archive archive.txt`after mkv and that would do it?!
