### ISSUE TITLE
youtube-dl-gui doesn't work properly

### ISSUE THREAD

**Issue by IoanPaleru** [MrS0m30n3/youtube-dl-gui#288]
Youtube-dl-gui is a great program because it's easy to use, but it didn't download any audio with a 720p video from youtube. Do you know how to fix that? Thanks.

**Comment by MrS0m30n3** [comment]
@IoanPaleru [This](https://www.youtube.com/watch?v=gFm3brOdxcw) is for a Mac but it should work on any computer.
