### ISSUE TITLE
Adresses should automatically enter a new row after pasting

### ISSUE THREAD

**Issue by ThebestwaytodesignJoinGitHub** [MrS0m30n3/youtube-dl-gui#29]
Otherwise the next pasted address is trailed to the previous

**Comment by MrS0m30n3** [comment]
With the current code state this is not possible (as far as i can think of right now) without keeping the insert state in a third variable and i am not going to edit the EVT_TEXT handler, so just hit Enter.

This behavior will change on the new GUI where you will have a single line textctrl and when you paste the url the textctrl will autoclear itself to be ready for the next url.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
Thanks, works when pasting via context menu, but not when pasting selected text with middle mouse button, which is a linux feature

**Comment by MrS0m30n3** [comment]
@ThebestwaytodesignJoinGitHub 

I am closing this issue. 
Now the middle mouse click automatically adds a newline when you paste urls.

Give it a try and feel free to re-open the issue if you have any problems.
