### ISSUE TITLE
Request to join Transifex team

### ISSUE THREAD

**Issue by ghost** [MrS0m30n3/youtube-dl-gui#293]
Hi, I have sent a request to join the translation team for a month after successfully requesting language, but my account still isn't in any team. Please let me know if you haven't received any request. Thanks! @MrS0m30n3 @nodiscc

**Comment by nodiscc** [comment]
Strange, I see your request in the Transifex log (2 months ago)

>The Chinese (China) language was requested for the youtube-dl-gui project by Abercrombie Chang 

but can not act on it (no approve request button). Can you try again?

**Comment by AbercrombieChang** [comment]
My language request have been accepted but request to join the team haven't received any response. Transifex ask me to select available language when submitting application and I don't have a Chinese (China) option now, which I selected 2 months ago. I have sent an application again with Chinese (Taiwan).
