### ISSUE TITLE
Question:  why proxy string appears commented in Youtube-dl config

### ISSUE THREAD

**Issue by bendover22** [MrS0m30n3/youtube-dl-gui#294]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [x ] **I think** my problem is **NOT** with **youtube-dl**
  - [x ] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x ] **I assure** that i am using the latest version of **youtube-dl**
  - [x ] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [x ] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

```

```

#### What operating system do you use ?
mint 18.1

#### List of actions to perform to reproduce the problem:

  1. ..general question - update youtube-dl, then run yt-dlg & download files.

  2. ..Compare youtube-dl's config vs. youtube-dlg's settings.json files
  3. ..
  
Is it normal for the "run this proxy" [the actual proxy address] in youtube-dl's config file to be commented out: 

```
# Use this proxy
#--proxy socks5://127.0.0.1:xxxx/
```

 , but... in youtube-dlg settings.json the proxy looks OK (to me):
```
"proxy": "socks5://127.0.0.1:xxxx/"
```

** When using youtube-dlg, why are  *all* settings stored in the yt-dl config file commented out?  These are settings I changed in yt-dlg.

An unrelated question.  
I updated yt-dl several days ago thru mint update manager (the PPA for youtube-dl is in the software sources).  I checked its version today in terminal - typing at the prompt w/o entering a specific path:

```
$ youtube-dl --version
```

it returned "2018.03.03" - several times, but Synaptic shows v 2018.04.03 installed  at /usr/bin.  Which is an 87 byte file, but has modified date 2018.04.03.  

If I enter the path /usr/bin & then the version query, it shows the correct version.  

There's another "youtube-dl" installed at /usr/local/bin - STILL showing modified date 2018.03.02.  Apparently that's the file terminal queries to get a version, but Synaptic knows the later ver is installed?  

I ran yt-dlg after updating yt-dl & also rebooted the machine.  So I don't know why the old version is shown in terminal?
 
In the future, I'd like to be able to confirm youtube-dl version easier than opening Synaptic update mgr or remembering the full  path to the *latest* version file, to enter in terminal .
Is there anyway Yt-dlg could show the installed yt-dl version, like in "about?"  Since if using yt-dlg, no one interacts w/ the yt-dl files.  I'm not sure if that's a feature request.

---

### Feature request (request for a new functionality)

Please make sure that the requested feature is **NOT** already in the [TODO](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/TODO) list

- [ ] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list

#### What operating system do you use ?

---

**Comment by nodiscc** [comment]
Output of  `which youtube-dl` ?

**Comment by bendover22** [comment]
Sorry for late reply.
Exactly what do you mean, "Output of which youtube-dl ?"

If you meant "what's the output of the command, 'which youtube-dl' ", then it's:
$ which youtube-dl
/usr/local/bin/youtube-dl
