### ISSUE TITLE
[Feature request] Add a delay allowing cancellation before shutdown after completion.

### ISSUE THREAD

**Issue by sipertruk** [MrS0m30n3/youtube-dl-gui#295]
### What is the purpose of your *issue*?

- [ ] Bug report
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Feature request (request for a new functionality)

Please make sure that the requested feature is **NOT** already in the [TODO](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/TODO) list

- [x] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list

---

Add a delay before shutdown after completion with a way to cancel it. Optionally something to make this enabled option obvious on the main window.

If you pop casually youtube-dl-gui you may not remember that the "Shutdown on download completion" is enabled. The consequence is that you'll helplessly watch your computer go to shutdown immediately after completion and this happening on the wrong machine can literally ruin your day, make you hate yourself and your surroundings, even the whole world.

**Comment by MrS0m30n3** [comment]
This is already available: [mainframe.py: 891](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/youtube_dl_gui/mainframe.py#L891)
