### ISSUE TITLE
Question: does youtube-dlg "update" need root permission; does it install the latest version?

### ISSUE THREAD

**Issue by bendover22** [MrS0m30n3/youtube-dl-gui#296]
### WARNING
All invalid issues will be rejected!!

  - [x ] **I think** my problem is **NOT** with **youtube-dl**
  - [x ] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x ] **I assure** that i am using the latest version of **youtube-dl**
  - [x ] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [x ] I've read the FAQs file  (yes, several times)

### What is the purpose of your *issue*?

- [x] Bug report
- [x ] Feature request (request for a new functionality)
- [x ] Question
- [x] Other

I found no real instructions or FAQ - here or in  w/ real details on using yt-dlg to update yt-dl.  I don't know if this is a bug or operator (me) error or neither.
  
The GUI leads you to think "update" under options will run under a user account & does show something like "downloading the latest..."  on yt-dlg's screen.
A couple days ago, I couldn't get yt-dlg to update yt-dl at all (a newer version was available).  No messages, no log output about failed to update.
I don't know if this is a yt-dlg or yt-dl issue (guessing -dlg).

I only used yt-dlg a few mo.  Before, I mostly updated yt-dl  via a PPA in the Mint repo.

There's no log entries about failed update (logging enabled), but that might only come from yt-dl.  You'd think yt-dl would log something if it just updated.

After it finished & restarting yt-dlg, checking the youtube-dl --version still showed the same version as before, though the *modified date* of yt-dl file had changed.  I tried updating couple more times via the GUI.  The yt-dl installed version didn't change.

A few minutes later, I updated youtube-dl in terminal using sudo, which worked fine.
Then checking the version showed the latest yt-dl - at that time - was installed.

Today, saw a new 2018.04.16 version was released, so I tried updating again from the GUI.  It said "downloading the latest youtube-dl" or similar. 
 It finished -successful. No mention of the version & nothing in the log.

Now the version check shows 2018.04.09 is installed.  That's checking both /usr/bin & /usr/local/bin.
But  the version on https://rg3.github.io/youtube-dl/ is 2018.04.16, not 04.09.
So I don't know what's going on.

I don't know where youtube-dlg D/L's yt-dl updates from.
Is the source yt-dlg fetches from a bit later getting the newest releases shown on  https://rg3.github.io/youtube-dl/?

### Bug report
Not sure if there is one - sorry.

#### What operating system do you use ?
Mint 18.1, updated except for kernel.
 

### Feature request (request for a new functionality)
Regardless, I'd suggest that youtube-dlg show the currently installed yt-dl version -  somewhere prominent - or near the menu option that probably *should* say, "Update youtube-dl" instead of "update". :)
To make it easier to tell if it actually updated yt-dl & to what version.

**Comment by MrS0m30n3** [comment]
That's already in the TODO list.
