### ISSUE TITLE
Window could remember its size

### ISSUE THREAD

**Issue by ThebestwaytodesignJoinGitHub** [MrS0m30n3/youtube-dl-gui#30]
and the margin between the three big buttons could shrink when decreasing window size

**Comment by MrS0m30n3** [comment]
I don't really like storing the window size in the settings. 
Anyway, now both the main and the options windows should be able to remember their sizes.
Also, the spaces between the buttons are now resizable.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
Cool, thank you!
