### ISSUE TITLE
Pasting anything in the URL box results in these weird Chinese characters

### ISSUE THREAD

**Issue by NightMachinary** [MrS0m30n3/youtube-dl-gui#300]
- [ x] **I think** my problem is **NOT** with **youtube-dl**
  - [ x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [ x] **I assure** that i am using the latest version of **youtube-dl**
  - [ x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [ x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x ] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### What operating system do you use ?
macOS

#### List of actions to perform to reproduce the problem:

Pasting anything in the URL box results in these weird Chinese characters:
![image](https://user-images.githubusercontent.com/36224762/39245921-514631dc-48aa-11e8-9127-1a4e6a5f5d6a.png)

**Comment by MrS0m30n3** [comment]
That's completely normal!
