### ISSUE TITLE
[Question] Virustotal: CMC  Trojan.Win32.Nimnul!O

### ISSUE THREAD

**Issue by Maveee** [MrS0m30n3/youtube-dl-gui#305]
I'm sure it's a false positive, but can anyone confirm? Or ask Virustotal to re-analyze the file?

https://www.virustotal.com/#/file/230690b25bd1c5bf7e396f905fa51c6760af93ad24a50ce2fb0eee5ffa9d7068/detection

https://i.imgur.com/fEsrcxY.png

**Comment by nodiscc** [comment]
False positives on the portable and setup Windows releases from https://github.com/MrS0m30n3/youtube-dl-gui/releases

https://www.virustotal.com/#/file/230690b25bd1c5bf7e396f905fa51c6760af93ad24a50ce2fb0eee5ffa9d7068/detection
https://www.virustotal.com/#/file/5642d1ae53a6dba7a084d997ca76305e40b897e90b1f7a932e08d980ea1a2ba0/detection

**Comment by nodiscc** [comment]
Files are now reported as `Clean` by VirusTotal.
