### ISSUE TITLE
Do I have to maintain a git clone of youtube-dl for latest version?

### ISSUE THREAD

**Issue by ThebestwaytodesignJoinGitHub** [MrS0m30n3/youtube-dl-gui#31]
Or does youtube-dl-gui download the most recent version?

**Comment by MrS0m30n3** [comment]
Hi @ThebestwaytodesignJoinGitHub 

youtube-dl-gui uses the latest binary from https://yt-dl.org/latest/.

You can also read this issue https://github.com/MrS0m30n3/youtube-dl-gui/issues/28
which refers to the gap between releases.

Let me point that if for some reason you want to use your own repository you need to edit the code at https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/youtube_dl_gui/updatemanager.py#L48 to point to your own binary or you can build the binary locally and change the 'youtubedl-path' unders settings.json file to point to your own binary.
