### ISSUE TITLE
Behavior change request : don't steal focus from full screen programs

### ISSUE THREAD

**Issue by RicoLeNecro** [MrS0m30n3/youtube-dl-gui#315]
- [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?
- [ ] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

#### What operating system do you use ?
Windows 7 Pro, x64

#### List of actions to perform to reproduce the problem:
  1. Start downloading one or more videos
  2. While the video(s) is/are still downloading, open another program (such as a video game) in full screen mode.
  3. Wait (or play your game) until all downloads have completed
  
#### What is the expected behaviour ?
Whichever program the user launched in full screen mode should stay in full screen mode and not have the focus "stolen" from it by Youtube-DLG's windows.

#### What happens instead ?
The full screen program gets minimized and the focus is stolen by Youtube-DLG's "Info" pop-up, stating "Downloads completed"

**Comment by MrS0m30n3** [comment]
You can turn-off the "Downloads completed" message in your Options.
