### ISSUE TITLE
How to remove youtube-dlg

### ISSUE THREAD

**Issue by blueray453** [MrS0m30n3/youtube-dl-gui#316]
I am using Ubuntu Mate.

I downloaded `youtube-dlg_0.4-1~webupd8~zesty4_all.deb` from http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/pool/main/y/youtube-dlg/

Then double clicked the file and thus install it.

When I needed to remove it, I opened synaptic and remove the `youtube-dlg` package.

Still some of the element is remaining and it is conflicting with my `youtube-dl` program which I installed using `apt-get install youtube-dl`

How to completely remove it?

**Comment by nodiscc** [comment]
@blueray453 what is the output of `which youtube-dl` ?

**Comment by MrS0m30n3** [comment]
>Still some of the element is remaining and it is conflicting with my youtube-dl
What elements conflict with youtube-dl?
