### ISSUE TITLE
uktv play  not working 

### ISSUE THREAD

**Issue by 5kedone** [MrS0m30n3/youtube-dl-gui#317]
---

### What is the purpose of your *issue*?

- [x] Bug report
---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **youtube-dl-gui**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

```
[05/25/18 09:39:47] WARNING: Falling back on generic information extractor.
[05/25/18 09:39:47] ERROR: Unsupported URL: https://uktvplay.uktv.co.uk/shows/the-horne-section/watch-online/
```

#### What operating system do you use ?
windows 10
#### List of actions to perform to reproduce the problem:

  1. ..paste in link in error log selct add
  2. ..press download 
  3. ..EERRROORRR
  
#### What is the expected behaviour ?
it to download the show
#### What happens instead ?
its failed to download

---

### Feature request (request for a new functionality)

Please make sure that the requested feature is **NOT** already in the [TODO](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/TODO) list

- [x] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list

#### What operating system do you use ?

---

**Comment by nodiscc** [comment]
@5kedone this is a problem with [youtube-dl](https://github.com/rg3/youtube-dl) which is what youtube-dl-gui uses for the actual download, it seems to have been reported [here](https://github.com/rg3/youtube-dl/issues/16294). I encourage you to follow this ticket instead.
