### ISSUE TITLE
[Debian][Gnome 3.28.2] Application icons missing

### ISSUE THREAD

**Issue by x2k13** [MrS0m30n3/youtube-dl-gui#319]
- [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Bug report

---

### Bug report

After installing youtube-dlg_0.4-1_webupd8_zesty4_all.deb, the only application icon that's appearing is the one in the overview (Windows / Super key). All the others are missing.

#### What operating system do you use ?

Linux 4.16.0-1-amd64 #1 SMP Debian 4.16.5-1 (2018-04-29) x86_64 GNU/Linux
Gnome 3.28.2

#### List of actions to perform to reproduce the problem:

  1. Install youtube-dlg*.deb (doesn't matter if via <apt install $path> or <dpkg -i>)
  2. Hit Windows / Super key on your keyboard
  3. Type "you", see the already marked application icon, hit enter and start YouTube DL GUI
  
#### What is the expected behaviour ?

After YouTube DL GUI ist started, the application icon should show up on the dock, the application's menu on the top-left corner of the screen and on the ALT+TAB switch panel.

#### What happens instead ?

After YouTube DL GUI ist started, the application icon doesn't show up on the dock, the application's menu on the top-left corner of the screen and on the ALT+TAB switch panel. Instead the following icon is displayed:

![scrn](https://user-images.githubusercontent.com/13673423/40791454-d1cc8edc-64f7-11e8-9283-85e52896a91b.png)

The necessarily needed iconset apparently is installed correctly in the systems default icons/pixmap locations:

![scrn-2](https://user-images.githubusercontent.com/13673423/40791835-b4795bb6-64f8-11e8-8d49-117611408618.png)

**Comment by MrS0m30n3** [comment]
You should contact the maintainer of the DEB package.
