### ISSUE TITLE
Please add user & password options.

### ISSUE THREAD

**Issue by BI7PRK** [MrS0m30n3/youtube-dl-gui#320]
great youtube-dl-gui !
but some websites need to authentication of user.
[authentication-options](https://github.com/rg3/youtube-dl#authentication-options)
please add user & password options in UI.
thanks so much.

**Comment by nodiscc** [comment]
Authentication options are already available in the `Options > Advanced` tab.

![adv](https://user-images.githubusercontent.com/3950390/42422709-9f865a04-82eb-11e8-8c08-6e664c39702d.png)
