### ISSUE TITLE
File dates

### ISSUE THREAD

**Issue by cantbothertoshave** [MrS0m30n3/youtube-dl-gui#321]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

### Feature request (request for a new functionality)

Please make sure that the requested feature is **NOT** already in the [TODO](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/TODO) list

- [x] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list

#### What operating system do you use ?
Win7 32

---

Option to **not screw with the file dates** of downloads.
I have looked through the options and didn't see that, so I assume there is no such option.
But youtube-dl command line util apparently provides it: --no-mtime
See here, post by phihag: https://github.com/rg3/youtube-dl/issues/4667

In its current state, files downloaded with youtube-dlG have the file date of when it was uploaded onto youtube, rather than when downloaded by the user. I imagine I'm far from the only one who does not care the least bit about the former, but a lot about the latter. It's plain annoying to not be able to use "sort by file date" in the file browser to see what you downloaded most recently.

**Comment by MrS0m30n3** [comment]
Options>Extra "No mtime" option.
