### ISSUE TITLE
ABC iView no longer supported

### ISSUE THREAD

**Issue by freddyzdead** [MrS0m30n3/youtube-dl-gui#324]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [ ] **I think** my problem is **NOT** with **youtube-dl**
  - [x ] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [ x] **I assure** that i am using the latest version of **youtube-dl**
  - [ ] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [x ] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [x ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### What operating system do you use ?
Windows 8.1 Pro
#### List of actions to perform to reproduce the problem:

  1. .. Copy link of desired content
  2. .. Paste into Youtube-DLG top window
  3. .. Download
  
#### What is the expected behaviour ?
Content downloads
#### What happens instead ?
ERROR
The error is because ABC has completely changed their mode of operation and now opens a new window with a player.  There is no longer a direct link to the content.  This is not Youtube-DL's fault, but the functionality is broken nonetheless.

---

### Feature request (request for a new functionality)
Not looking for new functionality as such... Need to surmount this latest hurdle.

Please make sure that the requested feature is **NOT** already in the [TODO](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/TODO) list

- [x ] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list

#### What operating system do you use ?
I already said, Windows 8.1 Pro

---

The issue is obvious.  Last week I was able to happily use Youtube-DLG to download any content from 
Australian ABC iView.  This week, it is all different, they have changed to a completely different method where a player opens in a new window.  The URL for the actual video clip is no longer available.  Hopefully there is some way around this.  I don't know why they are so jealous about their content since it goes out over the air for free anyway.

**Comment by Modelmat** [comment]
This is a youtube-dl issue, update your version of youtube-dl (settings > update) and it is fixed.

**Comment by freddyzdead** [comment]
Hi MrS0m30n3

 

Thank you for the reply.

 

I updated the program as you suggested, but there was no change.  The problem, I think, is that the ABC has introduced DRM in the form of an embedded player.  There is no longer a link directy to the content, else it is encrypted.  Youtube-dl still gives up and reports an error.  Is there any way around this?  I have to resort to using screen capture, which works, but not very well.

 

Thanks for all your efforts.

 

-freddy

 

 

Sent: Saturday, June 23, 2018 at 5:29 PM

**Comment by Modelmat** [comment]
It is possible, you need to click the share button - 
![image](https://user-images.githubusercontent.com/25718989/42364557-e2de0544-813e-11e8-8225-0a5f25b21016.png) 
then click copy link and it will give you the link
![image](https://user-images.githubusercontent.com/25718989/42364575-ee5ae3ba-813e-11e8-8c8f-4f50a2bf97a5.png)

**Comment by nodiscc** [comment]
@Modelmat is your problem fixed by using this link?

**Comment by Modelmat** [comment]
Yes it is (it's not my problem)
