### ISSUE TITLE
Replace "uploader" with "artist" in the metadata(?)

### ISSUE THREAD

**Issue by Raipperi** [MrS0m30n3/youtube-dl-gui#328]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

---

---

Hi

Im a complete noob at this so i need help. Ive been using youtube dl for a while now and it has always annoyed me that when i download a song from youtube and open it in foobar, the "artist" is somehow the uploader of the youtube video and not the actual artist in the video title. 

I have tried searching github and google for an answer but im still lost. Is there a way i can replace the "uploader" with the "artist" in the metadata(?) so it shows in foobar or any other player?

**Comment by nodiscc** [comment]
@Raipperi Have a look at https://github.com/rg3/youtube-dl#post-processing-options `--metadata-from-title`

**Comment by MrS0m30n3** [comment]
That's an issue with youtube-dl, not youtube-dl-gui.
