### ISSUE TITLE
Hallo,can you add a Simplified Chinese translation file？I made one. 

### ISSUE THREAD

**Issue by lvzhenbo** [MrS0m30n3/youtube-dl-gui#329]
Hallo,can you add a Simplified Chinese translation file？I made one. 
https://github.com/lvzhenbo/youtube-dl-gui-Simplified-Chinese-translation-file

**Comment by MrS0m30n3** [comment]
Read the localization guide from [here](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/localization_howto.md) please.
