### ISSUE TITLE
Need feature embed orginal creation date after convertion 

### ISSUE THREAD

**Issue by raj6996** [MrS0m30n3/youtube-dl-gui#330]
Thanks for awesome gui both of you!
If I set default, it download max resolution of yotuube files and those are .mkv file.
I like youtube-dl for the feature it don't modify meta data of date, I can't fine on other downloaders.
Now, I need to convert mkv to mp4, cause opus plugin not supported on vegus pro, so I need to convert them with ffmpeg or other converters. but problem it that it modify date, may be i put wrong section, any thing to converter option that don't modify date and keep original date of files. sorry for weak english.

**Comment by nodiscc** [comment]
>  I need to convert them with ffmpeg or other converters
> but problem it that it modify date

Have a look at the ffmpeg documentation https://ffmpeg.org/ffmpeg.html and https://ffmpeg.org/ffmpeg.html#toc-See-Also, or there are graphical interfaces for ffmpeg https://qwinff.github.io/ that may do what you need. But you probably need to write a custom ffmpeg command-line.

As it's an ffmpeg question and not a youtube-dlg question we can not help you much. Good luck.

**Comment by MrS0m30n3** [comment]
Options>Extra tab. Check the "No mtime" option.
