### ISSUE TITLE
Download from Blob URLs

### ISSUE THREAD

**Issue by AnotherFCCer** [MrS0m30n3/youtube-dl-gui#335]
Hello,

Thanks very much for this; just a Question or Feature Request: Is it possible to download from Blob URLs?

**Comment by nodiscc** [comment]
No, see

https://superuser.com/questions/948738/what-is-the-blobhttp-prefix-and-where-can-i-learn-more-about-this

> Blob URI/URL was created by JavaScript, refers to data that your browser currently has in memory (only in current page)

https://stackoverflow.com/questions/30864573/what-is-a-blob-url-and-why-it-is-used

> Blob URLs can only be generated internally by the browser
> These URLs can only be used locally in the single instance of the browser and in the same session (ie. the life of the page/document).

https://developer.mozilla.org/en-US/docs/Web/API/Blob
