### ISSUE TITLE
1080p YouTube download not working (requested format not available, even though it is)

### ISSUE THREAD

**Issue by ipkpjersi** [MrS0m30n3/youtube-dl-gui#336]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **youtube-dl-gui**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

```
[Wed Sep 12 22:40:34 2018] ERROR: requested format not available
```

#### What operating system do you use ?
Ubuntu 16.04

#### List of actions to perform to reproduce the problem:

  1. Try to download this video: https://www.youtube.com/watch?v=-KGnRe1f2DA
  2. Either leave it default manually select 1080p
  3. Download the video.
  
#### What is the expected behaviour ?
You should get 1080p when leaving it default or manually selecting 1080p.

#### What happens instead ?
Instead you get 720p default or an error when downloading 1080p.

**Comment by ipkpjersi** [comment]
Okay I feel really silly but I literally just fixed it. I de-selected "prefer native HLS" and now it automatically downloads the highest quality. Feel free to close this issue if you feel it's invalid, but I do have a suggestion. I think it might be worth adding this to the FAQ: 
`Q: how come 1080p YouTube download is not working` 
`A: Try disabling native HLS. You can disable the "Prefer Native HLS" option under the Options>Extra tab.`

**Comment by Akhilesh-T** [comment]
Hi,

I'm using the **Windows** version but facing the same issue. Disabling "**Prefer Native HLS**" didn't work for me.

Does anyone know how to solve this issue?

Thanks!

**Comment by axcore** [comment]
Make sure FFmpeg is installed on your system. youtube-dl uses FFmpeg with 1080p videos.

This project is not maintained any more, perhaps you would find [this fork](https://github.com/axcore/tartube) easier, since it will install FFmpeg for you.

**Comment by Akhilesh-T** [comment]
Thank you @axcore
