### ISSUE TITLE
Incompatibility with python3

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [MrS0m30n3/youtube-dl-gui#344]
When I did `pip3 install youtube-dlg`, I got the following output on my Linux Mint 19 machine:
```
Collecting youtube-dlg
  Downloading https://files.pythonhosted.org/packages/55/28/70620c1ffb8ad7ecb81913a053dc454ad7116d3fbdbd8ca23ac0b19ebb40/Youtube-DLG-0.4.tar.gz (153kB)
    100% |████████████████████████████████| 153kB 398kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-qsl53hm0/youtube-dlg/setup.py", line 69, in <module>
        from youtube_dl_gui import (
      File "/tmp/pip-build-qsl53hm0/youtube-dlg/youtube_dl_gui/__init__.py", line 25
        print error
                  ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(error)?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qsl53hm0/youtube-dlg/
```

I suspect youtube-dlg has not yet been [made to work with python3](https://pythonclock.org/). It would be nice if this could work for both Python - 2 and 3.

P. S: Thank you for the good work!

**Comment by nodiscc** [comment]
https://github.com/MrS0m30n3/youtube-dl-gui/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+python3

Installing with `pip2 install`  should work

**Comment by peanutbutterandcrackers** [comment]
Yes, it did. This is a good program. Thank you for your efforts.

I see this issue is also a duplicate, particularly of #289. It would be nice if this could be upgraded to Python3 soon as Python2 will be reaching it's EOL soon (2020 Jan 1).

Closing this as a duplicate, then.

**Comment by peanutbutterandcrackers** [comment]
There is `2to3` tool to do automatic conversions from Python2 code to Python3.
Here: https://docs.python.org/2/library/2to3.html
