### ISSUE TITLE
Feature request (request for a new functionality): BBC FLV Videos

### ISSUE THREAD

**Issue by Kelvin2019** [MrS0m30n3/youtube-dl-gui#357]
### Feature request (request for a new functionality)

Please make sure that the requested feature is **NOT** already in the [TODO](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/TODO) list

- [X ] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list

#### What operating system do you use ?
Windows 10

---

Although current BBC videos are downloadable the older FLV video such as the one below are not.

https://www.bbc.co.uk/programmes/p005qxp7

**Comment by nodiscc** [comment]
- You did not include the requested information (most importantly the log/error message)
- https://github.com/rg3/youtube-dl/search?o=desc&q=bbc&s=updated&type=Issues suggests that BBC downloads are suffering some issues in recent youtube-dl versions.

Closing, feel free to reopen if you have more information
