### ISSUE TITLE
Unable to download videos on Windows 10?

### ISSUE THREAD

**Issue by KirbyFan102** [MrS0m30n3/youtube-dl-gui#370]
My primary computer runs windows 10. I've had to reinstall it recently, but prior to that, I never had any problems using Youtube-DLG to download videos. But right now, whenever I try to download any video at all, it goes directly to "finished" while the video is at 0%, having not downloaded anything.
I tried using it on a computer with windows 8, it worked fine. I tried the same videos, too, so it has to be the computer that's causing it, not the videos.
Is there any way to fix this? And is this something that's happened before?

**Comment by KirbyFan102** [comment]
NEVER MIND, fixed it. Just had to download a msvcr100.dll, and put it in the appropriate folder. It's working fine now.

**Comment by PantherZalayeta** [comment]
> NEVER MIND, fixed it. Just had to download a msvcr100.dll, and put it in the appropriate folder. It's working fine now.

thanks! i was having the same problem

**Comment by KirbyFan102** [comment]
No problem :)

**Comment by 198019** [comment]
Same problem, "finished" message without downloading anything. Same solution too. 

Needs to add Visual C++ Redist 2010 as a requirement to the windows binary.

**Comment by VaiTon** [comment]
@KirbyFan102 if it is fixed please close the issue.
