### ISSUE TITLE
Option to download one after another

### ISSUE THREAD

**Issue by ThebestwaytodesignJoinGitHub** [MrS0m30n3/youtube-dl-gui#38]
and not all at the same time.
useful for a slow internet connection.

**Comment by MrS0m30n3** [comment]
You refer to the number of parallel downloads?

If so, then currently there is a way to change the number of max parallel downloads by editing the "**workers_number**" option in your settings.json file.

The settings.json file is located at
* Windows:     %APPDATA%\Roaming\youtube-dlg
* Linux:    ~/.config/youtube-dlg

You can also read this issue: https://github.com/MrS0m30n3/youtube-dl-gui/issues/20

This options will be available at the new GUI so you won't have to edit your settings file everytime.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
Ah, thank you
