### ISSUE TITLE
When will youtube-dl-gui update?

### ISSUE THREAD

**Issue by ghost** [MrS0m30n3/youtube-dl-gui#408]
Last update was a year and a half ago.
YouTube is different now.

**Comment by nathantaal** [comment]
And there are 81 commits since last release. I don't know if branch is build-ready but I hope it is.

**Comment by ghost** [comment]
Youtube dl DLG upgrade needed yesterday! 
@MrS0m30n3 he stayed three years and did a lot of good.
We need you!

**Comment by axcore** [comment]
[This fork](https://github.com/axcore/tartube) of youtube-dl-gui was updated today.

**Comment by ghost** [comment]
Tartube big cow. There is no Polish language and does not download movies, only links.
I don't want a big cow, just a simple youtube dlg portable.
