### ISSUE TITLE
Please release 0.3.8 tag to be able to enter into official homebrew.

### ISSUE THREAD

**Issue by pr0d1r2** [MrS0m30n3/youtube-dl-gui#41]
See: https://github.com/Homebrew/homebrew/pull/39987/files#diff-8c3e3bae4209ea806fdd9b449a582314R6

**Comment by MrS0m30n3** [comment]
Hi @pr0d1r2 

Tag 0.3.8 is now available. 
Leave this issue open until you merge your pull request with the official homebrew repo.

**Comment by MrS0m30n3** [comment]
Closing, since this issue is outdated.

@pr0d1r2 you can open a new issue and we can discuss the details there if you are still intrested.

**Comment by pr0d1r2** [comment]
@MrS0m30n3 sorry, no time for this right now :(
