### ISSUE TITLE
videos with very long titles are undownloadable on windows

### ISSUE THREAD

**Issue by hecko-yes** [MrS0m30n3/youtube-dl-gui#421]
example video: https://twitter.com/Tigenki/status/1209243329684279296

error shown: `[01/24/20 20:22:48] ERROR: unable to open for writing: [Errno 2] No such file or directory: "C:\\Users\\nicetry\\Downloads\\ Cat-astrophe  - No giveaway accounts! And please don't unfollow after the raffle ends, that ain't cool For anyone who can't see the above examples moving, here's a GIF! Prize will come with both a 500x500 version and a 100x100 version for use as avatars c - Hypno eyes are optional!.mp4.part"`

this error is most likely because ntfs only supports filenames with up to 255 characters

this is a problem with youtube-dl too, but at least there you can use a custom/hash filename to get around it

**Comment by QPUNeptune** [comment]
uhh, i mean there is a filename format on the tab you open when you click options
![youtube-dl-gui_98glWQSTAL](https://user-images.githubusercontent.com/55235912/73316763-ef0f3680-422b-11ea-9775-059b586e71fc.png)

**Comment by hecko-yes** [comment]
ohhhh right i'm blind sorry
