### ISSUE TITLE
Where is DLG's install directory for youtube-dl?

### ISSUE THREAD

**Issue by KirbyFan102** [MrS0m30n3/youtube-dl-gui#445]
- [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [ ] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [ ] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

I recently installed youtube-dl via python, and would like to make youtube-DLG use that version instead. So I would like to find where it originally installed youtube-dl and see if it can work using the version of the program on my python directory.

**Comment by JamoDevNich** [comment]
On my Windows machine it's in the `%appdata%/youtube-dlg` folder compiled as an exe.

https://github.com/MrS0m30n3/youtube-dl-gui/blob/57eb51ccc8e2df4e8c766b31d677513adb5c86cb/youtube_dl_gui/utils.py#L180

**Comment by KirbyFan102** [comment]
If I delete this version, and click on the update youtube-dl button, will dl-gui just reinstall it to that directory? Or will it instead update the python version of it?

**Comment by JamoDevNich** [comment]
From what I can see in the code it can only update the version of youtube-dl that it downloads itself, you would need to update the python version of youtube-dl externally. So yes it would just re-install to that directory.

https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/youtube_dl_gui/updatemanager.py#L30

Also looks like there is an option to disable updates but this doesn't appear to be accessible from the UI (can't find it)

https://github.com/MrS0m30n3/youtube-dl-gui/blob/57eb51ccc8e2df4e8c766b31d677513adb5c86cb/youtube_dl_gui/mainframe.py#L1040

**Comment by KirbyFan102** [comment]
That's good to know, thanks.
