### ISSUE TITLE
Not possible to recover the list of videos to download, once added from the gui.

### ISSUE THREAD

**Issue by antoan** [MrS0m30n3/youtube-dl-gui#478]
- [ x] **I think** my problem is **NOT** with **youtube-dl**
  - [ x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x ] **I assure** that i am using the latest version of **youtube-dl**
  - [ ] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [ ] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [ ] Feature request (request for a new functionality)
- [ x] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---
#### What operating system do you use ?
Ubuntu 20.04
#### List of actions to perform to reproduce the problem:

  1. Paste a list of youtube videos to download.

  2. Add to download, via button.
  3. Something unexpected happens we need to reboot the machine, and since the gui does not provide a way to persist the download list for later use, we want to manually backup that list to download them later. 
  4. Manually copying the download list used to be easy in the previous <0.4 version of the gui - as it simply remained present in the upper pane and was not cleared during download, not so with 0.4 where one needs to copy each item line by line.

### Feature request (request for a new functionality)
Do you plan to allow an option to save the download list, in case youtubedl-gui needs to be closed?

Please make sure that the requested feature is **NOT** already in the [TODO](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/TODO) list

- [x] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list

**Comment by axcore** [comment]
This project is not being maintained any more. There is a fork [here](https://github.com/axcore/tartube).
