### ISSUE TITLE
Save keywords as well

### ISSUE THREAD

**Issue by Xylemon** [MrS0m30n3/youtube-dl-gui#48]
Can we have the ability to save keywords (can be referred to as video tags) as well? They may be hidden on the page normally, but it's clearly visible in the source of the page.

**Comment by MrS0m30n3** [comment]
Hi @Xylemon 
I don't really understand what you are asking, can you give me an example?

**Comment by Xylemon** [comment]
I am talking about the old video tags that use to be publicly visible on the video description, but now hidden. Many older videos used video tags to include funny messages or other amusing info. Even though Google made them hidden, you can still see them. For instance, go to this video: https://www.youtube.com/watch?v=Hhpnp6ssqSQ

If you view the source of the page, and search for "keywords", you'll find all the video tags on line 258.

"keywords":"Valve Corporation (Video Game Developer),Valve,Time,ValveTime,Arkane Studios (Video Game Developer),The Crossing (Video Game),Video Game (Industry),Half-Life 2 (Video Game),Half-Life 2: Episode Four,Ep4,Ep3,Episode Four,Half-Life 3,Source Engine (Video Game Engine),Database,Gabe Newell (Organization Leader),Viktor Antonov,Dishonored (Award-Winning Work),Source 2,Multiplayer,Cancelled,Game"

I am asking if this information can be saved into the json files as well. It would be incredibly useful for my massive YouTube Archive.

**Comment by MrS0m30n3** [comment]
This is an issue with [youtube-dl](https://rg3.github.io/youtube-dl/). 
*youtube-dl-gui* is just a gui wrapper for *youtube-dl*.
*youtube-dl* is responsible for downloading the video files.
I searched the *youtube-dl* repo and i found this issue: https://github.com/rg3/youtube-dl/issues/3068

**Comment by Xylemon** [comment]
I see, I didn't know youtube-dl created the json files. Closing.
