### ISSUE TITLE
Suspicios IP connections

### ISSUE THREAD

**Issue by forofo** [MrS0m30n3/youtube-dl-gui#481]
On Windows Portable version, youtube-dl-gui is trying to connect to the following  IP.  If this is not allowed, the program doesn't work.  The IP seems to belong to a private user from an home ISP network

What it can be?

ip	"185.184.176.69"
hostname	"69.176.184.185.static.waly.ch"
city	"Fiesch"
region	"Valais"
country	"CH"

**Comment by axcore** [comment]
This project is not being updated any more. If you are worried, there is a fork [here](https://github.com/axcore/tartube).

**Comment by forofo** [comment]
understood. Thanks.
