### ISSUE TITLE
revise all options

### ISSUE THREAD

**Issue by Jan02** [MrS0m30n3/youtube-dl-gui#50]
When I try a youtube URL with default options I get this error:
youtube-dl.exe: error: no such option: --max-quality

version: youtube-dl-gui-0.3.8-win-portable

from the log:
```
[07/23/15 02:02:26] Usage: youtube-dl.exe [OPTIONS] URL [URL...]
[07/23/15 02:02:26] youtube-dl.exe: error: no such option: --max-quality
```

**Comment by cadesalaberry** [comment]
It seems to have been removed from `youtube-dl` core. https://github.com/rg3/youtube-dl/pull/5523

**Comment by Jan02** [comment]
Even if I change the video options it still says:

 [07/23/15 15:29:56] Usage: youtube-dl.exe [OPTIONS] URL [URL...]

**Comment by MrS0m30n3** [comment]
@Jan02 

Sorry for the late response i was AFK for a long time.
I just tried the portable version in a new Windows 7 installation and it worked fine with the default options. Also, all the options are up to date with youtube-dl. Are you still facing the same problem?
