### ISSUE TITLE
Absolute necessity of adding mkv format to yt-dlg

### ISSUE THREAD

**Issue by 1reverseengineer** [MrS0m30n3/youtube-dl-gui#504]
- [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Feature request (request for a new functionality)

- [x] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list

#### What operating system do you use ?
Windows 10

---

MKV is the matroshka container format which is known for being the best of the best, it can hold the extremely high quality video streams while also holding the best audio streams (+ thumbnails and subs etc...).
Any lossless/remux or high bitrate bluray movie are released in the mkv format.
MKV is convenient, easy to use, up to modern standards, support many more features. To most people in this field, mkv is a must/modern day standard compared to mp4 etc...

**Comment by axcore** [comment]
This project is abandoned. Try [this fork](https://github.com/yt-dlg/yt-dlg) or [my fork](https://github.com/axcore/tartube).

**Comment by abdo2048** [comment]
There is also another project here: https://github.com/jely2002/youtube-dl-gui
