### ISSUE TITLE
allow custom format 

### ISSUE THREAD

**Issue by osascruz** [MrS0m30n3/youtube-dl-gui#516]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [x ] **I think** my problem is **NOT** with **youtube-dl**
  - [ x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [ x] **I assure** that i am using the latest version of **youtube-dl**
  - [X ] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [ X] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [ X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

### Feature request (request for a new functionality)

Please make sure that the requested feature is **NOT** already in the [TODO](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/TODO) list

- [ X] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list

maybe related to "Mix formats option" ?

#### What operating system do you use ?
windows10

---

We need possibility to use format  such as  -f "bestvideo[height<=?480]+bestaudio[ext=m4a]/best[height<=480]"
instead of just
because sometimes there is no high resolution video but split video/audio instead, 

That would solve the MP3 problem too where it sometimes download 2GB  4K  video to strip 60MB of audio content, when m4a file is available, to avoid that the Mp3 format should use  :
-f "bestaudio[ext=m4a]/best[height<=480]"

to limit  to best audio with m4a format (so can be converted to mp3) and if not available, limit the max video size to be downloaded (only care here is the audio,  no need to download HUGE 2160p video one !)

maybe it is already supported , but I can't find any INI file or customization of the command line

**Comment by axcore** [comment]
This project is abandoned. There is a fork [here](https://github.com/oleksis/youtube-dl-gui), but I don't if it supports the feature you want.

[My own fork ]([url](https://github.com/axcore/tartube)) enables you to add any command-line options you like: click **Edit > General download options**, then add something to the **Extra command line options** box, for example **-f "bestaudio[ext=m4a]/best[height<=480]"**

**Comment by osascruz** [comment]
Thank you so much for your prompt reply !
