### ISSUE TITLE
Downloading mp3s from playlist sometimes downloads temporary webm first

### ISSUE THREAD

**Issue by DaforLynx** [MrS0m30n3/youtube-dl-gui#522]
- [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Bug report
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

#### What operating system do you use ?

Win10

#### List of actions to perform to reproduce the problem:

  1. Copy and paste YouTube playlist URL
  2. Choose destination and select "mp3" as the file format
  3. Add to queue and proceed to download
  
#### What is the expected behaviour ?

Each song will be downloaded quickly in mp3 format, after pre-processing for a bit, of course.

#### What happens instead ?

After pre-processing, _some_ videos (seemingly randomly) will proceed to download in webm format, before finally downloading as mp3. This multiplies the download time considerably. The webm will delete itself after either it or its corresponding mp3 are finished downloading, I don't know which.

---

As stated above, it's kind of weird how some videos will download as a webm despite me deliberately selecting "mp3". I'm not entirely sure whether it's a youtube-dl or a youtube-dl-gui issue. I'm not sure if it's a problem specifically with playlist downloading, either. But it does seem intentional, and if it's not an issue that can be fixed I'd like to know why, at least.
(Also, I once came across an issue where not every video in a playlist was downloaded, so it may be that playlist downloading is just buggy in general)

Edit: And now I'm coming across the issue in parentheses above again. And also, it's sometimes downloading m4a instead of webm? Weird.

**Comment by axcore** [comment]
This project is abandoned. Try one of the forks listed [here](https://www.reddit.com/r/youtubedl/wiki/info-guis).

**Comment by DaforLynx** [comment]
> 
> 
> This project is abandoned. Try one of the forks listed [here](https://www.reddit.com/r/youtubedl/wiki/info-guis).

Thank you. Didn't know.
