### ISSUE TITLE
Change number of simultaneous downloads

### ISSUE THREAD

**Issue by Pcsl** [MrS0m30n3/youtube-dl-gui#53]
Hello there again,

Is there any way to increase the number of simultaneous downloads? At this moment the software only allows me to download 3 files at the same time. When the video provider is slow this is far from being reasonable as you use only a minimal part of the available bandwith.

So I was wondering if there is any way to increase it or if you plan to add this in the future...

Keep up the good work!

**Comment by MrS0m30n3** [comment]
Hi @Pcsl 

Currently you can change the number of simultaneous downloads by editing the *workers_number* option under your settings file. To find the path of your settings file start *youtube-dl-gui* and hit the options button. At the bottom of the General tab you should see the *Settings File* label which shows the absolute path to your settings file.

There is also an open pull request for this issue. See: https://github.com/MrS0m30n3/youtube-dl-gui/pull/43 
I still have no reply from this guy so, you can create a new pull request if you want to fix this one.

You can also read [issue #20](https://github.com/MrS0m30n3/youtube-dl-gui/issues/20)

**Comment by MrS0m30n3** [comment]
I am closing this since there is an open pull-request for this issue.
