### ISSUE TITLE
Alternative GUI Downloader

### ISSUE THREAD

**Issue by MustafaHi** [MrS0m30n3/youtube-dl-gui#530]
Feel free to check out [xload](https://github.com/MustafaHi/xload) as an alternative

https://github.com/MustafaHi/xload

**Comment by floorshame** [comment]
no lol.

**Comment by ReznicencuBogdan** [comment]
> 

No thanks. Your 'open-source-code' is so open-source that no one can actually see it.

**Comment by p0358** [comment]
LOL

![image](https://user-images.githubusercontent.com/5182588/152520556-bcf043e3-e490-4651-bf34-d33ba409c50d.png)

**Comment by EmaX093** [comment]
Is this a joke or something ?
