### ISSUE TITLE
On Windows, commands like "something" pass in youtube-dl as \"something\"

### ISSUE THREAD

**Issue by unreal666** [MrS0m30n3/youtube-dl-gui#54]
Example, I type in Commands tab

```
-f "(mp4)[width<1300]"
```

but youtube-dl-gui run youtube-dl with parameter

```
-f \"(mp4)[width<1300]\"
```

but it has to be just

```
-f "(mp4)[width<1300]"
```

**Comment by MrS0m30n3** [comment]
You don't actually need the quotes on the gui.

Try again without the quotes and let me know if that worked.
Also, don't add spaces between the filters.
For example type (mp4)[width<1337][filesize>5M] and not (mp4)[width  <  1337]  [filesize  >  5M]

**Comment by unreal666** [comment]
Hm. Without quotes and spaces work normally.
