### ISSUE TITLE
Programme stalls

### ISSUE THREAD

**Issue by midas02** [MrS0m30n3/youtube-dl-gui#56]
Am I correct in assuming youtube-dl-gui is supposed to behave in exactly the same way as youtube-dl?

In that case I found an issue. Try downloading the following, with the flag "-f mp4", http://deredactie.be/permalink/1.2464764. It stalls halfway during the download. Seems to do so for all videos from that website. Downloading the same with youtube-dl from the command line works fine though.

**Comment by MrS0m30n3** [comment]
I just downloaded the URL with the latest version of youtube-dl-gui and it works fine both on Windows and Linux. What exactly do you mean when you say that it stalls during the download? Does the GUI freezes?

**Comment by midas02** [comment]
Ok, strange.

I'm running 0.3.7 on Win XP. It hangs about 3MB into the download. Just hangs, and stays there. Someone else confirmed the same behaviour to me. Also with other files from the same source.

You tried downloading it as a mp4 file right? As the standard flv version downloads just fine.

**Comment by MrS0m30n3** [comment]
I used the latest version from github thats why it worked.

There was a problem with youtube-dl [hls downloader](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/downloader/hls.py) which is now fixed.
You can read issue #49 for more informations.

This error is still valid even in the latest released version 0.3.8.
The patch will be included in version 0.3.9, until then you can use the patched portable version from [here](https://drive.google.com/file/d/0B4LUjPpAKNa1XzRjdjk5RW1HRnc/view?pli=1)

**Comment by midas02** [comment]
Ok, known issue then. I tried the patch, I confirm it was fixed. Closing the ticket.
