### ISSUE TITLE
Unicode decode error

### ISSUE THREAD

**Issue by MrS0m30n3** [MrS0m30n3/youtube-dl-gui#57]
*Comments from issue \#39*

>  rb07 commented 4 days ago

> Another use case (already mentioned in the youtube-dl thread): any user with a foreign character in its user name results in an early exception (the user's home directory is used to create/store something at the start of the program, and it fails; same thing happens when the program tries to create a log of the exception inside the installed location, which doesn't have write permission for the user -- no UTF problem here, just write permission, which is easy to fix).

> This is in Windows so its probably lack of UTF-16 support.

>> MrS0m30n3 commented 2 days ago

>> Hi @rb07 

>> That seems like a completely different problem. The main problem with the issue 4787 on the youtube-dl repo is the python's subprocess module on versions prior to 3. I was not able to reproduce your problem neither with the raw python version or the py2exe (Windows executable) version using foreign characters in the username path. Can you run the portable version of youtube-dlg from your desktop and paste the output of the log here?

>> **note**
Youtube-dlg creates the log file in the initialization process (See: [\__init\__.py:58](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/youtube_dl_gui/__init__.py#L58)) but i don't see a reason why this could fail if we use a config_path with foreign characters.

>>>  rb07 commented 2 days ago 

>>> You misunderstood the log issue, I said the problem is a permission problem, not a UTF problem (i.e. foreign characters are not involved, actually not even tested since the path is `/Program Files/YoutubeDLG`).

>>> Back on topic, the foreign character issue happened with the Windows executable, version 0.3.7, the original (not from the portable version, from the installed version) log:

>>> `Traceback (most recent call last):`
`  File "__main__.py", line 35, in <module>`
`  File "youtube_dl_gui\__init__.pyc", line 52, in <module>`
`  File "youtube_dl_gui\utils.pyc", line 93, in get_config_path`
`  File "ntpath.pyc", line 84, in join`
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 8: ordinal not in range(128)`

>>>>  MrS0m30n3 commented a day ago 

>>>> This was a completely different issue. Anyway, the problem was in the joining process as you can see in your log file, i just had to decode the imported value from the os.getenv function using the system preferred encoding. You should not longer face this issue as long as your system encoding can handle the foreign characters (See: https://github.com/MrS0m30n3/youtube-dl-gui/commit/def80ed6b419ff121a6284fd9ea402af3cf95386 for more details). 

>>>> You can find the patched portable version [here](https://drive.google.com/file/d/0B4LUjPpAKNa1TUNaeWRIeFpUS0k/view?usp=sharing).
Can you give it a try an let me know if that worked?

>>>>>  rb07 commented 19 hours ago 

>>>>> Tested the patched portable version, same problem, see the log:

>>>>> `Traceback (most recent call last):`
`  File "youtube-dl-gui", line 35, in <module>`
`  File "youtube_dl_gui\__init__.pyc", line 54, in <module>`
`  File "youtube_dl_gui\optionsmanager.pyc", line 51, in __init__`
`  File "youtube_dl_gui\optionsmanager.pyc", line 201, in load_default`
`  File "ntpath.pyc", line 310, in expanduser`
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 10: ordinal not in range(128)`

**Comment by Capoeirista** [comment]
I have same error
```
Traceback (most recent call last):
  File "youtube-dl-gui", line 35, in <module>
  File "youtube_dl_gui\__init__.pyc", line 52, in <module>
  File "youtube_dl_gui\utils.pyc", line 94, in get_config_path
  File "ntpath.pyc", line 84, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 7: ordinal not in range(128)
```
In patched version (include above issue):
```
Traceback (most recent call last):
  File "youtube-dl-gui", line 35, in <module>
  File "youtube_dl_gui\__init__.pyc", line 54, in <module>
  File "youtube_dl_gui\optionsmanager.pyc", line 51, in __init__
  File "youtube_dl_gui\optionsmanager.pyc", line 201, in load_default
  File "ntpath.pyc", line 310, in expanduser
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 9: ordinal not in range(128)
```

**Comment by MrS0m30n3** [comment]
Hi @rb07 @alchemisty @Capoeirista

I uploaded a new patched version [here](https://drive.google.com/file/d/0B4LUjPpAKNa1MXdOT1BQOEFEMGs). Can any of you try it out and let me know if it works?

**Comment by rb07** [comment]
It works fine **MrS0m30n3**.
