### ISSUE TITLE
external downloaders with youtube dl gui

### ISSUE THREAD

**Issue by ExtendedDev** [MrS0m30n3/youtube-dl-gui#60]
Is it possible to properly configure an external downloader, such as aria2c with y-dl-gui? The same cl argument --external-downloader aria2c  is functioning normally with the cl version. For instance, using the following arg in gui version:  aria2c --external-downloader     "download" is "completed" with status finished in main window. In this case, nothing is downloading. The same thing happens with following args: 
--external-downloader aria2c
youtube-dl --external-downloader aria2c
youtube-dl-gui --external-downloader aria2c

**Comment by Korons** [comment]
Have you tried adding `--external-downloader aria2c` to the commands tab in the options window of youtube-dl-gui?

**Comment by Korons** [comment]
I just tried adding `--external-downloader aria2c` to the command tab of youtube-dl-gui and it worked fine (aside from throw a `WARNING: Requested formats are incompatible for merge and will be merged into mkv.`)
