### ISSUE TITLE
Please add scheduling support

### ISSUE THREAD

**Issue by AnonymousUser200102010** [MrS0m30n3/youtube-dl-gui#63]
Please add scheduling support or some argument that automatically starts the download process.

I'd also like to not take up another ticket so I'd also like to see download validation support (where duplicate downloads are rejected without being downloaded) as soon as you are able.

Thanks.

**Comment by MrS0m30n3** [comment]
Hi @AnonymousUser200102010 

Yeah basically your OS should schedule when youtube-dl-gui should run. I don't really want to turn youtube-dl-gui into a daemon. I am planning to add support for command line arguments where you will be able to specify a file as the input with the URLs you want to download. Then you will be able to create a batch file and run it using the OS scheduler.

Now for the second issue, youtube-dl-gui already checks if the video is presented before it starts the download process. Also, you should check the **--download-archive FILE** option see: https://github.com/rg3/youtube-dl/blob/master/README.md#options for more informations i think thats exactly what you ask for.

**Comment by MrS0m30n3** [comment]
Closing this feel free to reopen if you have to
