### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by timofonic** [MrS0m30n3/youtube-dl-gui#66]
Hello.

I would like to know if this project is still alive, because there hasn't been recent activity.

Kind regards.

**Comment by nodiscc** [comment]
Well there is not much to be fixed and the program works as expected, so low activity is quite ok I think.

**Comment by timofonic** [comment]
I have a small "issue", I'm going to submit another issue about it...

**Comment by nodiscc** [comment]
In the meantime I think this one can be closed.

**Comment by MrS0m30n3** [comment]
Hi @timofonic 

This project is still alive i just was quite busy. Anyway, if you have more issues let me know.
@nodiscc Thanks for helping dude :+1:
