### ISSUE TITLE
"Download at best quality possible" option

### ISSUE THREAD

**Issue by timofonic** [MrS0m30n3/youtube-dl-gui#67]
Hello.

Are there a possibility to put an option to download the video at the best possible quality format. I need it for lectures and some technical videos, where it's important to watch them at high quality (some of them are tutorials to using technical software and are captured with not so good screen capturing tools, for example).

Kind regards.

**Comment by nodiscc** [comment]
I think the `default` format is now the highest possible quality. youtube-dl had `--quality best` in the past but I think it was deprectaed, and is now the default setting. @timofonic You should check `man youtube-dl` for a list of formats.

**Comment by nodiscc** [comment]
https://github.com/rg3/youtube-dl#format-selection

>FORMAT SELECTION
>       By  default  youtube-dl  tries to download the best quality, but sometimes you may want to
>       download in a different format.  The simplest case is requesting a  specific  format,  for
>       example  -f 22.   You  can get the list of available formats using --list-formats,

I think you can safely close this issue.

**Comment by MrS0m30n3** [comment]
Hi @timofonic 

It's exactly as @nodiscc said. When you have the *default* video format selected under Options>Video tab, youtube-dl-gui uses the default behaviour of youtube-dl which tries to download the highest quality possible.
