### ISSUE TITLE
Audio only YouTube Download?

### ISSUE THREAD

**Issue by robdhayes** [MrS0m30n3/youtube-dl-gui#68]
Hello, love this GUI.

I was hoping there was a way to have YouTube links download as an MP3.  I imagine there is a Command for this, but I haven't been able to figure it out (nor on the command line version).

Thanks in advance for any assistance.

**Comment by nodiscc** [comment]
command-line: `youtube-dl --extract-audio URL`, https://github.com/rg3/youtube-dl#post-processing-options.

youtube-dl-gui: Options > Audio > Convert to Audio

**Comment by robdhayes** [comment]
Curiously, the Options > Audio > Convert to Audio option doesn't work when I launch the program using AutoHotkey.

The code is:

^PgDn:: ; Ctrl+PgDn
run, C:\Program Files (x86)\YoutubeDLG\youtube-dl-gui.exe
Sleep 1500
Send, ^v ; Copy
Sleep 1000
Send, %A_Tab%
Sleep 1500
Send, {Enter}
;WinWait, WinTitle, WinText, Seconds, ExcludeTitle, ExcludeText
WinWait, Info ahk_class #32770, OK
Sleep 12500
Send, {Enter}
return

Any idea why this may be?

**Comment by robdhayes** [comment]
This command line version also doens't work:

^!PgDn::
ClipBoard = %ClipBoard% ; Convert to text
ClipWait ; Wait for the clipboard to contain text.
SetWorkingDir, C:\Users\Rob\Desktop
Run, youtube-dl.exe --extract-audio --audio-format "mp3" %ClipBoard%
Return

In both cases, the download works as a webm and not mp3

**Comment by nodiscc** [comment]
Nice you figured it out. May I ask why you used autohotkey instead of a simple script using the original youtube-dl commandline utility?

**Comment by robdhayes** [comment]
Good question.  I could not get the command line version working because of an error, which turned out to be a folder write permissions issue.

I have resolved the error and the simplified AutoHotkey script is:

^!PgDn:: ; presses Ctrl+PgDn
ClipBoard = %ClipBoard% ; converts to text
ClipWait ; waits for the clipboard to contain text.
SetWorkingDir, S:\Music\!EDM\!LooseLeaves ; Sets directoy to writable folder (need youtube-dl.exe, ffmpeg.exe, and ffprobe.exe inside)
Run, youtube-dl.exe --extract-audio --audio-format mp3 %ClipBoard%
Return

I've still recommended your GUI to 3 friends who do not use AHK and enjoy the benefits of ease-of-use.

**Comment by robdhayes** [comment]
Just noticed the command line version doesn't tag mp3s nearly as nicely as your GUI.  Would you happen to know the proper command for tagging?

**Comment by nodiscc** [comment]
FYI this is not my program, all credit goes to @MrS0m30n3. Check https://github.com/rg3/youtube-dl/blob/master/README.md for metadata options, I think the switch you're looking for is `--add-metadata` (not metadata-from-file)
