### ISSUE TITLE
Translations & icons dont work when installing via pip

### ISSUE THREAD

**Issue by qinfeng** [MrS0m30n3/youtube-dl-gui#73]
I try to change Localisation in Option panel, but the UI's language does not change after I restart youtube-dlg.

Howerver, I see the the locale is changed in settings file in .config/youtube-dlg/settings.json.

Possible bug is the locale files are not installed in right place as shown in attached screenshot.

After I move those PO files to correct places. It works perfectly.

PS. I install it via  `pip install youtube-dlg` in Mac OSX EI Capitan 10.11.3

![screen shot 2016-02-11 at 3 14 41 pm](https://cloud.githubusercontent.com/assets/1988491/12971213/69e89a5a-d0d3-11e5-895b-d86eeb51b2ab.png)

**Comment by qinfeng** [comment]
After a few hours searching, it seems an issue of setuptools and pip as shown in this Python's Packaging User Guide: http://python-packaging-user-guide.readthedocs.org/en/latest/distributing/

> setuptools allows absolute “data_files” paths, and pip honors them as absolute, when installing from sdist. This is not true when installing from wheel distributions. Wheels don’t support absolute paths, and they end up being installed relative to “site-packages”. For discussion see wheel Issue #92.

I tried to install via `python setup.py install` after clone the code. It works fine. However,`pip install ./` will package the project into bdist_wheel then install it which cause those `mo` files installed into wrong places.

**Comment by MrS0m30n3** [comment]
Hi @qinfeng

You are absolutly right. I didnt notice this one, this also occurs on Linux when i install using pip both for the translation files and the icons. Thanks for reporting this.

**Comment by MrS0m30n3** [comment]
PiP now works fine with the **new_layout** branch.

I moved all the translation files & icons into the package directory and changed the absolute icons paths (/usr/share/) to relative ones which seems that pip can handle just fine.

This fix will be available on the next release, closing.
