### ISSUE TITLE
cannot install in mac osx

### ISSUE THREAD

**Issue by qinfeng** [MrS0m30n3/youtube-dl-gui#74]
I run `python setup.py install` in Mac OSX but failed with below error message:

![screen shot 2016-02-11 at 5 47 00 pm](https://cloud.githubusercontent.com/assets/1988491/12973487/a28e1bfa-d0e7-11e5-8309-5dab9f146ff7.png)

It seems commit https://github.com/MrS0m30n3/youtube-dl-gui/commit/3d8aa8a0f11442fe96ca41fc9fa2d815488b0afc#diff-2eeaed663bd0d25b7e608891384b7298L141 removed the normal_setup() for darwin platform.

**Comment by MrS0m30n3** [comment]
Yeah currently there is no official support for mac. @pr0d1r2 wanted to add the package to homebrew but there are some issues that i need to fix first before releasing the next version. Until version 0.3.9 gets released the only way to install on mac is using the pip but the translations-icons wont work as you already know. 

Also as far as i can see the **darwin** platform support on commit https://github.com/MrS0m30n3/youtube-dl-gui/commit/3d8aa8a0f11442fe96ca41fc9fa2d815488b0afc#diff-2eeaed663bd0d25b7e608891384b7298L141 does not even handle the icon files.

If you have the time you are free to create a new pull request which adds support for the **darwin** platform using the `python setup.py install` way.

**Comment by skywinder** [comment]
Same issue. Please give some advices, how to run it properly.
after installation `ffmpeg` and `wxpython`

`sudo python setup.py install`

cause error: `error: could not create '/usr/share/icons': Operation not permitted`

**Comment by MrS0m30n3** [comment]
Try using `sudo pip install youtube-dlg` as mentioned here: https://github.com/MrS0m30n3/youtube-dl-gui/issues/73

**Comment by MrS0m30n3** [comment]
Closing since there is no official support for mac.
