### ISSUE TITLE
Progress report for HLS downloader

### ISSUE THREAD

**Issue by ashutosh2k12** [MrS0m30n3/youtube-dl-gui#78]
I would love if we can get a progress report on streaming urls (for ex- http://hotstar.com/1000000554). Looks like ffmpeg output isn't piped to stdout. I have tried but failed to get frame report. I tried outputting `stdout` and `stderr` both didn't pointed out any frame report. Here is what I did at:
[here](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/youtube_dl_gui/downloaders.py#L170)

```
if stdout:
                print stdout #just to know standard output for a moment
                data_dict = extract_data(stdout)
                self._extract_info(data_dict)
                self._hook_data(data_dict)
```

and [here](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/youtube_dl_gui/downloaders.py#L59)

```
for line in iter(self._filedescriptor.readline, ''):
                    print line #to get standard error from console
                    # Ignore ffmpeg stderr
                    if str('ffmpeg version') in line:
                        ignore_line = True

                    if not ignore_line:
                        self._queue.put_nowait(line)
```

While I use the command: `youtube-dl --newline -i -o C:\\Users\\Username\\%(title)s.%(ext)s http://hotstar.com/1000000554` in command prompt(I am using windows), I get following frame output (using ffmpeg version N-78355-g020b758) -
![frameop](https://cloud.githubusercontent.com/assets/1492350/13028576/2de8c472-d299-11e5-8a4f-6b376b59a3df.JPG)

I am unable to get this stdout when using youtube-dlg via console. Can someone point me in some direction?

**Comment by ashutosh2k12** [comment]
I checked and found youtube-dl didn't output `ffmpeg` to console (which again outputs to stderr pipe, this explains the reason of framelines going to `PipeReader`).
I've made a [pull request](https://github.com/rg3/youtube-dl/pull/8561) which now enables us to get progress.

**Comment by MrS0m30n3** [comment]
Hi @ashutosh2k12 

Hotstar uses the HLS downloader which uses ffmpeg to download the video. Now the ffmpeg output gets written in stderr, if you want to see this output add the print statement in *downloaders.py* line 60 and change line 62 to False then you should be able to see the output from ffmpeg.

I am also planning to use both stderr & stdout (not only stdout like i do now) to extract data but its not high in my priorities.
If you want to see more stats about the download process when using the HLS downloader you can
you the native HLS downloader. Go to Options>Commands tab and add the `--hls-prefer-native` option.

Also you can read issue https://github.com/MrS0m30n3/youtube-dl-gui/issues/49

**Comment by MrS0m30n3** [comment]
We could extract those informations directly on the youtube-dl-gui side as i said in my previous post.
Anyway, leave this issue open because i will probably have to add support on the youtube-dl-gui extractor after your pull request gets merged in the youtube-dl repo.

**Comment by MrS0m30n3** [comment]
@ashutosh2k12 Any news from the pull-request on the **youtube-dl** repo?

**Comment by MrS0m30n3** [comment]
@ashutosh2k12 

Closing, you can reopen this issue when [your pull request on the youtube-dl repo](https://github.com/rg3/youtube-dl/pull/8561) gets merged.
