### ISSUE TITLE
Download in specific format with no resolution attached

### ISSUE THREAD

**Issue by le717** [MrS0m30n3/youtube-dl-gui#79]
First, thank you for making this! It's just what I have been looking for. :)

I was wondering if you could somehow make it download into a certain format without tying it to a resolution. For example, [this song](https://www.youtube.com/watch?v=wX9oWOdZccA) downloads from youtube-dl as a 720p MP4 but from here as a 720p MKV. I can force it to an MP4 from the options, but the people I want to introduce this to will not know to check the resolution for each video and change the options on a per-video basis. It would be best if there were some way I could always download into MP4 (or any other of the possible formats) and let youtube-dl handle getting the highest/proper resolution.

**Comment by MrS0m30n3** [comment]
Hi @le717 

If you want lets say to download videos only in the *mp4* format you can set the video format option to *default* and under Options>Commands tab you can add this command `-f mp4`. That way youtube-dlg is going to search all available formats that match the specified format (in our case mp4) and download the highest quality available for the specified format. Other than that there is no other way to specify the video format i know its not the best option for a user which doesnt know anything about video formats, but i believe that the *default* option should be fine for most users.

**Comment by le717** [comment]
`-f mp4` is exactly what I was looking for. Thank you very much! :smiley:

**Comment by MrS0m30n3** [comment]
I think that i need to reorganize the options, maybe i could add an advanced tab where you will be able to select formats base on the resolution like now and keep only the simple formats (mp4, webm, flv, etc) under Options>Video tab. Anyway until then the command mentioned above should work fine.
