### ISSUE TITLE
Error downloading from RTÉ Player

### ISSUE THREAD

**Issue by seamus911** [MrS0m30n3/youtube-dl-gui#80]
It seems to stall at this:
![rte_error](https://cloud.githubusercontent.com/assets/17283454/13096424/527548fe-d511-11e5-8251-cd8239fbd47a.PNG)

**Comment by nodiscc** [comment]
Can you check the log and paste the contents here? `Options > Log > View Log`

Have you tried downloading it with the original command line tool [youtube-dl](https://rg3.github.io/youtube-dl/) and looking for error messages on the console?

**Comment by JohnRuddy** [comment]
Just to report the error if it's any use:

**### C:\WINDOWS\system32>youtube-dl https://www.rte.ie/player/ie/show/stutterer-30003890/10536757/
[generic] 10536757: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 10536757: Downloading webpage
[generic] 10536757: Extracting information
ERROR: Unsupported URL: https://www.rte.ie/player/ie/show/stutterer-30003890/10536757/**

**Comment by nodiscc** [comment]
@JohnRuddy rte.ie is not supported by youtube-dl: https://rg3.github.io/youtube-dl/supportedsites.html
It has already been reported here https://github.com/rg3/youtube-dl/issues/8525. I think you can subscribe to that issue and close the one we're on.

**Comment by nodiscc** [comment]
@seamus911 Please close this issue.
