### ISSUE TITLE
Muxing Opus with the Webm download.

### ISSUE THREAD

**Issue by Frozenkex** [MrS0m30n3/youtube-dl-gui#81]
Maybe it's already possible, in which case I'm not aware. But it'd be nice if it could download and mux Opus audio with the webm (talking about youtube here). Got the idea from CYS downloader for firefox, which has the option to mux Opus with webm when it's available.

**Comment by nodiscc** [comment]
You should ask at https://github.com/rg3/youtube-dl/. youtube-dl-gui is just a GUI.

**Comment by Frozenkex** [comment]
Perhaps. But it's possible youtube-dl can do that, but i don't understand it well enough to determine that.

**Comment by nodiscc** [comment]
~~As far as I know it can't~~ Apparently youtube-dl can do that: https://github.com/rg3/youtube-dl/blob:/master/README.md:

> You can merge the video and audio of two formats into a single file using -f <video-format>+<audio-format> (requires ffmpeg or avconv installed), for example -f bestvideo+bestaudio will download best video only format, best audio only format and mux them together with ffmpeg/avconv.

@MrS0m30n3 maybe you could add that to the `Options > Video` tab?

```
Video format
[  ...            ]

Mix format
[  ...            ]

[x] Use custom format
[ webm+opus            ]
```

Checking the `Use custom format` box would grey out the other 2 fields, and the `custom format` field would be passed as format parameter. There is a huge amount of possible combinations so it should be a freeform text field (not a dropdown list).

**Comment by MrS0m30n3** [comment]
**youtube-dl-gui** already uses the `-f<format1>+<format2>` to merge different formats together.
I don't exactly get what you propose @nodiscc, the *opus* format is not available.
If i run `youtube-dl -f 134+opous <URL>` i get: `ERROR: requested format not available`.

**Comment by MrS0m30n3** [comment]
Closing since this issue is old. Feel free to re-open if you have to.
