### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Rickyose** [MrS0m30n3/youtube-dl-gui#83]
Hello

i hav some problem in youtube dlg when i try to download other than from youtube, it will come with error message such example from dailymotion. in youtube dl it's already fixed by add --no-check-certificate. but when i add it in youtube dlg > option > commands, problem still persist. so i wionder if someone have answer for my question. thank you 

Here is my log 

> 

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--newline', u'-i', u'-k', u'-o', u'D:\\Youtube Video\\%(title)s.%(ext)s', u'-f', u'18', u'-v', u'http://www.dailymotion.com/video/x3tn7i4_jeep-gets-stuck-driving-through-water-off-roading-fail_fun']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2016.02.22
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1

>

**Comment by benb0jangles** [comment]
I have this also, help please

**Comment by MrS0m30n3** [comment]
Hi, @Rickyose 

From your log output it seems the command `--no-check-certificate` has not been added.

Sorry for the late response.

**Comment by Rickyose** [comment]
Hello, thank you for benb0jangles and MrS0m30n3 for replying here, after try again for it;s to work beside to add --no-check-certificate i also using default for video like benb0jangles said. just some update for anyone who hav same problem with me :)
