### ISSUE TITLE
Option to download files at a later time

### ISSUE THREAD

**Issue by ghost** [MrS0m30n3/youtube-dl-gui#89]

**Comment by nodiscc** [comment]
http://man.cx/at  
http://manpages.debian.org/cgi-bin/man.cgi?query=crontab

**Comment by sonchusarvesis** [comment]
When I fill the download list and then close youtube-dl-gui to download at a later time, the list is empty...

**Comment by 2E0PGS** [comment]
if you use the command line version of youtube-dl you can set a crontab to execute the download. for example: youtube-dl URL
https://github.com/rg3/youtube-dl

**Comment by nodiscc** [comment]
@MrS0m30n3 I think this should be renamed to "Persist download queue across sessions". Maybe youtube-dlg could store undownloaded items to a file, and reopen it on next run?

**Comment by MrS0m30n3** [comment]
Closing, since i'm not sure what the user asks.

If you mean add scheduling support, see https://github.com/MrS0m30n3/youtube-dl-gui/issues/63
If you mean persist download queue across sessions, then it's already in the [TODO](https://github.com/MrS0m30n3/youtube-dl-gui/blob/new_layout/TODO) list.
