### ISSUE TITLE
[Question] Download only audio file in 256k m4a or 256k webm?

### ISSUE THREAD

**Issue by Tox86** [MrS0m30n3/youtube-dl-gui#91]
Hi i cant download only audio with youtubeDLG.

**Comment by nodiscc** [comment]
@Tox86 Try `Options > Audio > Convert to Audio` ?

**Comment by nodiscc** [comment]
@MrS0m30n3 I think this issue can be closed.

**Comment by MrS0m30n3** [comment]
@Tox86 You can just select "webm 256k (DASH AUDIO)" under the Options > Video tab.
@nodiscc Thanks for your help dude :+1:
