### ISSUE TITLE
It is possible to download more than 3 files at a time. And why cant i delete completed files when they are ready without to restart the program. It is possible to get the program in Swedish language? And why cant i get the files name when i want to download them ?

### ISSUE THREAD

**Issue by ghost** [MrS0m30n3/youtube-dl-gui#97]

**Comment by nodiscc** [comment]
1. Check https://github.com/MrS0m30n3/youtube-dl-gui/issues/20
2. There is no "clear list" feature yet. Someone has to implement it.
3. You have to translate it yourself and send a patch https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/locale_build/HOWTO.md
4. I don't understand.

It is often better to open separate issues if you have several questions/problems.

**Comment by nodiscc** [comment]
@MrS0m30n3 I think this issue can be closed.
