### ISSUE TITLE
Rename files

### ISSUE THREAD

**Issue by ghost** [MrS0m30n3/youtube-dl-gui#98]
I mean it is possible to rename files when I download them with Youtube dlg. Sometimes I want another name that the program prefer.

**Comment by nodiscc** [comment]
You can change the naming format in `Options > Commands`, by specifying another naming scheme with `--output` (check https://github.com/rg3/youtube-dl/#filesystem-options, https://github.com/rg3/youtube-dl/#output-template-examples )

I use `--output '%(title)s-%(extractor)s-%(playlist_id)s%(id)s.%(ext)s'`, which results in filenames like `What Languages Sound Like To Foreigners-youtube-NAybcvlxivscw.mp4`

**Comment by nodiscc** [comment]
@MrS0m30n3 I think this issue can be closed.
